import {
  Package,
  Truck,
  Users,
  Building2,
  BarChart3,
  Bot,
  Bell,
  Shield,
  Leaf,
  MonitorSmartphone,
  Headphones,
  Link2,
  Map,
  Wallet,
  Navigation,
} from 'lucide-react';
import { SystemModule, SystemIntegration } from './types';

export const systemModulesData: SystemModule[] = [
  {
    id: 'shipments',
    name: 'إدارة الشحنات',
    icon: Package,
    description: 'نظام متكامل لإدارة شحنات النفايات من الإنشاء حتى التسليم',
    overallProgress: 92,
    strengths: [
      'واجهة سهلة الاستخدام لإنشاء الشحنات',
      'تتبع حالة الشحنات في الوقت الفعلي',
      'ربط الشحنات بين الجهات الثلاث (مولد، ناقل، مدور)',
      'طباعة تقارير الشحنات بتنسيقات متعددة',
      'دعم أنواع متعددة من المخلفات',
    ],
    weaknesses: [
      'عدم وجود نظام تنبيهات تلقائية عند تأخر الشحنات',
      'الحاجة لتحسين واجهة الفلترة المتقدمة',
    ],
    futureVision: 'تحويل النظام إلى منصة ذكية تستخدم AI للتنبؤ بأوقات التسليم وتحسين مسارات النقل تلقائياً',
    features: [
      { name: 'إنشاء شحنات جديدة', description: 'نموذج شامل لإنشاء الشحنات مع جميع التفاصيل', status: 'completed', progress: 100, priority: 'high', category: 'core' },
      { name: 'تتبع حالة الشحنات', description: 'Timeline تفاعلي لتتبع مراحل الشحنة', status: 'completed', progress: 100, priority: 'high', category: 'core' },
      { name: 'طباعة الشحنات', description: 'طباعة تقارير مفصلة بتنسيق PDF', status: 'completed', progress: 100, priority: 'medium', category: 'reporting' },
      { name: 'التنبيهات التلقائية', description: 'إشعارات عند تغيير حالة الشحنة', status: 'completed', progress: 100, priority: 'high', category: 'notifications' },
      { name: 'الفلترة المتقدمة', description: 'فلترة الشحنات حسب معايير متعددة', status: 'completed', progress: 100, priority: 'medium', category: 'ux' },
      { name: 'التغيير الجماعي للحالة', description: 'تغيير حالة عدة شحنات دفعة واحدة', status: 'completed', progress: 100, priority: 'medium', category: 'efficiency' },
    ],
  },
  {
    id: 'tracking',
    name: 'تتبع السائقين والمركبات',
    icon: Truck,
    description: 'نظام GPS متقدم لتتبع السائقين والمركبات على الخريطة',
    overallProgress: 95,
    strengths: [
      'تتبع مباشر لمواقع السائقين على الخريطة',
      'عرض سجل المسارات التاريخية',
      'دعم Mapbox للخرائط عالية الجودة',
      'تحديد المواقع الجغرافية بدقة',
      'نظام ملاحة متكامل',
    ],
    weaknesses: [
      'استهلاك عالي للبطارية في التطبيق - يحتاج تحسين',
    ],
    futureVision: 'إضافة نظام تجنب الازدحام وتحسين المسارات الذكي',
    features: [
      { name: 'خريطة السائقين', description: 'عرض مواقع جميع السائقين النشطين', status: 'completed', progress: 100, priority: 'high', category: 'core' },
      { name: 'سجل المواقع', description: 'تتبع تاريخ حركة السائق', status: 'completed', progress: 100, priority: 'medium', category: 'history' },
      { name: 'الملاحة التفاعلية', description: 'نظام ملاحة متكامل للسائقين', status: 'completed', progress: 100, priority: 'high', category: 'navigation' },
      { name: 'تقدير وقت الوصول', description: 'حساب الوقت المتوقع للوصول', status: 'completed', progress: 90, priority: 'medium', category: 'estimation' },
      { name: 'تنبيهات الخروج عن المسار', description: 'تنبيه عند انحراف السائق', status: 'planned', progress: 20, priority: 'low', category: 'alerts' },
    ],
  },
  {
    id: 'users',
    name: 'إدارة المستخدمين والجهات',
    icon: Users,
    description: 'نظام شامل لإدارة الجهات والموظفين والصلاحيات',
    overallProgress: 95,
    strengths: [
      'تسجيل الجهات بأنواعها الثلاث (مولد، ناقل، مدور)',
      'نظام صلاحيات متعدد المستويات',
      'إدارة الموظفين لكل جهة',
      'ملف تعريفي شامل للجهات',
      'نظام موافقات متكامل',
    ],
    weaknesses: [
      'الحاجة لتبسيط عملية التسجيل للمستخدمين الجدد',
    ],
    futureVision: 'تحويل ملفات الجهات إلى بورتفوليو تفاعلي مع تقييمات وشهادات',
    features: [
      { name: 'تسجيل الجهات', description: 'نموذج تسجيل شامل للجهات الجديدة', status: 'completed', progress: 100, priority: 'high', category: 'core' },
      { name: 'إدارة الموظفين', description: 'إضافة وإدارة موظفي الجهة', status: 'completed', progress: 100, priority: 'high', category: 'management' },
      { name: 'نظام الصلاحيات', description: 'تحديد صلاحيات كل موظف', status: 'completed', progress: 100, priority: 'high', category: 'security' },
      { name: 'ملف الجهة التعريفي', description: 'عرض معلومات الجهة الشاملة', status: 'completed', progress: 100, priority: 'medium', category: 'profile' },
      { name: 'نظام الدعوات', description: 'دعوة موظفين جدد عبر البريد', status: 'planned', progress: 10, priority: 'low', category: 'onboarding', suggestions: ['إضافة روابط دعوة مؤقتة'] },
    ],
  },
  {
    id: 'partners',
    name: 'الشركاء والعقود',
    icon: Building2,
    description: 'إدارة العلاقات مع الشركاء والعقود القانونية',
    overallProgress: 90,
    strengths: [
      'ربط الجهات كشركاء',
      'إنشاء عقود قانونية تلقائياً',
      'قوالب عقود متعددة',
      'التحقق من العقود عبر QR Code',
      'حسابات الشركاء المتبادلة',
    ],
    weaknesses: [
      'الحاجة لمزيد من قوالب العقود المتخصصة',
    ],
    futureVision: 'نظام ذكي لإدارة العقود مع تجديد تلقائي وتحليل بنود العقود بالذكاء الاصطناعي',
    features: [
      { name: 'إضافة شركاء', description: 'ربط الجهات كشركاء تجاريين', status: 'completed', progress: 100, priority: 'high', category: 'core' },
      { name: 'إنشاء العقود', description: 'إنشاء عقود قانونية من القوالب', status: 'completed', progress: 100, priority: 'high', category: 'legal' },
      { name: 'قوالب العقود', description: 'مكتبة قوالب عقود جاهزة', status: 'completed', progress: 95, priority: 'medium', category: 'templates' },
      { name: 'التحقق من العقود', description: 'نظام QR للتحقق من صحة العقد', status: 'completed', progress: 100, priority: 'medium', category: 'verification' },
      { name: 'تنبيهات انتهاء العقود', description: 'إشعارات قبل انتهاء صلاحية العقد', status: 'in_progress', progress: 50, priority: 'medium', category: 'alerts', suggestions: ['استخدام Supabase Edge Functions للجدولة'] },
    ],
  },
  {
    id: 'reports',
    name: 'التقارير والإحصائيات',
    icon: BarChart3,
    description: 'تقارير شاملة وإحصائيات تفاعلية للأداء',
    overallProgress: 92,
    strengths: [
      'تقارير مفصلة للشحنات',
      'رسوم بيانية تفاعلية',
      'تصدير PDF احترافي',
      'تقارير مجمعة للفترات الزمنية',
      'شهادات إعادة التدوير',
    ],
    weaknesses: [
      'الحاجة لمزيد من أنواع التقارير التحليلية',
    ],
    futureVision: 'لوحة تحكم ذكية مع تحليلات AI وتوقعات مستقبلية',
    features: [
      { name: 'تقارير الشحنات', description: 'تقارير تفصيلية لكل شحنة', status: 'completed', progress: 100, priority: 'high', category: 'core' },
      { name: 'التقرير المجمع', description: 'تقرير شامل لفترة زمنية', status: 'completed', progress: 100, priority: 'high', category: 'aggregate' },
      { name: 'الرسوم البيانية', description: 'charts تفاعلية للإحصائيات', status: 'completed', progress: 100, priority: 'medium', category: 'visualization' },
      { name: 'تصدير Excel', description: 'تصدير البيانات لـ Excel', status: 'in_progress', progress: 60, priority: 'medium', category: 'export', suggestions: ['استخدام مكتبة xlsx'] },
      { name: 'تحليلات AI', description: 'تحليل ذكي للبيانات والتوقعات', status: 'in_progress', progress: 70, priority: 'high', category: 'ai' },
    ],
  },
  {
    id: 'ai',
    name: 'أدوات الذكاء الاصطناعي',
    icon: Bot,
    description: 'أدوات AI متقدمة لتحسين الكفاءة والدقة',
    overallProgress: 85,
    strengths: [
      'استخراج بيانات من الصور',
      'تصنيف المخلفات تلقائياً',
      'مساعد ذكي للإجابة عن الأسئلة',
      'تحليل البيانات والإحصائيات',
      'إنشاء فيديوهات ترويجية',
    ],
    weaknesses: [
      'دقة الاستخراج للغة العربية تحتاج تحسين',
    ],
    futureVision: 'منصة AI متكاملة تتعلم من البيانات وتقدم توصيات استباقية',
    features: [
      { name: 'استخراج بيانات الوزن', description: 'استخراج البيانات من صور الإيصالات', status: 'completed', progress: 90, priority: 'high', category: 'extraction' },
      { name: 'تصنيف المخلفات', description: 'تصنيف تلقائي لنوع المخلف', status: 'completed', progress: 85, priority: 'medium', category: 'classification' },
      { name: 'المساعد الذكي', description: 'chatbot للإجابة عن الاستفسارات', status: 'completed', progress: 95, priority: 'high', category: 'assistant' },
      { name: 'تحليلات متقدمة', description: 'تحليل الأنماط والتوقعات', status: 'in_progress', progress: 70, priority: 'medium', category: 'analytics' },
      { name: 'إنشاء الفيديوهات', description: 'إنشاء فيديوهات ترويجية بـ AI', status: 'completed', progress: 85, priority: 'low', category: 'content' },
    ],
  },
  {
    id: 'notifications',
    name: 'الإشعارات والمحادثات',
    icon: Bell,
    description: 'نظام إشعارات فوري ومحادثات بين الجهات',
    overallProgress: 90,
    strengths: [
      'إشعارات فورية عند الأحداث المهمة',
      'أصوات تنبيه قابلة للتخصيص',
      'محادثات بين الجهات',
      'سجل كامل للإشعارات',
      'Realtime Updates',
    ],
    weaknesses: [
      'عدم دعم إشعارات Push للموبايل بشكل كامل',
    ],
    futureVision: 'نظام تواصل متكامل مع دعم الوسائط المتعددة والاجتماعات الافتراضية',
    features: [
      { name: 'الإشعارات الفورية', description: 'تنبيهات لحظية عند الأحداث', status: 'completed', progress: 100, priority: 'high', category: 'realtime' },
      { name: 'أصوات التنبيه', description: 'أصوات مخصصة للإشعارات', status: 'completed', progress: 100, priority: 'low', category: 'customization' },
      { name: 'المحادثات', description: 'نظام محادثات بين الجهات', status: 'completed', progress: 90, priority: 'medium', category: 'chat' },
      { name: 'Push Notifications', description: 'إشعارات للهواتف المحمولة', status: 'in_progress', progress: 40, priority: 'high', category: 'mobile', suggestions: ['استخدام Firebase Cloud Messaging'] },
    ],
  },
  {
    id: 'security',
    name: 'الأمان والتحقق',
    icon: Shield,
    description: 'نظام أمان متعدد الطبقات للحماية والتحقق',
    overallProgress: 92,
    strengths: [
      'مصادقة آمنة',
      'نظام RLS لحماية البيانات',
      'التحقق من الوثائق',
      'سجل النشاطات للتتبع',
      'تشفير البيانات الحساسة',
    ],
    weaknesses: [
      'الحاجة لإضافة المصادقة الثنائية 2FA',
    ],
    futureVision: 'نظام أمان متقدم مع التحقق البيومتري وشهادات ISO 27001',
    features: [
      { name: 'المصادقة الآمنة', description: 'تسجيل دخول آمن ومشفر', status: 'completed', progress: 100, priority: 'high', category: 'auth' },
      { name: 'حماية البيانات RLS', description: 'سياسات أمان على مستوى الصفوف', status: 'completed', progress: 100, priority: 'high', category: 'security' },
      { name: 'التحقق من الوثائق', description: 'نظام AI للتحقق من صحة الوثائق', status: 'completed', progress: 90, priority: 'medium', category: 'verification' },
      { name: 'المصادقة الثنائية 2FA', description: 'طبقة حماية إضافية', status: 'planned', progress: 10, priority: 'high', category: 'auth', suggestions: ['استخدام TOTP أو SMS'] },
      { name: 'سجل النشاطات', description: 'تتبع جميع العمليات', status: 'completed', progress: 90, priority: 'medium', category: 'audit' },
    ],
  },
  {
    id: 'sustainability',
    name: 'الاستدامة والبيئة',
    icon: Leaf,
    description: 'أدوات لقياس وتحسين الأثر البيئي',
    overallProgress: 85,
    strengths: [
      'حساب البصمة الكربونية',
      'شهادات إعادة التدوير',
      'تقارير الاستدامة',
      'إحصائيات بيئية شاملة',
    ],
    weaknesses: [
      'الحاجة لربط مع منظمات بيئية دولية',
    ],
    futureVision: 'منصة استدامة شاملة مع شهادات دولية وتتبع أهداف SDGs',
    features: [
      { name: 'البصمة الكربونية', description: 'حساب انبعاثات CO2', status: 'completed', progress: 90, priority: 'medium', category: 'carbon' },
      { name: 'شهادات التدوير', description: 'إصدار شهادات معتمدة', status: 'completed', progress: 100, priority: 'high', category: 'certificates' },
      { name: 'تقارير الاستدامة', description: 'تقارير ESG شاملة', status: 'in_progress', progress: 70, priority: 'medium', category: 'reporting' },
      { name: 'أهداف SDGs', description: 'ربط مع أهداف التنمية المستدامة', status: 'planned', progress: 30, priority: 'low', category: 'global' },
    ],
  },
  {
    id: 'ux',
    name: 'تجربة المستخدم UI/UX',
    icon: MonitorSmartphone,
    description: 'واجهة مستخدم حديثة ومتجاوبة',
    overallProgress: 95,
    strengths: [
      'تصميم عصري ومتجاوب',
      'دعم الوضع الداكن والفاتح',
      'رسوم متحركة سلسة',
      'واجهة عربية كاملة RTL',
      'دليل مستخدم تفاعلي',
    ],
    weaknesses: [
      'بعض الصفحات تحتاج تبسيط',
    ],
    futureVision: 'تجربة مستخدم ممتازة مع personalization وإمكانية وصول كاملة',
    features: [
      { name: 'التصميم المتجاوب', description: 'يعمل على جميع الأجهزة', status: 'completed', progress: 100, priority: 'high', category: 'responsive' },
      { name: 'الوضع الداكن', description: 'دعم الثيمات المتعددة', status: 'completed', progress: 100, priority: 'medium', category: 'theming' },
      { name: 'الأنيميشن', description: 'حركات سلسة مع Framer Motion', status: 'completed', progress: 100, priority: 'low', category: 'animation' },
      { name: 'تخصيص الواجهة', description: 'إمكانية تخصيص الألوان والتخطيط', status: 'completed', progress: 90, priority: 'low', category: 'customization' },
      { name: 'إمكانية الوصول A11y', description: 'دعم ذوي الاحتياجات الخاصة', status: 'in_progress', progress: 60, priority: 'medium', category: 'accessibility', suggestions: ['إضافة قارئ شاشة ولوحة مفاتيح'] },
    ],
  },
  {
    id: 'support',
    name: 'الدعم الفني',
    icon: Headphones,
    description: 'نظام متكامل لإدارة تذاكر الدعم والشكاوى',
    overallProgress: 100,
    strengths: [
      'نظام تذاكر متكامل مع تتبع الحالة',
      'محادثات فورية على التذاكر',
      'ملاحظات داخلية للفريق',
      'تقييم رضا العملاء',
      'إحصائيات شاملة للدعم',
      'ربط التذاكر بالشحنات والشركاء',
    ],
    weaknesses: [],
    futureVision: 'نظام دعم ذكي مع chatbot للإجابة التلقائية وتحليل المشاعر',
    features: [
      { name: 'إنشاء التذاكر', description: 'إنشاء تذاكر دعم فني متكاملة', status: 'completed', progress: 100, priority: 'high', category: 'core' },
      { name: 'المحادثات الفورية', description: 'دردشة مباشرة على التذاكر', status: 'completed', progress: 100, priority: 'high', category: 'chat' },
      { name: 'الملاحظات الداخلية', description: 'ملاحظات خاصة بفريق الدعم', status: 'completed', progress: 100, priority: 'medium', category: 'internal' },
      { name: 'تقييم الرضا', description: 'تقييم العميل بعد حل التذكرة', status: 'completed', progress: 100, priority: 'medium', category: 'feedback' },
      { name: 'إحصائيات الدعم', description: 'تقارير عن أداء فريق الدعم', status: 'completed', progress: 100, priority: 'high', category: 'analytics' },
    ],
  },
];

// System Integrations Data - تحليل الربط بين أجزاء النظام
export const systemIntegrationsData: SystemIntegration[] = [
  {
    id: 'entities-shipments',
    name: 'ربط الجهات بالشحنات',
    icon: Link2,
    description: 'العلاقة الثلاثية بين المولد والناقل والمدور في كل شحنة',
    dataFlowSummary: 'كل شحنة ترتبط بثلاث جهات (مولد ← ناقل ← مدور) مع تتبع كامل لدورة الحياة',
    overallStrength: 98,
    keyFeatures: [
      'ربط إلزامي بالجهة المولدة (generator_id)',
      'ربط بالناقل المسؤول عن النقل (transporter_id)',
      'ربط بجهة التدوير للمعالجة النهائية (recycler_id)',
      'ربط اختياري بالسائق المنفذ (driver_id)',
      'تتبع من أنشأ الشحنة (created_by)',
    ],
    links: [
      {
        source: 'organizations',
        target: 'shipments',
        description: 'الجهات ترتبط بالشحنات كمولد أو ناقل أو مدور',
        dataFlow: ['generator_id', 'transporter_id', 'recycler_id'],
        status: 'strong',
        tables: ['organizations', 'shipments'],
      },
      {
        source: 'drivers',
        target: 'shipments',
        description: 'السائق ينفذ الشحنة ميدانياً',
        dataFlow: ['driver_id', 'status_updates'],
        status: 'strong',
        tables: ['drivers', 'shipments'],
      },
      {
        source: 'profiles',
        target: 'shipments',
        description: 'المستخدم ينشئ ويتابع الشحنات',
        dataFlow: ['created_by', 'notifications'],
        status: 'strong',
        tables: ['profiles', 'shipments', 'notifications'],
      },
    ],
    technicalNotes: [
      'استخدام Foreign Keys للربط مع ضمان سلامة البيانات',
      'RLS policies تضمن رؤية الشحنات للجهات المعنية فقط',
      'Triggers تُطلق إشعارات تلقائية لجميع الأطراف',
      'دعم الشحنات المتعددة للسائق الواحد',
    ],
    improvements: [
      'إضافة ربط بالمركبة المستخدمة في النقل',
      'ربط بالعقود السارية تلقائياً',
    ],
  },
  {
    id: 'accounts-integration',
    name: 'منظومة الحسابات والمالية',
    icon: Wallet,
    description: 'الربط بين الشحنات والفواتير والإيداعات وأرصدة الشركاء',
    dataFlowSummary: 'شحنة ← فاتورة ← مدفوعات/إيداعات ← رصيد الشريك',
    overallStrength: 95,
    keyFeatures: [
      'حساب تلقائي لقيمة الشحنات من جدول الأسعار',
      'ربط الإيداعات بالشريك (منظمة أو خارجي)',
      'دفتر أستاذ تراكمي لكل شريك',
      'فصل الحسابات حسب نوع المخلف',
      'دعم الشركاء الخارجيين (external_partners)',
    ],
    links: [
      {
        source: 'shipments',
        target: 'invoices',
        description: 'الشحنة المؤكدة تُنشئ فاتورة تلقائياً',
        dataFlow: ['shipment_id', 'amount', 'waste_type'],
        status: 'strong',
        tables: ['shipments', 'invoices', 'aggregate_invoices'],
      },
      {
        source: 'deposits',
        target: 'partner_balances',
        description: 'الإيداعات تُحدّث رصيد الشريك',
        dataFlow: ['amount', 'partner_id', 'balance_update'],
        status: 'strong',
        tables: ['deposits', 'partner_balances', 'payments'],
      },
      {
        source: 'waste_type_prices',
        target: 'shipments',
        description: 'أسعار المخلفات تحدد قيمة الشحنة',
        dataFlow: ['price_per_unit', 'tax_rate', 'total_calculation'],
        status: 'strong',
        tables: ['waste_type_prices', 'shipments'],
      },
      {
        source: 'external_partners',
        target: 'deposits',
        description: 'ربط الإيداعات بشركاء خارج النظام',
        dataFlow: ['external_partner_id', 'deposit_amount'],
        status: 'strong',
        tables: ['external_partners', 'deposits'],
      },
    ],
    technicalNotes: [
      'Trigger update_partner_balance_on_payment يحدث الرصيد تلقائياً',
      'دعم العملات المتعددة (EGP افتراضي)',
      'حساب الضرائب (شاملة/غير شاملة) في جدول الأسعار',
      'Running Balance في دفتر الأستاذ',
    ],
    improvements: [
      'إضافة تقارير ربحية لكل نوع مخلف',
      'ربط مع بوابات الدفع الإلكتروني',
      'تنبيهات الفواتير المتأخرة',
    ],
  },
  {
    id: 'tracking-maps',
    name: 'التتبع والخرائط',
    icon: Map,
    description: 'ربط تتبع السائقين بالشحنات والمواقع الجغرافية',
    dataFlowSummary: 'موقع السائق ← سجل المواقع ← مسار الشحنة ← الخريطة التفاعلية',
    overallStrength: 92,
    keyFeatures: [
      'تسجيل مواقع السائقين في driver_location_logs',
      'حساب المسار الفعلي vs المخطط',
      'Mapbox GL JS للخرائط التفاعلية',
      'Geocoding للبحث عن العناوين',
      'تقدير وقت الوصول ETA',
    ],
    links: [
      {
        source: 'drivers',
        target: 'driver_location_logs',
        description: 'تسجيل موقع السائق كل فترة',
        dataFlow: ['latitude', 'longitude', 'speed', 'heading', 'accuracy'],
        status: 'strong',
        tables: ['drivers', 'driver_location_logs'],
      },
      {
        source: 'shipments',
        target: 'tracking_data',
        description: 'الشحنة تحمل بيانات المسار',
        dataFlow: ['pickup_location', 'delivery_location', 'route_polyline'],
        status: 'strong',
        tables: ['shipments'],
      },
      {
        source: 'driver_trips',
        target: 'shipments',
        description: 'رحلة السائق مرتبطة بالشحنة',
        dataFlow: ['trip_id', 'shipment_id', 'distance_km', 'duration'],
        status: 'moderate',
        tables: ['driver_trips', 'shipments'],
      },
    ],
    technicalNotes: [
      'استخدام Supabase Realtime لتحديث المواقع لحظياً',
      'Mapbox Directions API لحساب المسارات',
      'تخزين المسار كـ GeoJSON في قاعدة البيانات',
      'Presence API لمعرفة من يتابع السائق',
    ],
    improvements: [
      'إضافة Geofencing للتنبيه عند الوصول',
      'تحسين دقة GPS في المناطق المزدحمة',
      'تكامل مع نظام إدارة الأسطول',
    ],
  },
  {
    id: 'navigation-routing',
    name: 'الملاحة والتوجيه',
    icon: Navigation,
    description: 'نظام الملاحة للسائقين وحساب المسارات',
    dataFlowSummary: 'نقطة البداية ← حساب المسار ← التوجيه خطوة بخطوة ← الوصول',
    overallStrength: 88,
    keyFeatures: [
      'ملاحة مدمجة في التطبيق',
      'ربط مباشر مع Google Maps للتوجيه',
      'حساب بدائل المسارات',
      'تقدير المسافة والوقت',
      'دعم اللغة العربية في الخرائط',
    ],
    links: [
      {
        source: 'shipments',
        target: 'navigation',
        description: 'عناوين الشحنة تحدد نقاط الملاحة',
        dataFlow: ['pickup_address', 'delivery_address', 'coordinates'],
        status: 'strong',
        tables: ['shipments'],
      },
      {
        source: 'mapbox_api',
        target: 'route_calculation',
        description: 'Mapbox يحسب المسار الأمثل',
        dataFlow: ['waypoints', 'route_geometry', 'duration', 'distance'],
        status: 'strong',
        tables: [],
      },
    ],
    technicalNotes: [
      'Mapbox Directions API مع دعم اللغة العربية',
      'تخزين المسارات المحسوبة للاستخدام لاحقاً',
      'Deep links لـ Google Maps للملاحة الخارجية',
      'تحديث ETA بناءً على حركة المرور',
    ],
    improvements: [
      'إضافة تجنب الازدحام الذكي',
      'تكامل مع بيانات المرور الحية',
      'ملاحة صوتية بالعربية',
    ],
  },
  {
    id: 'notifications-realtime',
    name: 'الإشعارات والتحديثات الفورية',
    icon: Bell,
    description: 'ربط الأحداث بالإشعارات والتنبيهات اللحظية',
    dataFlowSummary: 'حدث (شحنة/تذكرة/وثيقة) ← Trigger ← إشعار ← المستخدمين المعنيين',
    overallStrength: 94,
    keyFeatures: [
      'إشعارات تلقائية عند تغيير حالة الشحنة',
      'تنبيه الأدمن عند رفع وثائق جديدة',
      'إشعارات تذاكر الدعم الفني',
      'Realtime للتحديثات اللحظية',
      'أصوات تنبيه قابلة للتخصيص',
    ],
    links: [
      {
        source: 'shipments',
        target: 'notifications',
        description: 'تغيير حالة الشحنة يُنشئ إشعاراً',
        dataFlow: ['shipment_id', 'status_change', 'target_users'],
        status: 'strong',
        tables: ['shipments', 'notifications'],
      },
      {
        source: 'support_tickets',
        target: 'notifications',
        description: 'تذكرة جديدة/تحديث تُنشئ إشعاراً',
        dataFlow: ['ticket_id', 'status', 'assigned_to'],
        status: 'strong',
        tables: ['support_tickets', 'ticket_messages', 'notifications'],
      },
      {
        source: 'organization_documents',
        target: 'notifications',
        description: 'رفع وثيقة يُنبه الأدمن',
        dataFlow: ['document_id', 'organization_id', 'admin_users'],
        status: 'strong',
        tables: ['organization_documents', 'notifications'],
      },
    ],
    technicalNotes: [
      'Database Triggers لإنشاء الإشعارات تلقائياً',
      'Supabase Realtime للتحديثات اللحظية',
      'SECURITY DEFINER للوصول الآمن',
      'تجنب الإشعارات المكررة عبر EXISTS checks',
    ],
    improvements: [
      'Push Notifications للموبايل (FCM)',
      'إشعارات البريد الإلكتروني للأحداث المهمة',
      'تلخيص يومي للإشعارات',
    ],
  },
  {
    id: 'contracts-partners',
    name: 'العقود والشراكات',
    icon: Building2,
    description: 'ربط العقود بالشركاء والشحنات والأسعار',
    dataFlowSummary: 'شريك ← عقد ← شروط الأسعار ← تطبيق على الشحنات',
    overallStrength: 85,
    keyFeatures: [
      'عقود قانونية لكل شراكة',
      'قوالب عقود جاهزة للتخصيص',
      'التحقق من العقود عبر QR Code',
      'ربط العقود بأنواع المخلفات',
      'تتبع تواريخ الانتهاء',
    ],
    links: [
      {
        source: 'organizations',
        target: 'contracts',
        description: 'المنظمة تُنشئ عقوداً مع شركائها',
        dataFlow: ['organization_id', 'partner_organization_id', 'terms'],
        status: 'strong',
        tables: ['organizations', 'contracts'],
      },
      {
        source: 'contract_templates',
        target: 'contracts',
        description: 'القوالب تُستخدم لإنشاء العقود',
        dataFlow: ['template_id', 'custom_terms', 'waste_types'],
        status: 'strong',
        tables: ['contract_templates', 'contracts'],
      },
      {
        source: 'contracts',
        target: 'waste_type_prices',
        description: 'العقد يحدد أسعار المخلفات مع الشريك',
        dataFlow: ['contract_id', 'price_per_unit', 'validity'],
        status: 'moderate',
        tables: ['contracts', 'waste_type_prices'],
      },
    ],
    technicalNotes: [
      'verification_code فريد لكل عقد للتحقق',
      'QR Code يحمل رابط التحقق الرسمي',
      'دعم أنواع عقود متعددة (شراء، نقل، تدوير)',
      'تخزين الإصدارات المخصصة في contract_custom_versions',
    ],
    improvements: [
      'ربط تلقائي بين العقد والشحنات الجديدة',
      'تنبيهات قبل انتهاء العقود',
      'تجديد تلقائي للعقود',
    ],
  },
  {
    id: 'documents-verification',
    name: 'الوثائق والتحقق',
    icon: Shield,
    description: 'ربط وثائق الجهات بعمليات التحقق والموافقات',
    dataFlowSummary: 'جهة ← رفع وثيقة ← تحقق AI ← مراجعة أدمن ← موافقة/رفض',
    overallStrength: 90,
    keyFeatures: [
      'رفع وثائق متعددة الأنواع',
      'تحقق AI من صحة الوثائق',
      'سجل كامل لعمليات التحقق',
      'ربط بحالة التفعيل للجهة',
      'تنبيهات انتهاء الصلاحية',
    ],
    links: [
      {
        source: 'organizations',
        target: 'organization_documents',
        description: 'كل جهة ترفع وثائقها الرسمية',
        dataFlow: ['organization_id', 'document_type', 'file_url'],
        status: 'strong',
        tables: ['organizations', 'organization_documents'],
      },
      {
        source: 'organization_documents',
        target: 'document_verifications',
        description: 'كل وثيقة لها سجل تحقق',
        dataFlow: ['document_id', 'verification_status', 'ai_analysis'],
        status: 'strong',
        tables: ['organization_documents', 'document_verifications'],
      },
      {
        source: 'document_verifications',
        target: 'organizations',
        description: 'التحقق يؤثر على حالة الجهة',
        dataFlow: ['is_verified', 'verification_date'],
        status: 'strong',
        tables: ['document_verifications', 'organizations'],
      },
    ],
    technicalNotes: [
      'Storage buckets منفصلة للوثائق',
      'AI analysis يُخزن كـ JSONB',
      'سجل كامل للتحقق مع user_id و timestamp',
      'RLS تحمي الوثائق من الوصول غير المصرح',
    ],
    improvements: [
      'OCR للتعرف على بيانات الوثائق',
      'تكامل مع سجلات حكومية للتحقق',
      'تجديد تلقائي للوثائق منتهية الصلاحية',
    ],
  },
  {
    id: 'support-system',
    name: 'الدعم الفني والتذاكر',
    icon: Headphones,
    description: 'ربط تذاكر الدعم بالجهات والشحنات والمستخدمين',
    dataFlowSummary: 'مستخدم ← تذكرة ← رسائل ← حل ← تقييم',
    overallStrength: 100,
    keyFeatures: [
      'تذاكر مرتبطة بالجهة والشحنة',
      'محادثات فورية (Realtime)',
      'ملاحظات داخلية للفريق',
      'مراقبون للتذاكر (Watchers)',
      'تقييم رضا العملاء',
    ],
    links: [
      {
        source: 'organizations',
        target: 'support_tickets',
        description: 'كل تذكرة مرتبطة بجهة',
        dataFlow: ['organization_id', 'created_by', 'category'],
        status: 'strong',
        tables: ['organizations', 'support_tickets'],
      },
      {
        source: 'support_tickets',
        target: 'ticket_messages',
        description: 'رسائل المحادثة على التذكرة',
        dataFlow: ['ticket_id', 'message', 'is_internal_note'],
        status: 'strong',
        tables: ['support_tickets', 'ticket_messages'],
      },
      {
        source: 'support_tickets',
        target: 'ticket_watchers',
        description: 'مستخدمون يتابعون التذكرة',
        dataFlow: ['ticket_id', 'user_id', 'organization_id'],
        status: 'strong',
        tables: ['support_tickets', 'ticket_watchers'],
      },
      {
        source: 'support_tickets',
        target: 'notifications',
        description: 'إشعارات تلقائية للتحديثات',
        dataFlow: ['ticket_number', 'status_change', 'assignee'],
        status: 'strong',
        tables: ['support_tickets', 'notifications'],
      },
    ],
    technicalNotes: [
      'Realtime subscriptions للرسائل الجديدة',
      'Triggers للإشعارات التلقائية (notify_admin_new_ticket, notify_ticket_update)',
      'ticket_number يُولد تلقائياً (TKT-YYYYMMDD-XXXX)',
      'دعم الأولويات والتصنيفات',
    ],
    improvements: [
      'Chatbot للإجابات التلقائية',
      'تحليل مشاعر العملاء بـ AI',
      'SLA tracking وتنبيهات التأخير',
    ],
  },
];
