/**
 * مكتبة قوالب تقارير إعادة التدوير
 * 100+ قالب جاهز لجميع أنواع المخلفات
 */

export interface RecyclingReportTemplate {
  id: string;
  name: string;
  description: string;
  waste_category: 'hazardous' | 'non_hazardous' | 'medical_hazardous' | 'all';
  waste_types: string[];
  opening_declaration: string;
  processing_details_template: string;
  closing_declaration: string;
  tags: string[];
}

// ============================================
// قوالب البلاستيك (10 قوالب)
// ============================================
const plasticTemplates: RecyclingReportTemplate[] = [
  {
    id: 'plastic-001',
    name: 'تقرير تدوير البلاستيك - قياسي',
    description: 'قالب قياسي لإعادة تدوير مخلفات البلاستيك العامة',
    waste_category: 'non_hazardous',
    waste_types: ['plastic'],
    opening_declaration: 'نقر نحن جهة إعادة التدوير المعتمدة باستلام شحنة المخلفات البلاستيكية الموضحة أدناه، والتي تم فحصها والتأكد من مطابقتها للمواصفات المتفق عليها.',
    processing_details_template: 'تم فرز المخلفات البلاستيكية حسب النوع (PET, HDPE, LDPE, PP) ثم غسلها وتجفيفها وطحنها لإنتاج حبيبات بلاستيكية معاد تدويرها صالحة للاستخدام الصناعي.',
    closing_declaration: 'نؤكد إتمام عملية إعادة تدوير المخلفات البلاستيكية بنجاح وفق المعايير البيئية المعتمدة، وتم تحويلها إلى مواد خام ثانوية قابلة للتصنيع.',
    tags: ['بلاستيك', 'PET', 'قياسي'],
  },
  {
    id: 'plastic-002',
    name: 'تدوير عبوات PET',
    description: 'متخصص في زجاجات المياه والمشروبات البلاستيكية',
    waste_category: 'non_hazardous',
    waste_types: ['plastic'],
    opening_declaration: 'نقر باستلام شحنة عبوات PET البلاستيكية الفارغة، وتم التحقق من خلوها من أي مواد ملوثة أو سوائل متبقية.',
    processing_details_template: 'تم غسل العبوات وإزالة الملصقات والأغطية، ثم طحنها وتحويلها إلى رقائق PET نظيفة جاهزة لإعادة التصنيع في صناعة الألياف والأقمشة.',
    closing_declaration: 'تم تدوير عبوات PET بكفاءة عالية تتجاوز 95% ويمكن استخدام المنتج النهائي في الصناعات النسيجية.',
    tags: ['PET', 'زجاجات', 'مياه'],
  },
  {
    id: 'plastic-003',
    name: 'تدوير البلاستيك الصناعي',
    description: 'لمخلفات المصانع والخطوط الإنتاجية',
    waste_category: 'non_hazardous',
    waste_types: ['plastic'],
    opening_declaration: 'تم استلام مخلفات البلاستيك الصناعي من خطوط الإنتاج، والتي تشمل الزوائد والقطع المرفوضة من عمليات التشكيل.',
    processing_details_template: 'تم فرز المخلفات حسب درجة النقاء واللون، ثم إعادة طحنها وخلطها بنسب محددة لإنتاج حبيبات بلاستيكية متجانسة للاستخدام الصناعي.',
    closing_declaration: 'تمت معالجة المخلفات الصناعية البلاستيكية وتحويلها إلى مواد خام ثانوية عالية الجودة مناسبة للتصنيع.',
    tags: ['صناعي', 'مصانع', 'إنتاج'],
  },
  {
    id: 'plastic-004',
    name: 'تدوير أكياس البلاستيك LDPE',
    description: 'لأكياس التسوق والتغليف المرنة',
    waste_category: 'non_hazardous',
    waste_types: ['plastic'],
    opening_declaration: 'نقر باستلام شحنة أكياس البلاستيك المرنة (LDPE) المجمعة، وتم فحصها للتأكد من خلوها من التلوث.',
    processing_details_template: 'تم غسل الأكياس وتجفيفها ثم صهرها وتحويلها إلى حبيبات LDPE معاد تدويرها تصلح لتصنيع أكياس قمامة وأنابيب ري.',
    closing_declaration: 'أكملنا تدوير أكياس البلاستيك بنجاح مع الحفاظ على جودة المادة المعاد تدويرها.',
    tags: ['أكياس', 'LDPE', 'تغليف'],
  },
  {
    id: 'plastic-005',
    name: 'تدوير مخلفات التعبئة والتغليف',
    description: 'للأغلفة والصناديق البلاستيكية',
    waste_category: 'non_hazardous',
    waste_types: ['plastic'],
    opening_declaration: 'استلمنا شحنة مخلفات التعبئة والتغليف البلاستيكية من المستودعات والمحلات التجارية.',
    processing_details_template: 'تم فصل المواد المختلفة (أفلام التغليف، صناديق، فوم) ومعالجة كل نوع على حدة بالتقنية المناسبة.',
    closing_declaration: 'تمت إعادة تدوير مخلفات التغليف وتحويلها إلى منتجات مفيدة مع تحقيق أهداف الاستدامة.',
    tags: ['تغليف', 'تعبئة', 'تجاري'],
  },
  {
    id: 'plastic-006',
    name: 'تدوير قطع غيار السيارات البلاستيكية',
    description: 'للصدامات والأجزاء البلاستيكية للمركبات',
    waste_category: 'non_hazardous',
    waste_types: ['plastic'],
    opening_declaration: 'تم استلام قطع الغيار البلاستيكية المستعملة من ورش السيارات ومراكز التصليح.',
    processing_details_template: 'تم تفكيك القطع وفصل المعادن والمواد الأخرى، ثم طحن البلاستيك (PP, ABS) وتحويله إلى حبيبات للتصنيع.',
    closing_declaration: 'نؤكد تدوير قطع السيارات البلاستيكية وإعادة استخدامها في تصنيع منتجات صناعية جديدة.',
    tags: ['سيارات', 'صدامات', 'PP', 'ABS'],
  },
  {
    id: 'plastic-007',
    name: 'تدوير الأثاث البلاستيكي',
    description: 'للكراسي والطاولات البلاستيكية المستعملة',
    waste_category: 'non_hazardous',
    waste_types: ['plastic'],
    opening_declaration: 'نقر باستلام الأثاث البلاستيكي المستعمل (كراسي، طاولات، خزائن) للتدوير.',
    processing_details_template: 'تم تفكيك الأثاث وفصل الألوان والأنواع، ثم طحنها وإعادة تشكيلها لمنتجات بلاستيكية جديدة.',
    closing_declaration: 'تم تحويل الأثاث البلاستيكي القديم إلى مواد خام جاهزة لتصنيع منتجات جديدة.',
    tags: ['أثاث', 'كراسي', 'منزلي'],
  },
  {
    id: 'plastic-008',
    name: 'تدوير مخلفات البناء البلاستيكية',
    description: 'للأنابيب والمواسير PVC',
    waste_category: 'non_hazardous',
    waste_types: ['plastic'],
    opening_declaration: 'استلمنا مخلفات البناء البلاستيكية من مواقع البناء والهدم، تشمل أنابيب PVC وعوازل.',
    processing_details_template: 'تم فصل أنابيب PVC وطحنها لإعادة استخدامها في تصنيع أنابيب ري ومواد بناء.',
    closing_declaration: 'أتممنا تدوير مخلفات البناء البلاستيكية وتحويلها لمواد صالحة للبناء مجدداً.',
    tags: ['بناء', 'PVC', 'أنابيب'],
  },
  {
    id: 'plastic-009',
    name: 'تدوير البلاستيك الزراعي',
    description: 'لأغطية الصوب والري بالتنقيط',
    waste_category: 'non_hazardous',
    waste_types: ['plastic'],
    opening_declaration: 'تم استلام المخلفات البلاستيكية الزراعية من المزارع والصوب الزراعية.',
    processing_details_template: 'تم غسل الأغطية البلاستيكية من التربة والمبيدات، ثم تدويرها لإنتاج أفلام زراعية جديدة.',
    closing_declaration: 'تمت معالجة البلاستيك الزراعي بأمان بيئي وتحويله لمنتجات زراعية مستدامة.',
    tags: ['زراعي', 'صوب', 'ري'],
  },
  {
    id: 'plastic-010',
    name: 'تدوير ألعاب الأطفال البلاستيكية',
    description: 'للألعاب المستعملة والتالفة',
    waste_category: 'non_hazardous',
    waste_types: ['plastic'],
    opening_declaration: 'نقر باستلام ألعاب الأطفال البلاستيكية المستعملة للتدوير الآمن.',
    processing_details_template: 'تم فحص الألعاب وإزالة أي مكونات خطرة، ثم طحن البلاستيك وإعادة تدويره لمنتجات آمنة.',
    closing_declaration: 'تم تدوير الألعاب البلاستيكية بأمان تام مع الحفاظ على معايير السلامة للأطفال.',
    tags: ['ألعاب', 'أطفال', 'آمن'],
  },
];

// ============================================
// قوالب الورق والكرتون (10 قوالب)
// ============================================
const paperTemplates: RecyclingReportTemplate[] = [
  {
    id: 'paper-001',
    name: 'تقرير تدوير الورق - قياسي',
    description: 'قالب عام لإعادة تدوير الورق والكرتون',
    waste_category: 'non_hazardous',
    waste_types: ['paper'],
    opening_declaration: 'نقر نحن جهة إعادة التدوير باستلام شحنة الورق والكرتون المستعمل، وتم فحصها للتأكد من جودتها.',
    processing_details_template: 'تم فرز الورق حسب النوع والجودة، ثم نقعه وإزالة الحبر ومعالجته لإنتاج لب ورقي نظيف.',
    closing_declaration: 'أتممنا تدوير الورق بنجاح وتحويله إلى لب ورقي جاهز لتصنيع ورق جديد.',
    tags: ['ورق', 'كرتون', 'قياسي'],
  },
  {
    id: 'paper-002',
    name: 'تدوير الورق المكتبي',
    description: 'للأوراق المطبوعة والمستندات',
    waste_category: 'non_hazardous',
    waste_types: ['paper'],
    opening_declaration: 'استلمنا أوراق المكاتب والمستندات المتقادمة للتدوير، مع ضمان إتلاف المعلومات السرية.',
    processing_details_template: 'تم تمزيق المستندات بشكل آمن ثم معالجتها كيميائياً لإزالة الحبر وإنتاج لب ورقي عالي الجودة.',
    closing_declaration: 'تم تدوير الورق المكتبي بسرية تامة وتحويله لمواد خام صالحة لصناعة الورق.',
    tags: ['مكتبي', 'مستندات', 'سري'],
  },
  {
    id: 'paper-003',
    name: 'تدوير الكرتون المموج',
    description: 'لصناديق الشحن والتغليف',
    waste_category: 'non_hazardous',
    waste_types: ['paper'],
    opening_declaration: 'نقر باستلام صناديق الكرتون المموج المستعملة من المستودعات والشركات.',
    processing_details_template: 'تم ضغط الكرتون وتفكيكه ثم نقعه لإنتاج لب كرتون يستخدم في صناعة صناديق جديدة.',
    closing_declaration: 'أكملنا تدوير الكرتون المموج بكفاءة عالية للاستخدام في صناعة التغليف.',
    tags: ['كرتون', 'مموج', 'صناديق'],
  },
  {
    id: 'paper-004',
    name: 'تدوير الصحف والمجلات',
    description: 'للمطبوعات الدورية المستعملة',
    waste_category: 'non_hazardous',
    waste_types: ['paper'],
    opening_declaration: 'تم استلام الصحف والمجلات المستعملة المجمعة من نقاط التجميع.',
    processing_details_template: 'تم فصل الصحف عن المجلات اللامعة ومعالجة كل نوع بتقنية مناسبة لإزالة الأحبار.',
    closing_declaration: 'تم تحويل المطبوعات الورقية إلى لب ورقي نظيف للتصنيع.',
    tags: ['صحف', 'مجلات', 'مطبوعات'],
  },
  {
    id: 'paper-005',
    name: 'تدوير ورق التغليف',
    description: 'لأوراق التغليف والهدايا',
    waste_category: 'non_hazardous',
    waste_types: ['paper'],
    opening_declaration: 'استلمنا أوراق التغليف المستعملة من المحلات ومراكز التسوق.',
    processing_details_template: 'تم فصل الأوراق الملونة والمطلية ومعالجتها لإنتاج ورق معاد تدويره للتغليف.',
    closing_declaration: 'تم إعادة تدوير أوراق التغليف بنجاح للاستخدام مجدداً.',
    tags: ['تغليف', 'هدايا', 'تجاري'],
  },
  {
    id: 'paper-006',
    name: 'تدوير الكتب والكراسات',
    description: 'للكتب المدرسية والدفاتر',
    waste_category: 'non_hazardous',
    waste_types: ['paper'],
    opening_declaration: 'نقر باستلام الكتب والكراسات المستعملة للتدوير بعد انتهاء صلاحيتها.',
    processing_details_template: 'تم فصل الأغلفة والمواد غير الورقية، ثم معالجة الصفحات لإنتاج لب ورقي للكراسات الجديدة.',
    closing_declaration: 'تم تدوير المواد التعليمية الورقية وتحويلها لمنتجات مفيدة.',
    tags: ['كتب', 'مدرسي', 'تعليمي'],
  },
  {
    id: 'paper-007',
    name: 'تدوير المناديل الورقية النظيفة',
    description: 'لفائض المناديل غير المستخدمة',
    waste_category: 'non_hazardous',
    waste_types: ['paper'],
    opening_declaration: 'استلمنا فائض المناديل الورقية النظيفة من المصانع والفنادق.',
    processing_details_template: 'تم نقع المناديل وتحويلها إلى لب ورقي للاستخدام في صناعة منتجات ورقية جديدة.',
    closing_declaration: 'تم استرداد المناديل الورقية وتحويلها لمواد خام مفيدة.',
    tags: ['مناديل', 'نظيف', 'فنادق'],
  },
  {
    id: 'paper-008',
    name: 'تدوير ورق الطباعة',
    description: 'لمخلفات المطابع ودور النشر',
    waste_category: 'non_hazardous',
    waste_types: ['paper'],
    opening_declaration: 'تم استلام مخلفات ورق الطباعة من المطابع (قص، أخطاء طباعة، تجارب).',
    processing_details_template: 'تم فرز الورق حسب الجودة وإزالة الأحبار بتقنيات متقدمة لإنتاج ورق أبيض نظيف.',
    closing_declaration: 'أتممنا تدوير مخلفات المطابع وتحويلها لورق عالي الجودة.',
    tags: ['طباعة', 'مطابع', 'نشر'],
  },
  {
    id: 'paper-009',
    name: 'تدوير الورق المقوى',
    description: 'للتغليف الصلب والعلب',
    waste_category: 'non_hazardous',
    waste_types: ['paper'],
    opening_declaration: 'نقر باستلام الورق المقوى المستخدم في التغليف والعلب.',
    processing_details_template: 'تم إزالة الطلاءات والمواد اللاصقة ثم معالجة الورق لإنتاج كرتون مقوى معاد تدويره.',
    closing_declaration: 'تم تحويل الورق المقوى إلى مادة خام للتغليف الصناعي.',
    tags: ['مقوى', 'علب', 'صلب'],
  },
  {
    id: 'paper-010',
    name: 'تدوير الورق السري',
    description: 'للمستندات السرية مع شهادة إتلاف',
    waste_category: 'non_hazardous',
    waste_types: ['paper'],
    opening_declaration: 'تم استلام المستندات السرية للإتلاف الآمن والتدوير، مع توفير شهادة إتلاف.',
    processing_details_template: 'تم تمزيق المستندات بآلات تقطيع متقاطعة ثم نقعها فوراً لضمان عدم إمكانية الاسترداد.',
    closing_declaration: 'نشهد بإتلاف المستندات السرية بشكل نهائي وتدويرها بأمان تام.',
    tags: ['سري', 'إتلاف', 'شهادة'],
  },
];

// ============================================
// قوالب المعادن (10 قوالب)
// ============================================
const metalTemplates: RecyclingReportTemplate[] = [
  {
    id: 'metal-001',
    name: 'تقرير تدوير المعادن - قياسي',
    description: 'قالب عام لإعادة تدوير الخردة المعدنية',
    waste_category: 'non_hazardous',
    waste_types: ['metal'],
    opening_declaration: 'نقر باستلام شحنة الخردة المعدنية الموضحة أدناه وتم وزنها وفحص محتوياتها.',
    processing_details_template: 'تم فرز المعادن حسب النوع (حديد، ألومنيوم، نحاس) ثم صهرها وتشكيلها إلى سبائك.',
    closing_declaration: 'أتممنا تدوير المعادن وتحويلها إلى سبائك معدنية جاهزة للتصنيع.',
    tags: ['معادن', 'خردة', 'قياسي'],
  },
  {
    id: 'metal-002',
    name: 'تدوير الألومنيوم',
    description: 'لعلب المشروبات والألواح',
    waste_category: 'non_hazardous',
    waste_types: ['metal'],
    opening_declaration: 'تم استلام مخلفات الألومنيوم (علب، ألواح، قطع) للتدوير.',
    processing_details_template: 'تم ضغط الألومنيوم وصهره في أفران متخصصة لإنتاج سبائك ألومنيوم نقية.',
    closing_declaration: 'تم إعادة تدوير الألومنيوم بكفاءة 95% وإنتاج سبائك عالية الجودة.',
    tags: ['ألومنيوم', 'علب', 'مشروبات'],
  },
  {
    id: 'metal-003',
    name: 'تدوير النحاس والأسلاك',
    description: 'للكابلات والأسلاك الكهربائية',
    waste_category: 'non_hazardous',
    waste_types: ['metal'],
    opening_declaration: 'نقر باستلام مخلفات النحاس والأسلاك الكهربائية للتدوير.',
    processing_details_template: 'تم تقشير العزل وفصل النحاس ثم صهره لإنتاج قضبان نحاسية نقية.',
    closing_declaration: 'تم استخلاص النحاس النقي وتحويله لمادة خام للصناعات الكهربائية.',
    tags: ['نحاس', 'أسلاك', 'كهربائي'],
  },
  {
    id: 'metal-004',
    name: 'تدوير الحديد والصلب',
    description: 'للهياكل والقطع الحديدية',
    waste_category: 'non_hazardous',
    waste_types: ['metal'],
    opening_declaration: 'استلمنا مخلفات الحديد والصلب من مواقع البناء والمصانع.',
    processing_details_template: 'تم قطع الحديد وضغطه ثم صهره في أفران القوس الكهربائي لإنتاج صلب معاد تدويره.',
    closing_declaration: 'أكملنا تدوير الحديد وتحويله إلى قضبان صلب جاهزة للبناء والتصنيع.',
    tags: ['حديد', 'صلب', 'بناء'],
  },
  {
    id: 'metal-005',
    name: 'تدوير علب الصفيح',
    description: 'لعلب الطعام المعدنية',
    waste_category: 'non_hazardous',
    waste_types: ['metal'],
    opening_declaration: 'تم استلام علب الصفيح الفارغة المجمعة من المصانع والمستهلكين.',
    processing_details_template: 'تم غسل العلب وإزالة الملصقات ثم صهرها لفصل الصفيح عن الحديد.',
    closing_declaration: 'تم استرداد الصفيح والحديد من العلب وتحويلهما لمواد خام صالحة.',
    tags: ['صفيح', 'علب', 'طعام'],
  },
  {
    id: 'metal-006',
    name: 'تدوير سكراب السيارات',
    description: 'لهياكل السيارات التالفة',
    waste_category: 'non_hazardous',
    waste_types: ['metal'],
    opening_declaration: 'نقر باستلام هياكل السيارات التالفة للتفكيك والتدوير.',
    processing_details_template: 'تم تفريغ السوائل وإزالة المواد الخطرة، ثم ضغط الهياكل وتقطيعها للصهر.',
    closing_declaration: 'تم تدوير هياكل السيارات بأمان بيئي وتحويلها لصلب معاد تدويره.',
    tags: ['سيارات', 'هياكل', 'سكراب'],
  },
  {
    id: 'metal-007',
    name: 'تدوير برادة المعادن',
    description: 'لمخلفات الورش والتصنيع',
    waste_category: 'non_hazardous',
    waste_types: ['metal'],
    opening_declaration: 'استلمنا برادة ورقائق المعادن من ورش التصنيع والخراطة.',
    processing_details_template: 'تم ضغط البرادة وإزالة الزيوت ثم صهرها لإنتاج سبائك معدنية.',
    closing_declaration: 'تم تحويل مخلفات التصنيع المعدنية إلى مواد خام قابلة لإعادة الاستخدام.',
    tags: ['برادة', 'ورش', 'تصنيع'],
  },
  {
    id: 'metal-008',
    name: 'تدوير المعادن الثمينة',
    description: 'للذهب والفضة من الإلكترونيات',
    waste_category: 'non_hazardous',
    waste_types: ['metal'],
    opening_declaration: 'تم استلام المكونات الإلكترونية المحتوية على معادن ثمينة للاستخلاص.',
    processing_details_template: 'تم استخدام تقنيات كيميائية وحرارية لاستخلاص الذهب والفضة والبلاتين.',
    closing_declaration: 'تم استرداد المعادن الثمينة بنقاوة عالية وتسليمها للتنقية النهائية.',
    tags: ['ذهب', 'فضة', 'إلكترونيات'],
  },
  {
    id: 'metal-009',
    name: 'تدوير الزنك والرصاص',
    description: 'للبطاريات والسبائك',
    waste_category: 'non_hazardous',
    waste_types: ['metal'],
    opening_declaration: 'نقر باستلام مخلفات الزنك والرصاص للتدوير الآمن.',
    processing_details_template: 'تم فصل المعادن وصهرها في بيئة محكمة لمنع التلوث وإنتاج سبائك نقية.',
    closing_declaration: 'تم تدوير الزنك والرصاص بأمان بيئي وفق المعايير الصحية.',
    tags: ['زنك', 'رصاص', 'بطاريات'],
  },
  {
    id: 'metal-010',
    name: 'تدوير الستانلس ستيل',
    description: 'للأواني والمعدات الغذائية',
    waste_category: 'non_hazardous',
    waste_types: ['metal'],
    opening_declaration: 'تم استلام مخلفات الستانلس ستيل من المطاعم والمصانع الغذائية.',
    processing_details_template: 'تم تنظيف وفرز الستانلس ستيل ثم صهره لإنتاج سبائك مقاومة للصدأ.',
    closing_declaration: 'أكملنا تدوير الستانلس ستيل وتحويله لمادة خام عالية الجودة.',
    tags: ['ستانلس', 'غذائي', 'أواني'],
  },
];

// ============================================
// قوالب الزجاج (10 قوالب)
// ============================================
const glassTemplates: RecyclingReportTemplate[] = [
  {
    id: 'glass-001',
    name: 'تقرير تدوير الزجاج - قياسي',
    description: 'قالب عام لإعادة تدوير الزجاج',
    waste_category: 'non_hazardous',
    waste_types: ['glass'],
    opening_declaration: 'نقر باستلام شحنة الزجاج المكسور والعبوات الزجاجية الفارغة للتدوير.',
    processing_details_template: 'تم فرز الزجاج حسب اللون وإزالة الشوائب ثم طحنه وصهره لإنتاج زجاج جديد.',
    closing_declaration: 'أتممنا تدوير الزجاج بكفاءة 100% وتحويله لمواد خام للتصنيع.',
    tags: ['زجاج', 'عبوات', 'قياسي'],
  },
  {
    id: 'glass-002',
    name: 'تدوير زجاجات المشروبات',
    description: 'للزجاجات الفارغة بجميع الألوان',
    waste_category: 'non_hazardous',
    waste_types: ['glass'],
    opening_declaration: 'استلمنا زجاجات المشروبات الفارغة المجمعة من نقاط التجميع.',
    processing_details_template: 'تم غسل الزجاجات وفرزها حسب اللون (شفاف، أخضر، بني) ثم طحنها وصهرها.',
    closing_declaration: 'تم تحويل زجاجات المشروبات إلى كسر زجاجي نظيف للتصنيع.',
    tags: ['زجاجات', 'مشروبات', 'ألوان'],
  },
  {
    id: 'glass-003',
    name: 'تدوير الزجاج المسطح',
    description: 'للنوافذ والمرايا',
    waste_category: 'non_hazardous',
    waste_types: ['glass'],
    opening_declaration: 'تم استلام ألواح الزجاج المسطح من مواقع البناء والتجديد.',
    processing_details_template: 'تم إزالة الإطارات والمواد اللاصقة ثم طحن الزجاج لاستخدامه في صناعة الزجاج المسطح.',
    closing_declaration: 'أكملنا تدوير الزجاج المسطح وتحويله لمادة خام للتصنيع.',
    tags: ['مسطح', 'نوافذ', 'بناء'],
  },
  {
    id: 'glass-004',
    name: 'تدوير الزجاج الطبي',
    description: 'للقوارير والأمبولات الفارغة',
    waste_category: 'non_hazardous',
    waste_types: ['glass'],
    opening_declaration: 'نقر باستلام الزجاج الطبي الفارغ بعد التأكد من خلوه من المواد الخطرة.',
    processing_details_template: 'تم تعقيم الزجاج الطبي ثم طحنه واستخدامه في صناعة زجاج غير طبي.',
    closing_declaration: 'تم تدوير الزجاج الطبي بأمان بعد التعقيم الكامل.',
    tags: ['طبي', 'قوارير', 'تعقيم'],
  },
  {
    id: 'glass-005',
    name: 'تدوير الزجاج الملون',
    description: 'للديكورات والفنون',
    waste_category: 'non_hazardous',
    waste_types: ['glass'],
    opening_declaration: 'استلمنا مخلفات الزجاج الملون من ورش الفن والديكور.',
    processing_details_template: 'تم فرز الألوان وطحن الزجاج لإنتاج كسر زجاجي ملون للصناعات الفنية.',
    closing_declaration: 'تم تحويل الزجاج الملون لمواد خام للحرف اليدوية والفنون.',
    tags: ['ملون', 'ديكور', 'فن'],
  },
  {
    id: 'glass-006',
    name: 'تدوير زجاج السيارات',
    description: 'للزجاج الأمامي والجانبي',
    waste_category: 'non_hazardous',
    waste_types: ['glass'],
    opening_declaration: 'تم استلام زجاج السيارات التالف من ورش التصليح.',
    processing_details_template: 'تم فصل طبقة البلاستيك (PVB) من الزجاج المصفح ثم طحن الزجاج للتدوير.',
    closing_declaration: 'أتممنا فصل وتدوير زجاج السيارات بنجاح.',
    tags: ['سيارات', 'مصفح', 'PVB'],
  },
  {
    id: 'glass-007',
    name: 'تدوير الألياف الزجاجية',
    description: 'للعزل والتكسية',
    waste_category: 'non_hazardous',
    waste_types: ['glass'],
    opening_declaration: 'نقر باستلام مخلفات الألياف الزجاجية من مواقع البناء.',
    processing_details_template: 'تم طحن الألياف الزجاجية وإعادة صهرها لإنتاج ألياف جديدة أو حشو عازل.',
    closing_declaration: 'تم تدوير الألياف الزجاجية وتحويلها لمواد عزل جديدة.',
    tags: ['ألياف', 'عزل', 'بناء'],
  },
  {
    id: 'glass-008',
    name: 'تدوير زجاج المختبرات',
    description: 'للأواني والأنابيب المختبرية',
    waste_category: 'non_hazardous',
    waste_types: ['glass'],
    opening_declaration: 'استلمنا الأواني الزجاجية المختبرية بعد تنظيفها وتعقيمها.',
    processing_details_template: 'تم فحص الزجاج المختبري للتأكد من خلوه من التلوث ثم طحنه للتدوير.',
    closing_declaration: 'تم تدوير الزجاج المختبري بأمان وتحويله لكسر زجاجي نظيف.',
    tags: ['مختبر', 'أواني', 'علمي'],
  },
  {
    id: 'glass-009',
    name: 'تدوير مرايا الزجاج',
    description: 'للمرايا المكسورة والقديمة',
    waste_category: 'non_hazardous',
    waste_types: ['glass'],
    opening_declaration: 'تم استلام المرايا المستعملة والمكسورة للتدوير.',
    processing_details_template: 'تم إزالة طلاء الفضة والمواد الخلفية ثم طحن الزجاج للتدوير.',
    closing_declaration: 'أكملنا تدوير المرايا بعد فصل المواد المعدنية والكيميائية.',
    tags: ['مرايا', 'فضة', 'طلاء'],
  },
  {
    id: 'glass-010',
    name: 'تدوير الزجاج البصري',
    description: 'للعدسات والنظارات',
    waste_category: 'non_hazardous',
    waste_types: ['glass'],
    opening_declaration: 'نقر باستلام الزجاج البصري المستعمل (عدسات، نظارات قديمة).',
    processing_details_template: 'تم فصل الإطارات والطلاءات ثم طحن العدسات الزجاجية للتدوير.',
    closing_declaration: 'تم تدوير الزجاج البصري وتحويله لمواد خام للصناعات الزجاجية.',
    tags: ['بصري', 'عدسات', 'نظارات'],
  },
];

// ============================================
// قوالب الإلكترونيات (10 قوالب) - خطرة
// ============================================
const electronicTemplates: RecyclingReportTemplate[] = [
  {
    id: 'electronic-001',
    name: 'تقرير تدوير الإلكترونيات - قياسي',
    description: 'قالب لإعادة تدوير المخلفات الإلكترونية',
    waste_category: 'hazardous',
    waste_types: ['electronic'],
    opening_declaration: 'نقر نحن جهة إعادة التدوير المعتمدة للمخلفات الإلكترونية باستلام الشحنة الموضحة أدناه، وتم التعامل معها وفق بروتوكولات السلامة.',
    processing_details_template: 'تم تفكيك الأجهزة يدوياً وفصل المكونات (معادن، بلاستيك، لوحات إلكترونية) ومعالجة كل مكون بالتقنية المناسبة.',
    closing_declaration: 'نؤكد إتمام تدوير المخلفات الإلكترونية بأمان بيئي واستخلاص المواد القيمة مع التخلص الآمن من المواد الخطرة.',
    tags: ['إلكترونيات', 'أجهزة', 'خطر'],
  },
  {
    id: 'electronic-002',
    name: 'تدوير الهواتف المحمولة',
    description: 'للجوالات والأجهزة اللوحية',
    waste_category: 'hazardous',
    waste_types: ['electronic'],
    opening_declaration: 'تم استلام الهواتف المحمولة والأجهزة اللوحية المستعملة للتدوير الآمن.',
    processing_details_template: 'تم مسح البيانات بشكل نهائي ثم تفكيك الأجهزة واستخلاص البطاريات والمعادن الثمينة واللوحات.',
    closing_declaration: 'أكملنا تدوير الأجهزة المحمولة مع ضمان إتلاف البيانات واسترداد المواد القيمة.',
    tags: ['هواتف', 'لوحية', 'بيانات'],
  },
  {
    id: 'electronic-003',
    name: 'تدوير أجهزة الكمبيوتر',
    description: 'للحواسيب المكتبية والمحمولة',
    waste_category: 'hazardous',
    waste_types: ['electronic'],
    opening_declaration: 'نقر باستلام أجهزة الكمبيوتر المستعملة للتدوير مع شهادة إتلاف البيانات.',
    processing_details_template: 'تم تدمير وسائط التخزين بشكل نهائي ثم تفكيك الأجهزة واستخلاص المعادن والمكونات القابلة للتدوير.',
    closing_declaration: 'تم تدوير الحواسيب بأمان تام مع تقديم شهادة إتلاف البيانات للعميل.',
    tags: ['كمبيوتر', 'حاسوب', 'بيانات'],
  },
  {
    id: 'electronic-004',
    name: 'تدوير الشاشات والتلفزيونات',
    description: 'للشاشات LCD وCRT',
    waste_category: 'hazardous',
    waste_types: ['electronic'],
    opening_declaration: 'استلمنا الشاشات والتلفزيونات المستعملة للتدوير الآمن.',
    processing_details_template: 'تم فصل اللوحات الإلكترونية والزجاج والبلاستيك، مع التعامل الخاص مع شاشات CRT المحتوية على الرصاص.',
    closing_declaration: 'أتممنا تدوير الشاشات بأمان مع التخلص الآمن من المواد السامة.',
    tags: ['شاشات', 'تلفزيون', 'LCD'],
  },
  {
    id: 'electronic-005',
    name: 'تدوير الطابعات والماسحات',
    description: 'للأجهزة المكتبية',
    waste_category: 'hazardous',
    waste_types: ['electronic'],
    opening_declaration: 'تم استلام الطابعات والماسحات الضوئية المستعملة للتفكيك والتدوير.',
    processing_details_template: 'تم إفراغ خراطيش الحبر وفصل المكونات الإلكترونية والمعدنية والبلاستيكية.',
    closing_declaration: 'تم تدوير الأجهزة المكتبية واستخلاص جميع المكونات القابلة لإعادة الاستخدام.',
    tags: ['طابعات', 'ماسحات', 'مكتبي'],
  },
  {
    id: 'electronic-006',
    name: 'تدوير الأجهزة المنزلية الصغيرة',
    description: 'للخلاطات والمكانس الكهربائية',
    waste_category: 'hazardous',
    waste_types: ['electronic'],
    opening_declaration: 'نقر باستلام الأجهزة المنزلية الكهربائية الصغيرة للتدوير.',
    processing_details_template: 'تم تفكيك الأجهزة وفصل المحركات والأسلاك والبلاستيك للتدوير كل على حدة.',
    closing_declaration: 'أكملنا تدوير الأجهزة المنزلية الصغيرة واسترداد المواد المعدنية.',
    tags: ['منزلي', 'كهربائي', 'صغير'],
  },
  {
    id: 'electronic-007',
    name: 'تدوير خوادم مراكز البيانات',
    description: 'للخوادم ومعدات الشبكات',
    waste_category: 'hazardous',
    waste_types: ['electronic'],
    opening_declaration: 'تم استلام خوادم ومعدات مراكز البيانات مع ضمان إتلاف البيانات بمعايير عسكرية.',
    processing_details_template: 'تم تدمير وسائط التخزين بتقنية الطحن ثم تفكيك الخوادم واستخلاص المعادن الثمينة والمكونات.',
    closing_declaration: 'نشهد بإتلاف جميع البيانات وفق معايير DOD وتدوير المعدات بأمان.',
    tags: ['خوادم', 'بيانات', 'شبكات'],
  },
  {
    id: 'electronic-008',
    name: 'تدوير ألواح الطاقة الشمسية',
    description: 'للألواح الشمسية المستهلكة',
    waste_category: 'hazardous',
    waste_types: ['electronic'],
    opening_declaration: 'نقر باستلام ألواح الطاقة الشمسية المستهلكة للتدوير المتخصص.',
    processing_details_template: 'تم فصل الزجاج والإطار الألومنيوم والخلايا السيليكونية، مع التعامل الآمن مع المواد الكيميائية.',
    closing_declaration: 'تم تدوير الألواح الشمسية واستخلاص السيليكون والمعادن الثمينة.',
    tags: ['شمسي', 'طاقة', 'سيليكون'],
  },
  {
    id: 'electronic-009',
    name: 'تدوير معدات الاتصالات',
    description: 'لأجهزة الراوتر والسنترالات',
    waste_category: 'hazardous',
    waste_types: ['electronic'],
    opening_declaration: 'استلمنا معدات الاتصالات والشبكات للتدوير الآمن.',
    processing_details_template: 'تم مسح إعدادات الأجهزة وتفكيكها واستخلاص المكونات الإلكترونية والمعدنية.',
    closing_declaration: 'أتممنا تدوير معدات الاتصالات مع ضمان أمن المعلومات.',
    tags: ['اتصالات', 'شبكات', 'راوتر'],
  },
  {
    id: 'electronic-010',
    name: 'تدوير الأجهزة الطبية الإلكترونية',
    description: 'للمعدات الطبية الإلكترونية',
    waste_category: 'hazardous',
    waste_types: ['electronic'],
    opening_declaration: 'تم استلام الأجهزة الطبية الإلكترونية بعد تعقيمها للتدوير.',
    processing_details_template: 'تم فحص الأجهزة للتأكد من التعقيم ثم تفكيكها واستخلاص المكونات مع التخلص الآمن من أي مواد ملوثة.',
    closing_declaration: 'نؤكد تدوير الأجهزة الطبية بأمان صحي وبيئي تام.',
    tags: ['طبي', 'إلكتروني', 'معدات'],
  },
];

// ============================================
// قوالب المخلفات العضوية (10 قوالب)
// ============================================
const organicTemplates: RecyclingReportTemplate[] = [
  {
    id: 'organic-001',
    name: 'تقرير تدوير العضويات - قياسي',
    description: 'قالب عام للمخلفات العضوية',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'نقر باستلام شحنة المخلفات العضوية الموضحة أدناه للمعالجة والتحويل.',
    processing_details_template: 'تم معالجة المخلفات العضوية بالتخمير الهوائي لإنتاج سماد عضوي عالي الجودة.',
    closing_declaration: 'أتممنا تحويل المخلفات العضوية إلى سماد عضوي صالح للزراعة.',
    tags: ['عضوي', 'سماد', 'قياسي'],
  },
  {
    id: 'organic-002',
    name: 'تحويل بقايا الطعام',
    description: 'لمخلفات المطاعم والفنادق',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'استلمنا بقايا الطعام من المطاعم والفنادق للتحويل إلى سماد.',
    processing_details_template: 'تم فرز بقايا الطعام وإزالة الشوائب ثم تخميرها في مفاعلات حيوية لإنتاج سماد عضوي.',
    closing_declaration: 'تم تحويل بقايا الطعام إلى سماد عضوي غني بالمغذيات.',
    tags: ['طعام', 'مطاعم', 'فنادق'],
  },
  {
    id: 'organic-003',
    name: 'تدوير المخلفات الزراعية',
    description: 'لبقايا المحاصيل والأغصان',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'تم استلام المخلفات الزراعية (قش، أغصان، أوراق) للتحويل.',
    processing_details_template: 'تم تقطيع المخلفات الزراعية وخلطها بمواد غنية بالنيتروجين للتسميد السريع.',
    closing_declaration: 'أكملنا تحويل المخلفات الزراعية إلى سماد ومحسنات تربة.',
    tags: ['زراعي', 'محاصيل', 'تربة'],
  },
  {
    id: 'organic-004',
    name: 'تحويل مخلفات الحدائق',
    description: 'للعشب والأوراق المتساقطة',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'نقر باستلام مخلفات الحدائق والمسطحات الخضراء للتحويل.',
    processing_details_template: 'تم تجميع الأوراق والعشب وتخميرها لإنتاج سماد أخضر عالي الجودة.',
    closing_declaration: 'تم تحويل مخلفات الحدائق إلى سماد مناسب للمسطحات الخضراء.',
    tags: ['حدائق', 'عشب', 'أوراق'],
  },
  {
    id: 'organic-005',
    name: 'إنتاج الغاز الحيوي',
    description: 'تحويل العضويات إلى طاقة',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'استلمنا المخلفات العضوية لتحويلها إلى غاز حيوي (بيوغاز).',
    processing_details_template: 'تم معالجة المخلفات في هاضم لاهوائي لإنتاج غاز الميثان واستخدامه في توليد الطاقة.',
    closing_declaration: 'تم تحويل المخلفات العضوية إلى طاقة نظيفة وسماد سائل.',
    tags: ['بيوغاز', 'طاقة', 'ميثان'],
  },
  {
    id: 'organic-006',
    name: 'تدوير مخلفات المطابخ المركزية',
    description: 'للمستشفيات والمدارس',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'تم استلام مخلفات المطابخ المركزية للمعالجة الآمنة.',
    processing_details_template: 'تم فصل المواد غير العضوية وتعقيم المخلفات ثم تخميرها لإنتاج سماد.',
    closing_declaration: 'أتممنا معالجة مخلفات المطابخ بأمان صحي وتحويلها لسماد.',
    tags: ['مطابخ', 'مؤسسات', 'صحي'],
  },
  {
    id: 'organic-007',
    name: 'تحويل مخلفات الأسواق',
    description: 'للفواكه والخضروات التالفة',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'نقر باستلام مخلفات أسواق الخضار والفاكهة للتحويل.',
    processing_details_template: 'تم فرز المخلفات وإزالة العبوات ثم تخميرها سريعاً لمنع الروائح.',
    closing_declaration: 'تم تحويل مخلفات الأسواق إلى سماد عضوي للمزارع.',
    tags: ['أسواق', 'خضار', 'فاكهة'],
  },
  {
    id: 'organic-008',
    name: 'تدوير مخلفات المخابز',
    description: 'للخبز والمعجنات المرتجعة',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'استلمنا مخلفات المخابز والمعجنات للتحويل أو استخدامها كعلف.',
    processing_details_template: 'تم فرز المخلفات الصالحة للعلف وتجفيفها، وتخمير الباقي لإنتاج سماد.',
    closing_declaration: 'تم تحويل مخلفات المخابز إلى علف حيواني وسماد عضوي.',
    tags: ['مخابز', 'خبز', 'علف'],
  },
  {
    id: 'organic-009',
    name: 'تدوير القهوة المستخدمة',
    description: 'لتفل القهوة من المقاهي',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'تم استلام تفل القهوة المستخدم من المقاهي والمطاعم.',
    processing_details_template: 'تم تجفيف تفل القهوة واستخدامه كمحسن تربة أو في إنتاج الوقود الحيوي.',
    closing_declaration: 'أكملنا تحويل تفل القهوة إلى منتجات مفيدة للزراعة والطاقة.',
    tags: ['قهوة', 'مقاهي', 'تربة'],
  },
  {
    id: 'organic-010',
    name: 'تحويل مخلفات تقليم الأشجار',
    description: 'للأغصان والجذوع',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'نقر باستلام مخلفات تقليم الأشجار من البلديات والحدائق.',
    processing_details_template: 'تم تقطيع الأغصان وتحويلها إلى نشارة للتغطية أو وقود حيوي.',
    closing_declaration: 'تم تحويل مخلفات التقليم إلى نشارة خشب ووقود حيوي.',
    tags: ['أشجار', 'تقليم', 'نشارة'],
  },
];

// ============================================
// قوالب المخلفات الكيميائية (10 قوالب) - خطرة
// ============================================
const chemicalTemplates: RecyclingReportTemplate[] = [
  {
    id: 'chemical-001',
    name: 'تقرير المخلفات الكيميائية - قياسي',
    description: 'قالب للتعامل مع المخلفات الكيميائية الخطرة',
    waste_category: 'hazardous',
    waste_types: ['chemical'],
    opening_declaration: 'نقر نحن جهة المعالجة المرخصة للمخلفات الكيميائية الخطرة باستلام الشحنة الموضحة أدناه، وتم التعامل معها وفق بروتوكولات السلامة الكيميائية.',
    processing_details_template: 'تم معالجة المخلفات الكيميائية بالتقنيات المعتمدة (معادلة، أكسدة، اختزال) والتخلص منها بطريقة آمنة.',
    closing_declaration: 'نؤكد أن المخلفات الكيميائية الخطرة قد تم التعامل معها والتخلص منها بشكل نهائي وآمن، بما يتوافق مع اللوائح البيئية.',
    tags: ['كيميائي', 'خطر', 'معالجة'],
  },
  {
    id: 'chemical-002',
    name: 'معالجة زيوت السيارات المستعملة',
    description: 'للزيوت الهيدروليكية وزيوت المحركات',
    waste_category: 'hazardous',
    waste_types: ['chemical'],
    opening_declaration: 'تم استلام الزيوت المستعملة من ورش السيارات ومحطات الخدمة.',
    processing_details_template: 'تم ترشيح الزيوت وإزالة الشوائب ثم إعادة تكريرها لإنتاج زيوت أساسية معاد تدويرها.',
    closing_declaration: 'أتممنا تكرير الزيوت المستعملة وتحويلها لزيوت قابلة للاستخدام مجدداً.',
    tags: ['زيوت', 'سيارات', 'تكرير'],
  },
  {
    id: 'chemical-003',
    name: 'معالجة المذيبات الصناعية',
    description: 'للمذيبات والمنظفات الكيميائية',
    waste_category: 'hazardous',
    waste_types: ['chemical'],
    opening_declaration: 'نقر باستلام المذيبات الصناعية المستعملة للمعالجة والاستخلاص.',
    processing_details_template: 'تم تقطير المذيبات واستخلاص المواد الصالحة للاستخدام والتخلص الآمن من البقايا.',
    closing_declaration: 'تم استخلاص المذيبات القابلة للاستخدام والتخلص الآمن من النفايات.',
    tags: ['مذيبات', 'صناعي', 'تقطير'],
  },
  {
    id: 'chemical-004',
    name: 'معالجة الأحماض والقلويات',
    description: 'للمحاليل الكيميائية المركزة',
    waste_category: 'hazardous',
    waste_types: ['chemical'],
    opening_declaration: 'استلمنا المحاليل الحمضية والقلوية المستعملة للمعادلة الآمنة.',
    processing_details_template: 'تم معادلة الأحماض والقلويات كيميائياً وترسيب الملوثات الثقيلة للتخلص الآمن.',
    closing_declaration: 'تم معادلة المحاليل الكيميائية والتخلص الآمن من الملوثات.',
    tags: ['أحماض', 'قلويات', 'معادلة'],
  },
  {
    id: 'chemical-005',
    name: 'معالجة الدهانات والطلاء',
    description: 'لبقايا الدهان والورنيش',
    waste_category: 'hazardous',
    waste_types: ['chemical'],
    opening_declaration: 'تم استلام بقايا الدهانات والطلاء من ورش الدهان والبناء.',
    processing_details_template: 'تم فصل المذيبات عن الدهان واستخلاصها، وتجفيف الدهان المتبقي للتخلص الآمن.',
    closing_declaration: 'أكملنا معالجة بقايا الدهانات واستخلاص المذيبات للاستخدام.',
    tags: ['دهان', 'طلاء', 'مذيبات'],
  },
  {
    id: 'chemical-006',
    name: 'معالجة مخلفات المختبرات',
    description: 'للكيماويات المختبرية',
    waste_category: 'hazardous',
    waste_types: ['chemical'],
    opening_declaration: 'نقر باستلام المخلفات الكيميائية المختبرية للمعالجة المتخصصة.',
    processing_details_template: 'تم تصنيف المخلفات حسب الخطورة ومعالجة كل نوع بالتقنية المناسبة.',
    closing_declaration: 'تم التخلص الآمن من جميع المخلفات الكيميائية المختبرية.',
    tags: ['مختبر', 'كيماويات', 'تصنيف'],
  },
  {
    id: 'chemical-007',
    name: 'معالجة المبيدات الزراعية',
    description: 'للمبيدات والأسمدة الكيميائية منتهية الصلاحية',
    waste_category: 'hazardous',
    waste_types: ['chemical'],
    opening_declaration: 'استلمنا المبيدات والأسمدة منتهية الصلاحية للتخلص الآمن.',
    processing_details_template: 'تم معالجة المبيدات بالحرق الآمن في أفران متخصصة مع معالجة الانبعاثات.',
    closing_declaration: 'تم التخلص الآمن من المبيدات المنتهية مع الحفاظ على البيئة.',
    tags: ['مبيدات', 'زراعي', 'حرق'],
  },
  {
    id: 'chemical-008',
    name: 'معالجة مخلفات التصوير',
    description: 'لمحاليل التحميض والتثبيت',
    waste_category: 'hazardous',
    waste_types: ['chemical'],
    opening_declaration: 'تم استلام مخلفات التصوير الفوتوغرافي (محاليل، أفلام قديمة).',
    processing_details_template: 'تم استخلاص الفضة من محاليل التثبيت ومعادلة الأحماض للتخلص الآمن.',
    closing_declaration: 'تم استرداد الفضة والتخلص الآمن من مخلفات التصوير.',
    tags: ['تصوير', 'فضة', 'أحماض'],
  },
  {
    id: 'chemical-009',
    name: 'معالجة سوائل التبريد',
    description: 'للفريون وغازات التبريد',
    waste_category: 'hazardous',
    waste_types: ['chemical'],
    opening_declaration: 'نقر باستلام سوائل وغازات التبريد المستنفدة للتخلص الآمن.',
    processing_details_template: 'تم استخلاص الفريون وتخزينه بشكل آمن لمنع إطلاقه في الغلاف الجوي.',
    closing_declaration: 'تم احتواء غازات التبريد بأمان لحماية طبقة الأوزون.',
    tags: ['تبريد', 'فريون', 'أوزون'],
  },
  {
    id: 'chemical-010',
    name: 'معالجة مخلفات الصناعات الكيميائية',
    description: 'للمخلفات الصناعية السائلة والصلبة',
    waste_category: 'hazardous',
    waste_types: ['chemical'],
    opening_declaration: 'استلمنا مخلفات المصانع الكيميائية للمعالجة المتخصصة.',
    processing_details_template: 'تم تحليل المخلفات وتطبيق تقنيات المعالجة المناسبة (فيزيائية، كيميائية، حرارية).',
    closing_declaration: 'أتممنا معالجة المخلفات الصناعية الكيميائية وفق أعلى معايير السلامة.',
    tags: ['صناعي', 'مصانع', 'معالجة'],
  },
];

// ============================================
// قوالب المخلفات الطبية (10 قوالب) - خطرة
// ============================================
const medicalTemplates: RecyclingReportTemplate[] = [
  {
    id: 'medical-001',
    name: 'تقرير المخلفات الطبية - قياسي',
    description: 'قالب للتعامل مع المخلفات الطبية الخطرة',
    waste_category: 'medical_hazardous',
    waste_types: ['medical'],
    opening_declaration: 'نقر نحن جهة المعالجة والتخلص من المخلفات الطبية المرخصة باستلام الشحنة الموضحة أدناه من المخلفات الطبية الخطرة، وسيتم التعامل معها وفق بروتوكولات السلامة الحيوية.',
    processing_details_template: 'تم معالجة المخلفات الطبية باستخدام تقنية الأوتوكلاف للتعقيم الحراري تحت ضغط عالٍ لقتل جميع الكائنات الدقيقة.',
    closing_declaration: 'نؤكد أن المخلفات الطبية الخطرة قد تم التعامل معها والتخلص منها بشكل نهائي وآمن، بما يتوافق مع اللوائح الصحية والبيئية.',
    tags: ['طبي', 'خطر', 'أوتوكلاف'],
  },
  {
    id: 'medical-002',
    name: 'معالجة النفايات المعدية',
    description: 'للمخلفات المحتوية على مسببات الأمراض',
    waste_category: 'medical_hazardous',
    waste_types: ['medical'],
    opening_declaration: 'تم استلام النفايات الطبية المعدية في حاويات محكمة الإغلاق.',
    processing_details_template: 'تم تعقيم النفايات المعدية بالأوتوكلاف عند 134°C لمدة 30 دقيقة، ثم تمزيقها والتخلص منها كنفايات عادية.',
    closing_declaration: 'نشهد بإتمام تعقيم والتخلص الآمن من النفايات المعدية.',
    tags: ['معدي', 'تعقيم', 'حرارة'],
  },
  {
    id: 'medical-003',
    name: 'التخلص من الأدوات الحادة',
    description: 'للإبر والمشارط والزجاج المكسور',
    waste_category: 'medical_hazardous',
    waste_types: ['medical'],
    opening_declaration: 'نقر باستلام حاويات الأدوات الحادة المغلقة من المنشآت الصحية.',
    processing_details_template: 'تم تعقيم حاويات الأدوات الحادة ثم صهرها في أفران متخصصة لإذابة المعادن بأمان.',
    closing_declaration: 'تم التخلص الآمن من الأدوات الحادة بعد التعقيم والصهر.',
    tags: ['حاد', 'إبر', 'صهر'],
  },
  {
    id: 'medical-004',
    name: 'معالجة الأدوية منتهية الصلاحية',
    description: 'للأدوية والعقاقير المنتهية',
    waste_category: 'medical_hazardous',
    waste_types: ['medical'],
    opening_declaration: 'استلمنا الأدوية منتهية الصلاحية للتخلص الآمن.',
    processing_details_template: 'تم فرز الأدوية حسب طريقة التخلص المناسبة (حرق، معادلة، تكسير) والتخلص منها بأمان.',
    closing_declaration: 'أتممنا التخلص الآمن من الأدوية منتهية الصلاحية لمنع سوء الاستخدام.',
    tags: ['أدوية', 'منتهية', 'حرق'],
  },
  {
    id: 'medical-005',
    name: 'التخلص من النفايات التشريحية',
    description: 'للأنسجة والأعضاء البشرية',
    waste_category: 'medical_hazardous',
    waste_types: ['medical'],
    opening_declaration: 'تم استلام النفايات التشريحية في حاويات محكمة للتخلص المراعي للكرامة.',
    processing_details_template: 'تم حرق النفايات التشريحية في محرقة طبية متخصصة عند درجة حرارة 1000°C.',
    closing_declaration: 'تم التخلص من النفايات التشريحية بطريقة كريمة وآمنة بيئياً.',
    tags: ['تشريحي', 'حرق', 'كرامة'],
  },
  {
    id: 'medical-006',
    name: 'معالجة مخلفات المختبرات الطبية',
    description: 'لعينات الدم والزراعات البكتيرية',
    waste_category: 'medical_hazardous',
    waste_types: ['medical'],
    opening_declaration: 'نقر باستلام مخلفات المختبرات الطبية للتعقيم والتخلص.',
    processing_details_template: 'تم تعقيم العينات والزراعات بالأوتوكلاف ثم التخلص منها كنفايات غير خطرة.',
    closing_declaration: 'تم القضاء على جميع الكائنات الدقيقة والتخلص الآمن من المخلفات.',
    tags: ['مختبر', 'عينات', 'بكتيريا'],
  },
  {
    id: 'medical-007',
    name: 'التخلص من مخلفات العلاج الكيميائي',
    description: 'للأدوية السامة للخلايا',
    waste_category: 'medical_hazardous',
    waste_types: ['medical'],
    opening_declaration: 'استلمنا مخلفات العلاج الكيميائي في حاويات مخصصة.',
    processing_details_template: 'تم حرق مخلفات العلاج الكيميائي في محرقة عالية الحرارة مع معالجة خاصة للانبعاثات.',
    closing_declaration: 'تم التخلص الآمن من المخلفات السامة للخلايا بالحرق الآمن.',
    tags: ['كيميائي', 'علاج', 'سام'],
  },
  {
    id: 'medical-008',
    name: 'معالجة مخلفات غسيل الكلى',
    description: 'للفلاتر والأنابيب الملوثة',
    waste_category: 'medical_hazardous',
    waste_types: ['medical'],
    opening_declaration: 'تم استلام مخلفات أقسام غسيل الكلى للتعقيم والتخلص.',
    processing_details_template: 'تم تعقيم الفلاتر والأنابيب بالأوتوكلاف ثم تمزيقها للتخلص الآمن.',
    closing_declaration: 'أكملنا التخلص الآمن من مخلفات غسيل الكلى بعد التعقيم الكامل.',
    tags: ['كلى', 'غسيل', 'فلاتر'],
  },
  {
    id: 'medical-009',
    name: 'التخلص من مخلفات الأسنان',
    description: 'للحشوات والأملغم',
    waste_category: 'medical_hazardous',
    waste_types: ['medical'],
    opening_declaration: 'نقر باستلام مخلفات عيادات الأسنان للتخلص المتخصص.',
    processing_details_template: 'تم استخلاص الزئبق من حشوات الأملغم ومعالجة المخلفات الأخرى بالتعقيم.',
    closing_declaration: 'تم استرداد الزئبق والتخلص الآمن من مخلفات الأسنان.',
    tags: ['أسنان', 'زئبق', 'أملغم'],
  },
  {
    id: 'medical-010',
    name: 'معالجة مخلفات كوفيد-19',
    description: 'للمخلفات المرتبطة بالجائحة',
    waste_category: 'medical_hazardous',
    waste_types: ['medical'],
    opening_declaration: 'استلمنا مخلفات العزل ومناطق كوفيد-19 للتخلص الآمن.',
    processing_details_template: 'تم تعقيم جميع المخلفات بالأوتوكلاف مع اتباع بروتوكولات خاصة لمنع انتشار العدوى.',
    closing_declaration: 'تم التخلص الآمن من مخلفات كوفيد-19 وفق إرشادات منظمة الصحة العالمية.',
    tags: ['كوفيد', 'عزل', 'وباء'],
  },
];

// ============================================
// قوالب مخلفات البناء (10 قوالب)
// ============================================
const constructionTemplates: RecyclingReportTemplate[] = [
  {
    id: 'construction-001',
    name: 'تقرير مخلفات البناء - قياسي',
    description: 'قالب عام لمخلفات البناء والهدم',
    waste_category: 'non_hazardous',
    waste_types: ['construction'],
    opening_declaration: 'نقر باستلام شحنة مخلفات البناء والهدم الموضحة أدناه للفرز والتدوير.',
    processing_details_template: 'تم فرز المخلفات إلى (خرسانة، طوب، خشب، معادن، بلاستيك) وتكسير وطحن كل نوع للاستخدام.',
    closing_declaration: 'أتممنا تدوير مخلفات البناء وتحويلها إلى مواد قابلة للاستخدام في البناء.',
    tags: ['بناء', 'هدم', 'خرسانة'],
  },
  {
    id: 'construction-002',
    name: 'تدوير الخرسانة المكسرة',
    description: 'لأنقاض الخرسانة المسلحة',
    waste_category: 'non_hazardous',
    waste_types: ['construction'],
    opening_declaration: 'تم استلام أنقاض الخرسانة من مواقع الهدم للتكسير والتدوير.',
    processing_details_template: 'تم تكسير الخرسانة وفصل حديد التسليح وإنتاج ركام معاد تدويره للاستخدام في البناء.',
    closing_declaration: 'تم تحويل الخرسانة إلى ركام معاد تدويره صالح للبناء والطرق.',
    tags: ['خرسانة', 'ركام', 'تكسير'],
  },
  {
    id: 'construction-003',
    name: 'تدوير الطوب والبلوك',
    description: 'للطوب الأحمر والإسمنتي',
    waste_category: 'non_hazardous',
    waste_types: ['construction'],
    opening_declaration: 'نقر باستلام مخلفات الطوب والبلوك للتكسير والتدوير.',
    processing_details_template: 'تم تكسير الطوب وغربلته لإنتاج مواد ردم ومكونات للخرسانة.',
    closing_declaration: 'أكملنا تدوير الطوب وتحويله لمواد بناء ثانوية.',
    tags: ['طوب', 'بلوك', 'ردم'],
  },
  {
    id: 'construction-004',
    name: 'تدوير الأخشاب الإنشائية',
    description: 'للقوالب والسقالات الخشبية',
    waste_category: 'non_hazardous',
    waste_types: ['construction'],
    opening_declaration: 'استلمنا الأخشاب المستعملة من مواقع البناء للتدوير.',
    processing_details_template: 'تم فرز الأخشاب الصالحة لإعادة الاستخدام وتحويل الباقي إلى نشارة أو وقود حيوي.',
    closing_declaration: 'تم استرداد الأخشاب الصالحة وتدوير الباقي بشكل مفيد.',
    tags: ['خشب', 'قوالب', 'سقالات'],
  },
  {
    id: 'construction-005',
    name: 'تدوير مخلفات الأسقف',
    description: 'للقرميد والعزل والجبس',
    waste_category: 'non_hazardous',
    waste_types: ['construction'],
    opening_declaration: 'تم استلام مخلفات الأسقف (قرميد، عزل، ألواح جبس) للفرز والتدوير.',
    processing_details_template: 'تم فصل المواد حسب النوع وتدوير كل منها بالطريقة المناسبة.',
    closing_declaration: 'أتممنا تدوير مخلفات الأسقف وتحويلها لمواد مفيدة.',
    tags: ['أسقف', 'قرميد', 'جبس'],
  },
  {
    id: 'construction-006',
    name: 'تدوير الأسفلت القديم',
    description: 'لرصف الطرق المقشور',
    waste_category: 'non_hazardous',
    waste_types: ['construction'],
    opening_declaration: 'نقر باستلام الأسفلت المقشور من مشاريع صيانة الطرق.',
    processing_details_template: 'تم تكسير الأسفلت وإعادة تسخينه لاستخدامه في خلطات الأسفلت الجديدة.',
    closing_declaration: 'تم تدوير الأسفلت وإعادة استخدامه في رصف الطرق.',
    tags: ['أسفلت', 'طرق', 'رصف'],
  },
  {
    id: 'construction-007',
    name: 'تدوير نوافذ الألومنيوم',
    description: 'للنوافذ والأبواب القديمة',
    waste_category: 'non_hazardous',
    waste_types: ['construction'],
    opening_declaration: 'استلمنا نوافذ وأبواب الألومنيوم القديمة للتفكيك والتدوير.',
    processing_details_template: 'تم فصل الألومنيوم عن الزجاج والمطاط وتدوير كل مكون على حدة.',
    closing_declaration: 'أكملنا تدوير نوافذ الألومنيوم واستخلاص المعادن والزجاج.',
    tags: ['ألومنيوم', 'نوافذ', 'أبواب'],
  },
  {
    id: 'construction-008',
    name: 'تدوير السيراميك والبلاط',
    description: 'للبلاط والسيراميك المكسور',
    waste_category: 'non_hazardous',
    waste_types: ['construction'],
    opening_declaration: 'تم استلام السيراميك والبلاط المكسور من مشاريع التجديد.',
    processing_details_template: 'تم تكسير السيراميك واستخدامه كركام للخرسانة أو مواد ردم.',
    closing_declaration: 'تم تحويل السيراميك المكسور إلى ركام مفيد للبناء.',
    tags: ['سيراميك', 'بلاط', 'ركام'],
  },
  {
    id: 'construction-009',
    name: 'تدوير مخلفات الصرف الصحي',
    description: 'للأنابيب والتوصيلات القديمة',
    waste_category: 'non_hazardous',
    waste_types: ['construction'],
    opening_declaration: 'نقر باستلام أنابيب وتوصيلات الصرف القديمة للتدوير.',
    processing_details_template: 'تم تنظيف وفصل الأنابيب حسب المادة (PVC، حديد، فخار) وتدوير كل نوع.',
    closing_declaration: 'أتممنا تدوير مخلفات الصرف الصحي بشكل صحي وآمن.',
    tags: ['صرف', 'أنابيب', 'PVC'],
  },
  {
    id: 'construction-010',
    name: 'تدوير التربة والحفريات',
    description: 'للتربة النظيفة من الحفريات',
    waste_category: 'non_hazardous',
    waste_types: ['construction'],
    opening_declaration: 'استلمنا التربة الناتجة عن أعمال الحفر للاستفادة منها.',
    processing_details_template: 'تم غربلة التربة وفحصها للتأكد من خلوها من الملوثات واستخدامها في الردم.',
    closing_declaration: 'تم إعادة استخدام التربة النظيفة في مشاريع الردم والتسوية.',
    tags: ['تربة', 'حفريات', 'ردم'],
  },
];

// ============================================
// قوالب متنوعة/أخرى (10 قوالب)
// ============================================
const otherTemplates: RecyclingReportTemplate[] = [
  {
    id: 'other-001',
    name: 'تقرير مخلفات متنوعة - قياسي',
    description: 'قالب عام للمخلفات المختلطة',
    waste_category: 'all',
    waste_types: ['other'],
    opening_declaration: 'نقر باستلام شحنة المخلفات المتنوعة الموضحة أدناه للفرز والمعالجة.',
    processing_details_template: 'تم فرز المخلفات وتصنيفها حسب النوع والمادة، ثم معالجة كل صنف بالطريقة المناسبة.',
    closing_declaration: 'أتممنا فرز ومعالجة المخلفات المتنوعة وتحويلها لمواد قابلة للاستخدام.',
    tags: ['متنوع', 'مختلط', 'فرز'],
  },
  {
    id: 'other-002',
    name: 'تدوير الإطارات المستعملة',
    description: 'لإطارات السيارات والشاحنات',
    waste_category: 'non_hazardous',
    waste_types: ['other'],
    opening_declaration: 'تم استلام الإطارات المستعملة للتدوير أو إعادة الاستخدام.',
    processing_details_template: 'تم تقطيع الإطارات واستخلاص المطاط والأسلاك المعدنية وتحويلها لمنتجات جديدة.',
    closing_declaration: 'أكملنا تدوير الإطارات وتحويلها لمنتجات مطاطية ومواد بناء.',
    tags: ['إطارات', 'مطاط', 'سيارات'],
  },
  {
    id: 'other-003',
    name: 'تدوير المنسوجات والملابس',
    description: 'للملابس المستعملة والأقمشة',
    waste_category: 'non_hazardous',
    waste_types: ['other'],
    opening_declaration: 'نقر باستلام المنسوجات والملابس المستعملة للتدوير.',
    processing_details_template: 'تم فرز الملابس الصالحة للاستخدام وتحويل الباقي لألياف معاد تدويرها.',
    closing_declaration: 'تم استرداد الملابس الصالحة وتدوير الأقمشة لإنتاج ألياف جديدة.',
    tags: ['ملابس', 'أقمشة', 'ألياف'],
  },
  {
    id: 'other-004',
    name: 'تدوير البطاريات العادية',
    description: 'للبطاريات القلوية والجافة',
    waste_category: 'non_hazardous',
    waste_types: ['other'],
    opening_declaration: 'استلمنا البطاريات العادية المستهلكة للتدوير الآمن.',
    processing_details_template: 'تم فصل المكونات واستخلاص الزنك والمنغنيز والكربون للاستخدام الصناعي.',
    closing_declaration: 'تم تدوير البطاريات العادية واستخلاص المعادن القيمة.',
    tags: ['بطاريات', 'قلوية', 'زنك'],
  },
  {
    id: 'other-005',
    name: 'تدوير الفلين والكورك',
    description: 'لسدادات الزجاجات',
    waste_category: 'non_hazardous',
    waste_types: ['other'],
    opening_declaration: 'تم استلام سدادات الفلين المجمعة للتدوير.',
    processing_details_template: 'تم تنظيف وطحن الفلين لإنتاج حبيبات تستخدم في العزل والأرضيات.',
    closing_declaration: 'أتممنا تدوير الفلين وتحويله لمواد عزل صديقة للبيئة.',
    tags: ['فلين', 'كورك', 'عزل'],
  },
  {
    id: 'other-006',
    name: 'تدوير الشمع والشموع',
    description: 'لبقايا الشموع المستخدمة',
    waste_category: 'non_hazardous',
    waste_types: ['other'],
    opening_declaration: 'نقر باستلام بقايا الشموع المستعملة للتذويب والتدوير.',
    processing_details_template: 'تم تذويب الشمع وتنقيته وإعادة تشكيله لشموع جديدة أو مواد صناعية.',
    closing_declaration: 'تم إعادة تدوير الشموع وإنتاج شموع جديدة أو مواد خام.',
    tags: ['شمع', 'شموع', 'تذويب'],
  },
  {
    id: 'other-007',
    name: 'تدوير الفوم والإسفنج',
    description: 'للفوم والمراتب الإسفنجية',
    waste_category: 'non_hazardous',
    waste_types: ['other'],
    opening_declaration: 'استلمنا مخلفات الفوم والإسفنج للتدوير.',
    processing_details_template: 'تم تقطيع وطحن الإسفنج لاستخدامه في حشو الأثاث أو مواد العزل.',
    closing_declaration: 'أكملنا تدوير الفوم وتحويله لمواد حشو ومنتجات جديدة.',
    tags: ['فوم', 'إسفنج', 'حشو'],
  },
  {
    id: 'other-008',
    name: 'تدوير الشعر البشري',
    description: 'لشعر الصالونات',
    waste_category: 'non_hazardous',
    waste_types: ['other'],
    opening_declaration: 'تم استلام الشعر المقصوص من الصالونات للاستفادة منه.',
    processing_details_template: 'تم تنظيف الشعر واستخدامه في صناعة حصائر امتصاص الزيوت أو أسمدة.',
    closing_declaration: 'تم تحويل الشعر البشري لمنتجات مفيدة بيئياً.',
    tags: ['شعر', 'صالونات', 'امتصاص'],
  },
  {
    id: 'other-009',
    name: 'تدوير الأقلام والقرطاسية',
    description: 'للأدوات المكتبية البلاستيكية',
    waste_category: 'non_hazardous',
    waste_types: ['other'],
    opening_declaration: 'نقر باستلام الأقلام والأدوات المكتبية المستعملة.',
    processing_details_template: 'تم فصل المكونات المعدنية والبلاستيكية وتدوير كل نوع.',
    closing_declaration: 'أتممنا تدوير القرطاسية واستخلاص المواد القابلة للتدوير.',
    tags: ['أقلام', 'قرطاسية', 'مكتبي'],
  },
  {
    id: 'other-010',
    name: 'تدوير الأحذية والجلود',
    description: 'للأحذية والمنتجات الجلدية',
    waste_category: 'non_hazardous',
    waste_types: ['other'],
    opening_declaration: 'استلمنا الأحذية والمنتجات الجلدية المستعملة للتدوير.',
    processing_details_template: 'تم فصل النعال المطاطية عن الجلد وتدوير كل مكون حسب نوعه.',
    closing_declaration: 'أكملنا تدوير الأحذية والجلود وتحويلها لمواد مفيدة.',
    tags: ['أحذية', 'جلود', 'مطاط'],
  },
];

// ============================================
// قوالب مخلفات المصانع الغذائية (10 قوالب)
// ============================================
const foodIndustryTemplates: RecyclingReportTemplate[] = [
  {
    id: 'food-001',
    name: 'مخلفات مصانع الألبان',
    description: 'لبقايا الحليب والأجبان التالفة',
    waste_category: 'non_hazardous',
    waste_types: ['organic', 'other'],
    opening_declaration: 'نقر باستلام مخلفات مصانع الألبان للمعالجة والتحويل.',
    processing_details_template: 'تم فصل السوائل عن المواد الصلبة وتحويلها لأعلاف حيوانية أو سماد عضوي.',
    closing_declaration: 'أتممنا تحويل مخلفات الألبان لمنتجات علفية وسماد مفيد.',
    tags: ['ألبان', 'حليب', 'علف'],
  },
  {
    id: 'food-002',
    name: 'مخلفات مصانع العصائر',
    description: 'لقشور وبقايا الفواكه',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'تم استلام مخلفات مصانع العصائر (قشور، بذور، لب) للتدوير.',
    processing_details_template: 'تم تجفيف القشور لاستخلاص الزيوت العطرية وتحويل الباقي لسماد أو علف.',
    closing_declaration: 'تم استخلاص الزيوت وتحويل البقايا لمنتجات مفيدة.',
    tags: ['عصائر', 'قشور', 'فواكه'],
  },
  {
    id: 'food-003',
    name: 'مخلفات مصانع الزيوت',
    description: 'لكسب البذور وزيوت القلي',
    waste_category: 'non_hazardous',
    waste_types: ['organic', 'chemical'],
    opening_declaration: 'نقر باستلام مخلفات مصانع الزيوت للمعالجة.',
    processing_details_template: 'تم تحويل الكسب لأعلاف حيوانية وجمع زيوت القلي لإنتاج الوقود الحيوي.',
    closing_declaration: 'أكملنا تحويل مخلفات الزيوت لأعلاف ووقود حيوي.',
    tags: ['زيوت', 'كسب', 'بيوديزل'],
  },
  {
    id: 'food-004',
    name: 'مخلفات مصانع اللحوم',
    description: 'للعظام والأحشاء غير المستخدمة',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'استلمنا مخلفات مصانع اللحوم للمعالجة الآمنة.',
    processing_details_template: 'تم طهي المخلفات بالبخار لإنتاج مسحوق العظام والدهون الصناعية.',
    closing_declaration: 'تم تحويل مخلفات اللحوم لمنتجات صناعية مفيدة.',
    tags: ['لحوم', 'عظام', 'دهون'],
  },
  {
    id: 'food-005',
    name: 'مخلفات مصانع السكر',
    description: 'للمولاس وتفل القصب',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'تم استلام مخلفات مصانع السكر للاستفادة منها.',
    processing_details_template: 'تم تحويل المولاس لإيثانول وتفل القصب لوقود حيوي أو ألواح ضغط.',
    closing_declaration: 'أتممنا تحويل مخلفات السكر لإيثانول ومنتجات طاقة.',
    tags: ['سكر', 'مولاس', 'قصب'],
  },
  {
    id: 'food-006',
    name: 'مخلفات مصانع البن',
    description: 'لقشور وتفل البن',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'نقر باستلام مخلفات مصانع البن للتدوير.',
    processing_details_template: 'تم استخدام قشور البن كوقود حيوي وتفل البن كسماد أو في صناعة المستحضرات.',
    closing_declaration: 'أكملنا تحويل مخلفات البن لوقود ومنتجات تجميلية.',
    tags: ['بن', 'قهوة', 'تفل'],
  },
  {
    id: 'food-007',
    name: 'مخلفات مصانع الأعلاف',
    description: 'للمواد المرفوضة والغبار',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'استلمنا مخلفات مصانع الأعلاف للاستفادة منها.',
    processing_details_template: 'تم إعادة معالجة المواد الصالحة وتحويل الغبار لسماد عضوي.',
    closing_declaration: 'تم استرداد المواد الصالحة وتحويل الباقي لسماد.',
    tags: ['أعلاف', 'حيوانات', 'غبار'],
  },
  {
    id: 'food-008',
    name: 'مخلفات مصانع المشروبات الغازية',
    description: 'للسوائل التالفة والشراب',
    waste_category: 'non_hazardous',
    waste_types: ['organic', 'other'],
    opening_declaration: 'تم استلام مخلفات مصانع المشروبات للمعالجة.',
    processing_details_template: 'تم معادلة السوائل وتحويل السكريات لإيثانول حيوي.',
    closing_declaration: 'أتممنا معالجة مخلفات المشروبات وتحويلها لطاقة.',
    tags: ['مشروبات', 'غازية', 'سكر'],
  },
  {
    id: 'food-009',
    name: 'مخلفات مصانع الشوكولاتة',
    description: 'لقشور الكاكاو والمرفوضات',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'نقر باستلام مخلفات مصانع الشوكولاتة للتدوير.',
    processing_details_template: 'تم استخدام قشور الكاكاو كنشارة للحدائق وتحويل المرفوضات لأعلاف.',
    closing_declaration: 'أكملنا تحويل مخلفات الشوكولاتة لمنتجات مفيدة.',
    tags: ['شوكولاتة', 'كاكاو', 'حدائق'],
  },
  {
    id: 'food-010',
    name: 'مخلفات مصانع المعلبات',
    description: 'للخضار والفواكه المرفوضة',
    waste_category: 'non_hazardous',
    waste_types: ['organic'],
    opening_declaration: 'استلمنا مخلفات مصانع المعلبات للتحويل.',
    processing_details_template: 'تم تحويل المواد العضوية لسماد عالي الجودة عبر التخمير السريع.',
    closing_declaration: 'تم إنتاج سماد عضوي من مخلفات التعليب.',
    tags: ['معلبات', 'خضار', 'سماد'],
  },
];

// ============================================
// تجميع جميع القوالب
// ============================================
export const allRecyclingTemplates: RecyclingReportTemplate[] = [
  ...plasticTemplates,
  ...paperTemplates,
  ...metalTemplates,
  ...glassTemplates,
  ...electronicTemplates,
  ...organicTemplates,
  ...chemicalTemplates,
  ...medicalTemplates,
  ...constructionTemplates,
  ...otherTemplates,
  ...foodIndustryTemplates,
];

// ============================================
// دوال مساعدة
// ============================================

/**
 * الحصول على القوالب حسب نوع المخلفات
 */
export const getTemplatesByWasteType = (wasteType: string): RecyclingReportTemplate[] => {
  return allRecyclingTemplates.filter(t => 
    t.waste_types.includes(wasteType) || t.waste_category === 'all'
  );
};

/**
 * الحصول على القوالب حسب الفئة
 */
export const getTemplatesByCategory = (category: RecyclingReportTemplate['waste_category']): RecyclingReportTemplate[] => {
  if (category === 'all') return allRecyclingTemplates;
  return allRecyclingTemplates.filter(t => t.waste_category === category);
};

/**
 * البحث في القوالب بالكلمات المفتاحية
 */
export const searchTemplates = (query: string): RecyclingReportTemplate[] => {
  const lowerQuery = query.toLowerCase();
  return allRecyclingTemplates.filter(t => 
    t.name.toLowerCase().includes(lowerQuery) ||
    t.description.toLowerCase().includes(lowerQuery) ||
    t.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
};

/**
 * الحصول على قالب عشوائي حسب النوع
 */
export const getRandomTemplate = (wasteType?: string): RecyclingReportTemplate => {
  const templates = wasteType ? getTemplatesByWasteType(wasteType) : allRecyclingTemplates;
  return templates[Math.floor(Math.random() * templates.length)];
};

/**
 * تحويل نوع المخلفات للفئة
 */
export const wasteTypeToCategory = (wasteType: string): RecyclingReportTemplate['waste_category'] => {
  const hazardousTypes = ['chemical', 'electronic'];
  const medicalTypes = ['medical'];
  
  if (medicalTypes.includes(wasteType)) return 'medical_hazardous';
  if (hazardousTypes.includes(wasteType)) return 'hazardous';
  return 'non_hazardous';
};

// إحصائيات القوالب
export const templateStats = {
  total: allRecyclingTemplates.length,
  byCategory: {
    hazardous: allRecyclingTemplates.filter(t => t.waste_category === 'hazardous').length,
    non_hazardous: allRecyclingTemplates.filter(t => t.waste_category === 'non_hazardous').length,
    medical_hazardous: allRecyclingTemplates.filter(t => t.waste_category === 'medical_hazardous').length,
    all: allRecyclingTemplates.filter(t => t.waste_category === 'all').length,
  },
  byWasteType: {
    plastic: plasticTemplates.length,
    paper: paperTemplates.length,
    metal: metalTemplates.length,
    glass: glassTemplates.length,
    electronic: electronicTemplates.length,
    organic: organicTemplates.length,
    chemical: chemicalTemplates.length,
    medical: medicalTemplates.length,
    construction: constructionTemplates.length,
    other: otherTemplates.length,
    food_industry: foodIndustryTemplates.length,
  }
};

export default allRecyclingTemplates;
