export interface PrintTheme {
  id: string;
  name: string;
  nameEn: string;
  description: string;
  preview: string;
  colors: {
    primary: string;
    primaryLight: string;
    primaryDark: string;
    secondary: string;
    accent: string;
    border: string;
    borderLight: string;
    headerBg: string;
    headerText: string;
    labelBg: string;
    labelText: string;
    generatorBg: string;
    generatorText: string;
    generatorLight: string;
    transporterBg: string;
    transporterText: string;
    transporterLight: string;
    recyclerBg: string;
    recyclerText: string;
    recyclerLight: string;
    shipmentBg: string;
    shipmentText: string;
    stampBg: string;
    stampText: string;
    statusBg: string;
    statusText: string;
    statusBorder: string;
    footerText: string;
    watermark: string;
    securityBorder: string;
    securityPattern: string;
  };
  font: string;
  borderRadius: string;
  tableStyle: 'classic' | 'modern' | 'minimal' | 'striped';
}

export const PRINT_THEMES: PrintTheme[] = [
  {
    id: 'eco-green',
    name: 'البيئي الأخضر',
    nameEn: 'Eco Green',
    description: 'السمة الافتراضية - ألوان بيئية خضراء',
    preview: '🌿',
    colors: {
      primary: '#16a34a',
      primaryLight: '#dcfce7',
      primaryDark: '#166534',
      secondary: '#22c55e',
      accent: '#86efac',
      border: '#d1d5db',
      borderLight: '#e5e7eb',
      headerBg: 'linear-gradient(135deg, #16a34a 0%, #22c55e 100%)',
      headerText: '#ffffff',
      labelBg: '#f9fafb',
      labelText: '#4b5563',
      generatorBg: '#dbeafe',
      generatorText: '#000000',
      generatorLight: '#dbeafe',
      transporterBg: '#fef3c7',
      transporterText: '#000000',
      transporterLight: '#fef3c7',
      recyclerBg: '#dcfce7',
      recyclerText: '#000000',
      recyclerLight: '#dcfce7',
      shipmentBg: '#f5f5dc',
      shipmentText: '#000000',
      stampBg: '#e2e8f0',
      stampText: '#000000',
      statusBg: '#dcfce7',
      statusText: '#166534',
      statusBorder: '#86efac',
      footerText: '#9ca3af',
      watermark: 'rgba(22, 163, 74, 0.04)',
      securityBorder: 'rgba(22, 163, 74, 0.3)',
      securityPattern: '#16a34a',
    },
    font: "'Segoe UI', Tahoma, Arial, sans-serif",
    borderRadius: '4px',
    tableStyle: 'classic',
  },
  {
    id: 'corporate-blue',
    name: 'المؤسسي الأزرق',
    nameEn: 'Corporate Blue',
    description: 'مظهر رسمي للشركات الكبرى',
    preview: '🏢',
    colors: {
      primary: '#1e40af',
      primaryLight: '#dbeafe',
      primaryDark: '#1e3a5f',
      secondary: '#3b82f6',
      accent: '#93c5fd',
      border: '#cbd5e1',
      borderLight: '#e2e8f0',
      headerBg: 'linear-gradient(135deg, #1e40af 0%, #3b82f6 100%)',
      headerText: '#ffffff',
      labelBg: '#f1f5f9',
      labelText: '#475569',
      generatorBg: '#e0f2fe',
      generatorText: '#000000',
      generatorLight: '#e0f2fe',
      transporterBg: '#ede9fe',
      transporterText: '#000000',
      transporterLight: '#ede9fe',
      recyclerBg: '#d1fae5',
      recyclerText: '#000000',
      recyclerLight: '#d1fae5',
      shipmentBg: '#dbeafe',
      shipmentText: '#000000',
      stampBg: '#e2e8f0',
      stampText: '#000000',
      statusBg: '#dbeafe',
      statusText: '#1e40af',
      statusBorder: '#93c5fd',
      footerText: '#94a3b8',
      watermark: 'rgba(30, 64, 175, 0.04)',
      securityBorder: 'rgba(30, 64, 175, 0.3)',
      securityPattern: '#1e40af',
    },
    font: "'Segoe UI', Tahoma, Arial, sans-serif",
    borderRadius: '3px',
    tableStyle: 'modern',
  },
  {
    id: 'royal-gold',
    name: 'الملكي الذهبي',
    nameEn: 'Royal Gold',
    description: 'مظهر فاخر بألوان ذهبية وكحلي',
    preview: '👑',
    colors: {
      primary: '#92400e',
      primaryLight: '#fef3c7',
      primaryDark: '#78350f',
      secondary: '#d97706',
      accent: '#fbbf24',
      border: '#d6d3d1',
      borderLight: '#e7e5e4',
      headerBg: 'linear-gradient(135deg, #78350f 0%, #b45309 100%)',
      headerText: '#ffffff',
      labelBg: '#fafaf9',
      labelText: '#57534e',
      generatorBg: '#e0f2fe',
      generatorText: '#000000',
      generatorLight: '#e0f2fe',
      transporterBg: '#fef3c7',
      transporterText: '#000000',
      transporterLight: '#fef3c7',
      recyclerBg: '#d1fae5',
      recyclerText: '#000000',
      recyclerLight: '#d1fae5',
      shipmentBg: '#fef3c7',
      shipmentText: '#000000',
      stampBg: '#e7e5e4',
      stampText: '#000000',
      statusBg: '#fef3c7',
      statusText: '#92400e',
      statusBorder: '#fbbf24',
      footerText: '#a8a29e',
      watermark: 'rgba(146, 64, 14, 0.04)',
      securityBorder: 'rgba(217, 119, 6, 0.3)',
      securityPattern: '#d97706',
    },
    font: "'Segoe UI', Tahoma, Arial, sans-serif",
    borderRadius: '2px',
    tableStyle: 'classic',
  },
  {
    id: 'modern-dark',
    name: 'العصري الداكن',
    nameEn: 'Modern Dark',
    description: 'تصميم عصري بألوان داكنة وجريئة',
    preview: '🌑',
    colors: {
      primary: '#18181b',
      primaryLight: '#f4f4f5',
      primaryDark: '#09090b',
      secondary: '#3f3f46',
      accent: '#a1a1aa',
      border: '#3f3f46',
      borderLight: '#52525b',
      headerBg: 'linear-gradient(135deg, #18181b 0%, #3f3f46 100%)',
      headerText: '#ffffff',
      labelBg: '#27272a',
      labelText: '#d4d4d8',
      generatorBg: '#1d4ed8',
      generatorText: '#ffffff',
      generatorLight: '#1e293b',
      transporterBg: '#ca8a04',
      transporterText: '#ffffff',
      transporterLight: '#1c1917',
      recyclerBg: '#15803d',
      recyclerText: '#ffffff',
      recyclerLight: '#14532d',
      shipmentBg: '#18181b',
      shipmentText: '#e4e4e7',
      stampBg: '#09090b',
      stampText: '#e4e4e7',
      statusBg: '#27272a',
      statusText: '#a1a1aa',
      statusBorder: '#3f3f46',
      footerText: '#71717a',
      watermark: 'rgba(24, 24, 27, 0.06)',
      securityBorder: 'rgba(63, 63, 70, 0.4)',
      securityPattern: '#3f3f46',
    },
    font: "'Segoe UI', Tahoma, Arial, sans-serif",
    borderRadius: '6px',
    tableStyle: 'modern',
  },
  {
    id: 'elegant-purple',
    name: 'الأنيق البنفسجي',
    nameEn: 'Elegant Purple',
    description: 'تصميم أنيق بدرجات البنفسجي',
    preview: '💜',
    colors: {
      primary: '#7c3aed',
      primaryLight: '#ede9fe',
      primaryDark: '#5b21b6',
      secondary: '#8b5cf6',
      accent: '#c4b5fd',
      border: '#d8b4fe',
      borderLight: '#e9d5ff',
      headerBg: 'linear-gradient(135deg, #5b21b6 0%, #7c3aed 100%)',
      headerText: '#ffffff',
      labelBg: '#faf5ff',
      labelText: '#6b21a8',
      generatorBg: '#2563eb',
      generatorText: '#ffffff',
      generatorLight: '#dbeafe',
      transporterBg: '#c026d3',
      transporterText: '#ffffff',
      transporterLight: '#fae8ff',
      recyclerBg: '#059669',
      recyclerText: '#ffffff',
      recyclerLight: '#d1fae5',
      shipmentBg: 'linear-gradient(135deg, #5b21b6 0%, #8b5cf6 100%)',
      shipmentText: '#ffffff',
      stampBg: '#3b0764',
      stampText: '#c4b5fd',
      statusBg: '#ede9fe',
      statusText: '#5b21b6',
      statusBorder: '#c4b5fd',
      footerText: '#a78bfa',
      watermark: 'rgba(124, 58, 237, 0.04)',
      securityBorder: 'rgba(124, 58, 237, 0.3)',
      securityPattern: '#7c3aed',
    },
    font: "'Segoe UI', Tahoma, Arial, sans-serif",
    borderRadius: '8px',
    tableStyle: 'striped',
  },
  {
    id: 'classic-red',
    name: 'الكلاسيكي الأحمر',
    nameEn: 'Classic Red',
    description: 'مظهر تقليدي بألوان حمراء داكنة',
    preview: '🔴',
    colors: {
      primary: '#991b1b',
      primaryLight: '#fef2f2',
      primaryDark: '#7f1d1d',
      secondary: '#dc2626',
      accent: '#fca5a5',
      border: '#d1d5db',
      borderLight: '#e5e7eb',
      headerBg: 'linear-gradient(135deg, #7f1d1d 0%, #991b1b 100%)',
      headerText: '#ffffff',
      labelBg: '#fef2f2',
      labelText: '#991b1b',
      generatorBg: '#1e40af',
      generatorText: '#ffffff',
      generatorLight: '#dbeafe',
      transporterBg: '#b45309',
      transporterText: '#ffffff',
      transporterLight: '#fef3c7',
      recyclerBg: '#166534',
      recyclerText: '#ffffff',
      recyclerLight: '#dcfce7',
      shipmentBg: '#991b1b',
      shipmentText: '#ffffff',
      stampBg: '#450a0a',
      stampText: '#fca5a5',
      statusBg: '#fef2f2',
      statusText: '#991b1b',
      statusBorder: '#fca5a5',
      footerText: '#9ca3af',
      watermark: 'rgba(153, 27, 27, 0.04)',
      securityBorder: 'rgba(153, 27, 27, 0.3)',
      securityPattern: '#991b1b',
    },
    font: "'Segoe UI', Tahoma, Arial, sans-serif",
    borderRadius: '2px',
    tableStyle: 'classic',
  },
  {
    id: 'ocean-teal',
    name: 'المحيط التركوازي',
    nameEn: 'Ocean Teal',
    description: 'ألوان بحرية هادئة ومريحة',
    preview: '🌊',
    colors: {
      primary: '#0d9488',
      primaryLight: '#ccfbf1',
      primaryDark: '#134e4a',
      secondary: '#14b8a6',
      accent: '#5eead4',
      border: '#99f6e4',
      borderLight: '#ccfbf1',
      headerBg: 'linear-gradient(135deg, #134e4a 0%, #0d9488 100%)',
      headerText: '#ffffff',
      labelBg: '#f0fdfa',
      labelText: '#115e59',
      generatorBg: '#0284c7',
      generatorText: '#ffffff',
      generatorLight: '#e0f2fe',
      transporterBg: '#7c3aed',
      transporterText: '#ffffff',
      transporterLight: '#ede9fe',
      recyclerBg: '#16a34a',
      recyclerText: '#ffffff',
      recyclerLight: '#dcfce7',
      shipmentBg: 'linear-gradient(135deg, #134e4a 0%, #14b8a6 100%)',
      shipmentText: '#ffffff',
      stampBg: '#042f2e',
      stampText: '#5eead4',
      statusBg: '#ccfbf1',
      statusText: '#0d9488',
      statusBorder: '#5eead4',
      footerText: '#94a3b8',
      watermark: 'rgba(13, 148, 136, 0.04)',
      securityBorder: 'rgba(13, 148, 136, 0.3)',
      securityPattern: '#0d9488',
    },
    font: "'Segoe UI', Tahoma, Arial, sans-serif",
    borderRadius: '6px',
    tableStyle: 'modern',
  },
  {
    id: 'wmra-official',
    name: 'الرسمي (WMRA)',
    nameEn: 'WMRA Official',
    description: 'نموذج رسمي لجهاز تنظيم إدارة المخلفات',
    preview: '🏛️',
    colors: {
      primary: '#1e3a5f',
      primaryLight: '#e0f2fe',
      primaryDark: '#0c1f3d',
      secondary: '#2563eb',
      accent: '#60a5fa',
      border: '#9ca3af',
      borderLight: '#d1d5db',
      headerBg: 'linear-gradient(135deg, #0c1f3d 0%, #1e3a5f 100%)',
      headerText: '#ffffff',
      labelBg: '#f3f4f6',
      labelText: '#374151',
      generatorBg: '#1e3a5f',
      generatorText: '#ffffff',
      generatorLight: '#e0f2fe',
      transporterBg: '#1e3a5f',
      transporterText: '#ffffff',
      transporterLight: '#e0f2fe',
      recyclerBg: '#1e3a5f',
      recyclerText: '#ffffff',
      recyclerLight: '#e0f2fe',
      shipmentBg: '#1e3a5f',
      shipmentText: '#ffffff',
      stampBg: '#0c1f3d',
      stampText: '#60a5fa',
      statusBg: '#e0f2fe',
      statusText: '#1e3a5f',
      statusBorder: '#60a5fa',
      footerText: '#6b7280',
      watermark: 'rgba(30, 58, 95, 0.04)',
      securityBorder: 'rgba(30, 58, 95, 0.3)',
      securityPattern: '#1e3a5f',
    },
    font: "'Segoe UI', Tahoma, Arial, sans-serif",
    borderRadius: '0px',
    tableStyle: 'classic',
  },
  // === 7 NEW THEMES ===
  {
    id: 'sunset-orange',
    name: 'غروب برتقالي',
    nameEn: 'Sunset Orange',
    description: 'ألوان دافئة بتدرجات الغروب',
    preview: '🌅',
    colors: {
      primary: '#ea580c',
      primaryLight: '#fff7ed',
      primaryDark: '#9a3412',
      secondary: '#f97316',
      accent: '#fdba74',
      border: '#fed7aa',
      borderLight: '#ffedd5',
      headerBg: 'linear-gradient(135deg, #9a3412 0%, #ea580c 50%, #f97316 100%)',
      headerText: '#ffffff',
      labelBg: '#fff7ed',
      labelText: '#9a3412',
      generatorBg: '#0284c7',
      generatorText: '#ffffff',
      generatorLight: '#e0f2fe',
      transporterBg: '#ea580c',
      transporterText: '#ffffff',
      transporterLight: '#fff7ed',
      recyclerBg: '#059669',
      recyclerText: '#ffffff',
      recyclerLight: '#d1fae5',
      shipmentBg: 'linear-gradient(135deg, #9a3412 0%, #ea580c 100%)',
      shipmentText: '#ffffff',
      stampBg: '#431407',
      stampText: '#fdba74',
      statusBg: '#fff7ed',
      statusText: '#9a3412',
      statusBorder: '#fdba74',
      footerText: '#a8a29e',
      watermark: 'rgba(234, 88, 12, 0.04)',
      securityBorder: 'rgba(234, 88, 12, 0.3)',
      securityPattern: '#ea580c',
    },
    font: "'Segoe UI', Tahoma, Arial, sans-serif",
    borderRadius: '6px',
    tableStyle: 'striped',
  },
  {
    id: 'rose-pink',
    name: 'الوردي الأنيق',
    nameEn: 'Rose Pink',
    description: 'تصميم ناعم بدرجات الوردي',
    preview: '🌸',
    colors: {
      primary: '#be185d',
      primaryLight: '#fce7f3',
      primaryDark: '#831843',
      secondary: '#ec4899',
      accent: '#f9a8d4',
      border: '#fbcfe8',
      borderLight: '#fce7f3',
      headerBg: 'linear-gradient(135deg, #831843 0%, #be185d 100%)',
      headerText: '#ffffff',
      labelBg: '#fdf2f8',
      labelText: '#9d174d',
      generatorBg: '#4f46e5',
      generatorText: '#ffffff',
      generatorLight: '#e0e7ff',
      transporterBg: '#be185d',
      transporterText: '#ffffff',
      transporterLight: '#fce7f3',
      recyclerBg: '#059669',
      recyclerText: '#ffffff',
      recyclerLight: '#d1fae5',
      shipmentBg: 'linear-gradient(135deg, #831843 0%, #ec4899 100%)',
      shipmentText: '#ffffff',
      stampBg: '#500724',
      stampText: '#f9a8d4',
      statusBg: '#fce7f3',
      statusText: '#831843',
      statusBorder: '#f9a8d4',
      footerText: '#9ca3af',
      watermark: 'rgba(190, 24, 93, 0.04)',
      securityBorder: 'rgba(190, 24, 93, 0.3)',
      securityPattern: '#be185d',
    },
    font: "'Segoe UI', Tahoma, Arial, sans-serif",
    borderRadius: '8px',
    tableStyle: 'modern',
  },
  {
    id: 'forest-earth',
    name: 'الغابة الترابي',
    nameEn: 'Forest Earth',
    description: 'ألوان طبيعية ترابية من الغابات',
    preview: '🌲',
    colors: {
      primary: '#365314',
      primaryLight: '#ecfccb',
      primaryDark: '#1a2e05',
      secondary: '#4d7c0f',
      accent: '#a3e635',
      border: '#bef264',
      borderLight: '#d9f99d',
      headerBg: 'linear-gradient(135deg, #1a2e05 0%, #365314 50%, #4d7c0f 100%)',
      headerText: '#ffffff',
      labelBg: '#f7fee7',
      labelText: '#365314',
      generatorBg: '#92400e',
      generatorText: '#ffffff',
      generatorLight: '#fef3c7',
      transporterBg: '#365314',
      transporterText: '#ffffff',
      transporterLight: '#ecfccb',
      recyclerBg: '#166534',
      recyclerText: '#ffffff',
      recyclerLight: '#dcfce7',
      shipmentBg: '#365314',
      shipmentText: '#ffffff',
      stampBg: '#1a2e05',
      stampText: '#a3e635',
      statusBg: '#ecfccb',
      statusText: '#365314',
      statusBorder: '#a3e635',
      footerText: '#78716c',
      watermark: 'rgba(54, 83, 20, 0.04)',
      securityBorder: 'rgba(54, 83, 20, 0.3)',
      securityPattern: '#365314',
    },
    font: "'Segoe UI', Tahoma, Arial, sans-serif",
    borderRadius: '4px',
    tableStyle: 'classic',
  },
  {
    id: 'midnight-indigo',
    name: 'منتصف الليل النيلي',
    nameEn: 'Midnight Indigo',
    description: 'تصميم عميق بدرجات النيلي',
    preview: '🌌',
    colors: {
      primary: '#312e81',
      primaryLight: '#e0e7ff',
      primaryDark: '#1e1b4b',
      secondary: '#4338ca',
      accent: '#818cf8',
      border: '#a5b4fc',
      borderLight: '#c7d2fe',
      headerBg: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #4338ca 100%)',
      headerText: '#ffffff',
      labelBg: '#eef2ff',
      labelText: '#3730a3',
      generatorBg: '#0e7490',
      generatorText: '#ffffff',
      generatorLight: '#cffafe',
      transporterBg: '#4338ca',
      transporterText: '#ffffff',
      transporterLight: '#e0e7ff',
      recyclerBg: '#047857',
      recyclerText: '#ffffff',
      recyclerLight: '#d1fae5',
      shipmentBg: 'linear-gradient(135deg, #1e1b4b 0%, #4338ca 100%)',
      shipmentText: '#ffffff',
      stampBg: '#1e1b4b',
      stampText: '#818cf8',
      statusBg: '#e0e7ff',
      statusText: '#312e81',
      statusBorder: '#818cf8',
      footerText: '#6b7280',
      watermark: 'rgba(49, 46, 129, 0.04)',
      securityBorder: 'rgba(49, 46, 129, 0.3)',
      securityPattern: '#312e81',
    },
    font: "'Segoe UI', Tahoma, Arial, sans-serif",
    borderRadius: '5px',
    tableStyle: 'striped',
  },
  {
    id: 'steel-gray',
    name: 'الفولاذي الرمادي',
    nameEn: 'Steel Gray',
    description: 'مظهر صناعي احترافي',
    preview: '⚙️',
    colors: {
      primary: '#374151',
      primaryLight: '#f3f4f6',
      primaryDark: '#1f2937',
      secondary: '#6b7280',
      accent: '#9ca3af',
      border: '#d1d5db',
      borderLight: '#e5e7eb',
      headerBg: 'linear-gradient(135deg, #1f2937 0%, #374151 100%)',
      headerText: '#ffffff',
      labelBg: '#f9fafb',
      labelText: '#4b5563',
      generatorBg: '#1d4ed8',
      generatorText: '#ffffff',
      generatorLight: '#dbeafe',
      transporterBg: '#b45309',
      transporterText: '#ffffff',
      transporterLight: '#fef3c7',
      recyclerBg: '#047857',
      recyclerText: '#ffffff',
      recyclerLight: '#d1fae5',
      shipmentBg: '#374151',
      shipmentText: '#ffffff',
      stampBg: '#111827',
      stampText: '#d1d5db',
      statusBg: '#f3f4f6',
      statusText: '#1f2937',
      statusBorder: '#9ca3af',
      footerText: '#9ca3af',
      watermark: 'rgba(55, 65, 81, 0.04)',
      securityBorder: 'rgba(55, 65, 81, 0.3)',
      securityPattern: '#374151',
    },
    font: "'Segoe UI', Tahoma, Arial, sans-serif",
    borderRadius: '3px',
    tableStyle: 'minimal',
  },
  {
    id: 'cherry-burgundy',
    name: 'الكرزي العنابي',
    nameEn: 'Cherry Burgundy',
    description: 'تصميم فخم بألوان عنابية داكنة',
    preview: '🍒',
    colors: {
      primary: '#881337',
      primaryLight: '#fff1f2',
      primaryDark: '#4c0519',
      secondary: '#be123c',
      accent: '#fb7185',
      border: '#fda4af',
      borderLight: '#fecdd3',
      headerBg: 'linear-gradient(135deg, #4c0519 0%, #881337 50%, #be123c 100%)',
      headerText: '#ffffff',
      labelBg: '#fff1f2',
      labelText: '#9f1239',
      generatorBg: '#1e3a5f',
      generatorText: '#ffffff',
      generatorLight: '#e0f2fe',
      transporterBg: '#881337',
      transporterText: '#ffffff',
      transporterLight: '#fff1f2',
      recyclerBg: '#065f46',
      recyclerText: '#ffffff',
      recyclerLight: '#d1fae5',
      shipmentBg: 'linear-gradient(135deg, #4c0519 0%, #be123c 100%)',
      shipmentText: '#ffffff',
      stampBg: '#4c0519',
      stampText: '#fb7185',
      statusBg: '#fff1f2',
      statusText: '#881337',
      statusBorder: '#fb7185',
      footerText: '#a8a29e',
      watermark: 'rgba(136, 19, 55, 0.04)',
      securityBorder: 'rgba(136, 19, 55, 0.3)',
      securityPattern: '#881337',
    },
    font: "'Segoe UI', Tahoma, Arial, sans-serif",
    borderRadius: '4px',
    tableStyle: 'classic',
  },
  {
    id: 'sky-cyan',
    name: 'السماوي اللازوردي',
    nameEn: 'Sky Cyan',
    description: 'ألوان سماوية مشرقة ومنعشة',
    preview: '☁️',
    colors: {
      primary: '#0891b2',
      primaryLight: '#cffafe',
      primaryDark: '#155e75',
      secondary: '#06b6d4',
      accent: '#67e8f9',
      border: '#a5f3fc',
      borderLight: '#cffafe',
      headerBg: 'linear-gradient(135deg, #155e75 0%, #0891b2 50%, #06b6d4 100%)',
      headerText: '#ffffff',
      labelBg: '#ecfeff',
      labelText: '#164e63',
      generatorBg: '#7c3aed',
      generatorText: '#ffffff',
      generatorLight: '#ede9fe',
      transporterBg: '#0891b2',
      transporterText: '#ffffff',
      transporterLight: '#cffafe',
      recyclerBg: '#16a34a',
      recyclerText: '#ffffff',
      recyclerLight: '#dcfce7',
      shipmentBg: 'linear-gradient(135deg, #155e75 0%, #06b6d4 100%)',
      shipmentText: '#ffffff',
      stampBg: '#083344',
      stampText: '#67e8f9',
      statusBg: '#cffafe',
      statusText: '#155e75',
      statusBorder: '#67e8f9',
      footerText: '#94a3b8',
      watermark: 'rgba(8, 145, 178, 0.04)',
      securityBorder: 'rgba(8, 145, 178, 0.3)',
      securityPattern: '#0891b2',
    },
    font: "'Segoe UI', Tahoma, Arial, sans-serif",
    borderRadius: '6px',
    tableStyle: 'modern',
  },
];

export const getThemeById = (id: string): PrintTheme => {
  return PRINT_THEMES.find(t => t.id === id) || PRINT_THEMES[0];
};
