import { useState, useCallback, useRef } from 'react';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { autoCreateGeneratorDeclaration, autoCreateRecyclerDeclaration } from '@/utils/autoDeclarationCreator';
import { autoCreateReceipt } from '@/utils/autoReceiptCreator';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import { usePDFExport } from '@/hooks/usePDFExport';
import {
  FileSignature,
  FileCheck,
  Receipt,
  Truck,
  Building2,
  Recycle,
  CheckCircle2,
  Clock,
  FileText,
  XCircle,
  Bot,
  AlertTriangle,
  RefreshCw,
  Printer,
  Download,
  Eye,
} from 'lucide-react';
import { format } from 'date-fns';
import { ar } from 'date-fns/locale';
import { toast } from 'sonner';
import GeneratorHandoverDialog from './GeneratorHandoverDialog';
import DeliveryDeclarationViewDialog from './DeliveryDeclarationViewDialog';
import { rejectDeclaration } from '@/utils/autoDeclarationCreator';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';

interface ShipmentDocumentsTimelineProps {
  shipment: {
    id: string;
    shipment_number: string;
    waste_type: string;
    quantity: number;
    unit?: string;
    status: string;
    generator_id?: string;
    transporter_id?: string;
    recycler_id?: string;
    generator?: { name: string } | null;
    transporter?: { name: string } | null;
    recycler?: { name: string } | null;
    manual_disposal_name?: string;
  };
  onRefresh?: () => void;
}

interface DocumentStep {
  key: string;
  label: string;
  icon: React.ReactNode;
  colorClass: string;
  description: string;
  status: 'completed' | 'pending' | 'rejected';
  signedBy?: string;
  signedAt?: string;
  actionAvailable?: boolean;
  canReject?: boolean;
  data?: any;
  autoGenerated?: boolean;
  rejectionReason?: string;
}

const ShipmentDocumentsTimeline = ({ shipment, onRefresh }: ShipmentDocumentsTimelineProps) => {
  const { profile, organization } = useAuth();
  const [showGeneratorHandover, setShowGeneratorHandover] = useState(false);
  const [showDeclarationView, setShowDeclarationView] = useState<any>(null);
  const [rejectingDeclaration, setRejectingDeclaration] = useState<any>(null);
  const [rejectionReason, setRejectionReason] = useState('');
  const [rejecting, setRejecting] = useState(false);
  const [generatingDocs, setGeneratingDocs] = useState(false);
  const [showPrintPreview, setShowPrintPreview] = useState(false);
  
  const printRef = useRef<HTMLDivElement>(null);
  const { exportToPDF, printContent, isExporting } = usePDFExport({
    filename: `document-chain-${shipment.shipment_number}`,
    orientation: 'portrait',
  });

  // Fetch all declarations for this shipment
  const { data: declarations = [], refetch: refetchDeclarations } = useQuery({
    queryKey: ['shipment-documents', shipment.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('delivery_declarations')
        .select('*')
        .eq('shipment_id', shipment.id)
        .order('created_at', { ascending: true });

      if (error) {
        console.error('Error fetching declarations:', error);
        return [];
      }
      return data || [];
    },
    staleTime: 1000 * 60 * 2,
  });

  // Fetch receipts for this shipment
  const { data: receipts = [] } = useQuery({
    queryKey: ['shipment-receipts', shipment.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('shipment_receipts')
        .select('id, receipt_number, status, created_at, created_by')
        .eq('shipment_id', shipment.id)
        .order('created_at', { ascending: true });

      if (error) {
        console.error('Error fetching receipts:', error);
        return [] as any[];
      }
      return (data || []) as any[];
    },
    staleTime: 1000 * 60 * 2,
  });

  const generatorDeclaration = declarations.find((d: any) => d.declaration_type === 'generator_handover' && (d as any).status !== 'rejected');
  const rejectedGeneratorDecl = declarations.find((d: any) => d.declaration_type === 'generator_handover' && (d as any).status === 'rejected');
  const transporterDeclaration = declarations.find((d: any) => (d.declaration_type === 'transporter_delivery' || !d.declaration_type) && (d as any).status !== 'rejected');
  const recyclerDeclaration = declarations.find((d: any) => d.declaration_type === 'recycler_receipt' && (d as any).status !== 'rejected');
  const rejectedRecyclerDecl = declarations.find((d: any) => d.declaration_type === 'recycler_receipt' && (d as any).status === 'rejected');
  const latestReceipt = receipts[receipts.length - 1] as any;

  const isGenerator = organization?.id === shipment.generator_id;
  const isRecycler = organization?.id === shipment.recycler_id;

  const handleReject = async () => {
    if (!rejectingDeclaration || !rejectionReason.trim()) return;
    setRejecting(true);
    try {
      await rejectDeclaration(rejectingDeclaration.id, organization?.id || '', rejectionReason.trim());
      toast.success('تم إلغاء الإقرار بنجاح');
      refetchDeclarations();
      onRefresh?.();
      setRejectingDeclaration(null);
      setRejectionReason('');
    } catch {
      toast.error('فشل في إلغاء الإقرار');
    } finally {
      setRejecting(false);
    }
  };

  const handleGenerateMissingDocs = useCallback(async () => {
    if (!profile?.id) {
      toast.error('يجب تسجيل الدخول أولاً');
      return;
    }
    setGeneratingDocs(true);
    let created = 0;
    try {
      const status = shipment.status;
      if (['approved', 'registered', 'in_transit', 'delivered', 'confirmed'].includes(status) && shipment.generator_id) {
        try { await autoCreateGeneratorDeclaration(shipment.id, shipment.generator_id, profile.id); created++; } catch (e) { console.error('Generator declaration:', e); }
      }
      if (['delivered', 'confirmed'].includes(status) && shipment.recycler_id) {
        try { await autoCreateRecyclerDeclaration(shipment.id, shipment.recycler_id, profile.id); created++; } catch (e) { console.error('Recycler declaration:', e); }
      }
      if (['in_transit', 'delivered', 'confirmed'].includes(status) && shipment.transporter_id) {
        try { await autoCreateReceipt(shipment.id, shipment.transporter_id, profile.id); created++; } catch (e) { console.error('Receipt:', e); }
      }
      if (created > 0) {
        toast.success(`تم إنشاء ${created} مستند(ات) مفقودة بنجاح`);
      } else {
        toast.info('جميع المستندات المتاحة موجودة بالفعل');
      }
      refetchDeclarations();
      onRefresh?.();
    } catch (error) {
      console.error('Error generating missing docs:', error);
      toast.error('حدث خطأ أثناء إنشاء المستندات');
    } finally {
      setGeneratingDocs(false);
    }
  }, [shipment, profile?.id, refetchDeclarations, onRefresh]);

  // Build the document steps
  const steps: DocumentStep[] = [
    {
      key: 'generator_handover',
      label: 'إقرار تسليم المولّد',
      icon: <Building2 className="w-4 h-4" />,
      colorClass: 'blue',
      description: rejectedGeneratorDecl
        ? `مرفوض: ${(rejectedGeneratorDecl as any).rejection_reason || 'بدون سبب'}`
        : 'المولّد يُقر بتسليم المخلفات للناقل — يتم تلقائياً عند بدء النقل',
      status: generatorDeclaration ? 'completed' : rejectedGeneratorDecl ? 'rejected' : 'pending',
      signedBy: generatorDeclaration?.driver_name || generatorDeclaration?.generator_name,
      signedAt: generatorDeclaration?.declared_at,
      actionAvailable: isGenerator && !generatorDeclaration,
      canReject: isGenerator && !!generatorDeclaration && (generatorDeclaration as any).status === 'active',
      data: generatorDeclaration || rejectedGeneratorDecl,
      autoGenerated: (generatorDeclaration as any)?.auto_generated,
      rejectionReason: (rejectedGeneratorDecl as any)?.rejection_reason,
    },
    {
      key: 'transporter_delivery',
      label: 'إقرار تسليم الناقل',
      icon: <Truck className="w-4 h-4" />,
      colorClass: 'purple',
      description: 'الناقل/السائق يُقر بتسليم الشحنة للمدوّر',
      status: transporterDeclaration ? 'completed' : 'pending',
      signedBy: transporterDeclaration?.driver_name || transporterDeclaration?.transporter_name,
      signedAt: transporterDeclaration?.declared_at,
      data: transporterDeclaration,
    },
    {
      key: 'recycler_receipt',
      label: 'إقرار استلام المدوّر',
      icon: <Recycle className="w-4 h-4" />,
      colorClass: 'emerald',
      description: rejectedRecyclerDecl
        ? `مرفوض: ${(rejectedRecyclerDecl as any).rejection_reason || 'بدون سبب'}`
        : 'المدوّر يُقر باستلام المخلفات — يتم تلقائياً عند التسليم',
      status: recyclerDeclaration ? 'completed' : rejectedRecyclerDecl ? 'rejected' : 'pending',
      signedBy: recyclerDeclaration?.recycler_name,
      signedAt: recyclerDeclaration?.declared_at,
      canReject: isRecycler && !!recyclerDeclaration && (recyclerDeclaration as any).status === 'active',
      data: recyclerDeclaration || rejectedRecyclerDecl,
      autoGenerated: (recyclerDeclaration as any)?.auto_generated,
      rejectionReason: (rejectedRecyclerDecl as any)?.rejection_reason,
    },
    {
      key: 'receipt',
      label: 'شهادة الاستلام',
      icon: <Receipt className="w-4 h-4" />,
      colorClass: 'green',
      description: 'شهادة استلام من المدوّر/جهة التخلص',
      status: latestReceipt ? 'completed' : 'pending',
      signedBy: latestReceipt?.issued_by_name,
      signedAt: latestReceipt?.created_at,
      data: latestReceipt,
    },
  ];

  const completedCount = steps.filter(s => s.status === 'completed').length;
  const totalSteps = steps.length;

  const getStatusIcon = (status: string) => {
    if (status === 'completed') return <CheckCircle2 className="w-4 h-4 text-green-600 dark:text-green-400" />;
    if (status === 'rejected') return <XCircle className="w-4 h-4 text-red-500" />;
    return <Clock className="w-4 h-4 text-muted-foreground" />;
  };

  const getStepBorderClass = (status: string) => {
    if (status === 'completed') return 'bg-green-100 border-green-400 dark:bg-green-900/30 dark:border-green-600';
    if (status === 'rejected') return 'bg-red-100 border-red-400 dark:bg-red-900/30 dark:border-red-600';
    return 'bg-muted/50 border-muted-foreground/20';
  };

  const getContentBorderClass = (status: string) => {
    if (status === 'completed') return 'border-green-200 bg-green-50/50 dark:border-green-800 dark:bg-green-950/20';
    if (status === 'rejected') return 'border-red-200 bg-red-50/50 dark:border-red-800 dark:bg-red-950/20';
    return 'border-muted bg-muted/10';
  };

  const declarationTypeLabels: Record<string, string> = {
    'generator_handover': 'إقرار تسليم المولّد',
    'transporter_delivery': 'إقرار تسليم الناقل',
    'recycler_receipt': 'إقرار استلام المدوّر',
  };

  // Printable document chain content
  const PrintableContent = () => (
    <div ref={printRef} dir="rtl" style={{ fontFamily: 'Cairo, sans-serif', padding: '20px', backgroundColor: '#fff', color: '#000' }}>
      {/* Header */}
      <div style={{ textAlign: 'center', marginBottom: '24px', borderBottom: '3px solid #1a56db', paddingBottom: '16px' }}>
        <h1 style={{ fontSize: '22px', fontWeight: 'bold', margin: '0 0 4px 0', color: '#1a56db' }}>
          سلسلة مستندات الشحنة
        </h1>
        <p style={{ fontSize: '13px', color: '#666', margin: 0 }}>
          تقرير شامل لسلسلة الحيازة والمستندات القانونية
        </p>
      </div>

      {/* Shipment Info */}
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '20px', padding: '12px', backgroundColor: '#f8fafc', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
        <div style={{ textAlign: 'right' }}>
          <div style={{ fontSize: '12px', color: '#666' }}>رقم الشحنة</div>
          <div style={{ fontSize: '16px', fontWeight: 'bold' }}>{shipment.shipment_number}</div>
        </div>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: '12px', color: '#666' }}>نوع المخلفات</div>
          <div style={{ fontSize: '14px', fontWeight: '600' }}>{shipment.waste_type}</div>
        </div>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: '12px', color: '#666' }}>الكمية</div>
          <div style={{ fontSize: '14px', fontWeight: '600' }}>{shipment.quantity} {shipment.unit || 'طن'}</div>
        </div>
        <div style={{ textAlign: 'left' }}>
          <div style={{ fontSize: '12px', color: '#666' }}>الحالة</div>
          <div style={{ fontSize: '14px', fontWeight: '600' }}>{shipment.status}</div>
        </div>
      </div>

      {/* Parties */}
      <div style={{ display: 'flex', gap: '12px', marginBottom: '20px' }}>
        {shipment.generator?.name && (
          <div style={{ flex: 1, padding: '10px', border: '1px solid #bfdbfe', borderRadius: '8px', backgroundColor: '#eff6ff' }}>
            <div style={{ fontSize: '10px', color: '#3b82f6', fontWeight: 'bold' }}>🏭 المولّد</div>
            <div style={{ fontSize: '13px', fontWeight: '600' }}>{shipment.generator.name}</div>
          </div>
        )}
        {shipment.transporter?.name && (
          <div style={{ flex: 1, padding: '10px', border: '1px solid #e9d5ff', borderRadius: '8px', backgroundColor: '#faf5ff' }}>
            <div style={{ fontSize: '10px', color: '#9333ea', fontWeight: 'bold' }}>🚚 الناقل</div>
            <div style={{ fontSize: '13px', fontWeight: '600' }}>{shipment.transporter.name}</div>
          </div>
        )}
        {(shipment.recycler?.name || shipment.manual_disposal_name) && (
          <div style={{ flex: 1, padding: '10px', border: '1px solid #a7f3d0', borderRadius: '8px', backgroundColor: '#ecfdf5' }}>
            <div style={{ fontSize: '10px', color: '#059669', fontWeight: 'bold' }}>♻️ المدوّر/جهة التخلص</div>
            <div style={{ fontSize: '13px', fontWeight: '600' }}>{shipment.recycler?.name || shipment.manual_disposal_name}</div>
          </div>
        )}
      </div>

      {/* Completion Summary */}
      <div style={{ marginBottom: '16px', padding: '10px 16px', backgroundColor: completedCount === totalSteps ? '#ecfdf5' : '#fffbeb', borderRadius: '8px', border: `1px solid ${completedCount === totalSteps ? '#a7f3d0' : '#fde68a'}`, textAlign: 'center' }}>
        <span style={{ fontSize: '14px', fontWeight: 'bold', color: completedCount === totalSteps ? '#059669' : '#d97706' }}>
          {completedCount === totalSteps ? '✅ سلسلة المستندات مكتملة' : `⏳ ${completedCount} من ${totalSteps} مستندات مكتملة`}
        </span>
      </div>

      {/* Document Steps */}
      <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '20px' }}>
        <thead>
          <tr style={{ backgroundColor: '#f1f5f9' }}>
            <th style={{ padding: '10px', textAlign: 'right', borderBottom: '2px solid #cbd5e1', fontSize: '12px' }}>المستند</th>
            <th style={{ padding: '10px', textAlign: 'center', borderBottom: '2px solid #cbd5e1', fontSize: '12px' }}>الحالة</th>
            <th style={{ padding: '10px', textAlign: 'right', borderBottom: '2px solid #cbd5e1', fontSize: '12px' }}>بواسطة</th>
            <th style={{ padding: '10px', textAlign: 'left', borderBottom: '2px solid #cbd5e1', fontSize: '12px' }}>التاريخ</th>
          </tr>
        </thead>
        <tbody>
          {steps.map((step) => (
            <tr key={step.key} style={{ borderBottom: '1px solid #e2e8f0' }}>
              <td style={{ padding: '10px', fontSize: '13px', fontWeight: '600' }}>
                {step.label}
                {step.autoGenerated && <span style={{ fontSize: '10px', color: '#9333ea', marginRight: '6px' }}>(🤖 تلقائي)</span>}
              </td>
              <td style={{ padding: '10px', textAlign: 'center' }}>
                <span style={{
                  padding: '3px 10px',
                  borderRadius: '12px',
                  fontSize: '11px',
                  fontWeight: 'bold',
                  backgroundColor: step.status === 'completed' ? '#dcfce7' : step.status === 'rejected' ? '#fee2e2' : '#f3f4f6',
                  color: step.status === 'completed' ? '#166534' : step.status === 'rejected' ? '#991b1b' : '#6b7280',
                }}>
                  {step.status === 'completed' ? '✓ مكتمل' : step.status === 'rejected' ? '✗ مرفوض' : '⏳ معلق'}
                </span>
              </td>
              <td style={{ padding: '10px', fontSize: '12px' }}>{step.signedBy || '—'}</td>
              <td style={{ padding: '10px', fontSize: '12px', textAlign: 'left' }}>
                {step.signedAt ? format(new Date(step.signedAt), 'dd/MM/yyyy HH:mm', { locale: ar }) : '—'}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Declarations Detail */}
      {declarations.length > 0 && (
        <div style={{ marginBottom: '20px' }}>
          <h3 style={{ fontSize: '15px', fontWeight: 'bold', marginBottom: '10px', borderBottom: '2px solid #e2e8f0', paddingBottom: '6px' }}>
            📄 تفاصيل الإقرارات
          </h3>
          {declarations.map((decl: any) => (
            <div key={decl.id} style={{ marginBottom: '12px', padding: '12px', border: '1px solid #e2e8f0', borderRadius: '8px', backgroundColor: '#fafafa' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '6px' }}>
                <span style={{ fontSize: '13px', fontWeight: 'bold' }}>
                  {declarationTypeLabels[decl.declaration_type] || decl.declaration_type}
                </span>
                <span style={{
                  padding: '2px 8px', borderRadius: '10px', fontSize: '10px', fontWeight: 'bold',
                  backgroundColor: decl.status === 'active' ? '#dcfce7' : decl.status === 'rejected' ? '#fee2e2' : '#f3f4f6',
                  color: decl.status === 'active' ? '#166534' : decl.status === 'rejected' ? '#991b1b' : '#6b7280',
                }}>
                  {decl.status === 'active' ? 'فعال' : decl.status === 'rejected' ? 'مرفوض' : 'معلق'}
                </span>
              </div>
              <div style={{ fontSize: '11px', color: '#666', lineHeight: '1.8' }}>
                {decl.driver_name && <div>🚛 السائق: {decl.driver_name} {decl.driver_national_id ? `(${decl.driver_national_id})` : ''}</div>}
                {decl.generator_name && <div>🏭 المولّد: {decl.generator_name}</div>}
                {decl.transporter_name && <div>🚚 الناقل: {decl.transporter_name}</div>}
                {decl.recycler_name && <div>♻️ المدوّر: {decl.recycler_name}</div>}
                <div>📅 التاريخ: {format(new Date(decl.declared_at), 'dd/MM/yyyy HH:mm:ss', { locale: ar })}</div>
                {decl.auto_generated && <div>🤖 تم الإنشاء تلقائياً بواسطة النظام</div>}
              </div>
              {decl.declaration_text && (
                <div style={{ marginTop: '8px', padding: '8px', backgroundColor: '#f0f9ff', borderRadius: '6px', fontSize: '10px', lineHeight: '1.6', color: '#334155', borderRight: '3px solid #3b82f6' }}>
                  {decl.declaration_text.substring(0, 300)}{decl.declaration_text.length > 300 ? '...' : ''}
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Receipts Detail */}
      {receipts.length > 0 && (
        <div style={{ marginBottom: '20px' }}>
          <h3 style={{ fontSize: '15px', fontWeight: 'bold', marginBottom: '10px', borderBottom: '2px solid #e2e8f0', paddingBottom: '6px' }}>
            🧾 شهادات الاستلام
          </h3>
          {receipts.map((rcp: any) => (
            <div key={rcp.id} style={{ marginBottom: '10px', padding: '10px', border: '1px solid #e2e8f0', borderRadius: '8px', backgroundColor: '#fafafa' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ fontSize: '13px', fontWeight: 'bold' }}>رقم الشهادة: {rcp.receipt_number}</span>
                <span style={{
                  padding: '2px 8px', borderRadius: '10px', fontSize: '10px', fontWeight: 'bold',
                  backgroundColor: rcp.status === 'confirmed' ? '#dcfce7' : '#fef3c7',
                  color: rcp.status === 'confirmed' ? '#166534' : '#92400e',
                }}>
                  {rcp.status === 'confirmed' ? 'مؤكد' : 'معلق'}
                </span>
              </div>
              {rcp.notes && <div style={{ fontSize: '11px', color: '#666', marginTop: '4px' }}>{rcp.notes}</div>}
              <div style={{ fontSize: '11px', color: '#666', marginTop: '4px' }}>
                📅 {format(new Date(rcp.created_at), 'dd/MM/yyyy HH:mm', { locale: ar })}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Footer */}
      <div style={{ borderTop: '2px solid #e2e8f0', paddingTop: '12px', display: 'flex', justifyContent: 'space-between', fontSize: '10px', color: '#94a3b8' }}>
        <div>تاريخ الطباعة: {format(new Date(), 'dd/MM/yyyy HH:mm', { locale: ar })}</div>
        <div>منصة إدارة النفايات — سلسلة الحيازة الرقمية</div>
        <div>الشحنة: {shipment.shipment_number}</div>
      </div>
    </div>
  );

  return (
    <>
      <Card>
        <CardHeader className="text-right pb-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 flex-wrap">
              <Badge variant="outline" className="text-xs">
                {completedCount}/{totalSteps} مكتمل
              </Badge>
              {completedCount < totalSteps && (
                <Button variant="outline" size="sm" className="h-7 text-xs gap-1" onClick={handleGenerateMissingDocs} disabled={generatingDocs}>
                  <RefreshCw className={`w-3 h-3 ${generatingDocs ? 'animate-spin' : ''}`} />
                  {generatingDocs ? 'جارٍ الإنشاء...' : 'إنشاء المفقودة'}
                </Button>
              )}
              {/* Print / PDF / Preview Actions */}
              <div className="flex items-center gap-1 no-print">
                <Button
                  variant="outline"
                  size="sm"
                  className="h-7 text-xs gap-1"
                  onClick={() => setShowPrintPreview(true)}
                >
                  <Eye className="w-3 h-3" />
                  عرض
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  className="h-7 text-xs gap-1"
                  onClick={() => {
                    // Brief delay for render
                    setShowPrintPreview(true);
                    setTimeout(() => {
                      printContent(printRef.current);
                    }, 500);
                  }}
                >
                  <Printer className="w-3 h-3" />
                  طباعة
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  className="h-7 text-xs gap-1"
                  disabled={isExporting}
                  onClick={() => {
                    setShowPrintPreview(true);
                    setTimeout(() => {
                      exportToPDF(printRef.current);
                    }, 500);
                  }}
                >
                  <Download className="w-3 h-3" />
                  PDF
                </Button>
              </div>
            </div>
            <CardTitle className="flex items-center gap-2 text-lg">
              <FileText className="w-5 h-5 text-primary" />
              سلسلة المستندات
            </CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          <div className="space-y-0">
            {steps.map((step, index) => {
              const isCompleted = step.status === 'completed';
              const isRejected = step.status === 'rejected';
              return (
                <div key={step.key} className="flex gap-3" dir="rtl">
                  <div className="flex flex-col items-center">
                    <div className={`w-8 h-8 rounded-full flex items-center justify-center border-2 ${getStepBorderClass(step.status)}`}>
                      {getStatusIcon(step.status)}
                    </div>
                    {index < steps.length - 1 && (
                      <div className={`w-0.5 h-full min-h-[32px] ${
                        isCompleted ? 'bg-green-300 dark:bg-green-700' : isRejected ? 'bg-red-300 dark:bg-red-700' : 'bg-muted'
                      }`} />
                    )}
                  </div>

                  <div className="flex-1 pb-4">
                    <div className={`p-3 rounded-lg border ${getContentBorderClass(step.status)}`}>
                      <div className="flex items-center justify-between gap-2 mb-1">
                        <div className="flex items-center gap-2">
                          {step.icon}
                          <span className="font-semibold text-sm">{step.label}</span>
                          {step.autoGenerated && (
                            <Badge variant="outline" className="text-[9px] px-1.5 py-0 gap-0.5">
                              <Bot className="w-3 h-3" />
                              تلقائي
                            </Badge>
                          )}
                        </div>
                        {isCompleted && (
                          <Badge className="bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200 text-[10px]">
                            مكتمل ✓
                          </Badge>
                        )}
                        {isRejected && (
                          <Badge className="bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200 text-[10px]">
                            <XCircle className="w-3 h-3 ml-0.5" />
                            مرفوض
                          </Badge>
                        )}
                      </div>

                      <p className="text-xs text-muted-foreground mb-2">{step.description}</p>

                      {isRejected && step.rejectionReason && (
                        <div className="bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-800 rounded p-2 mb-2 text-xs text-red-700 dark:text-red-300 flex items-start gap-1.5">
                          <AlertTriangle className="w-3.5 h-3.5 mt-0.5 shrink-0" />
                          <div>
                            <strong>سبب الرفض:</strong> {step.rejectionReason}
                          </div>
                        </div>
                      )}

                      {isCompleted && (
                        <div className="flex items-center justify-between text-[11px]">
                          <div className="text-muted-foreground">
                            {step.signedBy && <>بواسطة: <strong>{step.signedBy}</strong></>}
                            {step.signedAt && (
                              <> — {format(new Date(step.signedAt), 'dd/MM/yyyy HH:mm', { locale: ar })}</>
                            )}
                          </div>
                          <div className="flex items-center gap-1">
                            {step.data && step.key !== 'receipt' && (
                              <Button variant="ghost" size="sm" className="h-6 text-[10px] px-2" onClick={() => setShowDeclarationView(step.data)}>
                                <FileSignature className="w-3 h-3 ml-1" />
                                عرض
                              </Button>
                            )}
                            {step.canReject && (
                              <Button variant="ghost" size="sm" className="h-6 text-[10px] px-2 text-red-600 hover:text-red-700 hover:bg-red-50" onClick={() => setRejectingDeclaration(step.data)}>
                                <XCircle className="w-3 h-3 ml-1" />
                                إلغاء الإقرار
                              </Button>
                            )}
                          </div>
                        </div>
                      )}

                      {!isCompleted && !isRejected && step.actionAvailable && (
                        <Button
                          variant="eco"
                          size="sm"
                          className="mt-2 w-full h-8 text-xs"
                          onClick={() => {
                            if (step.key === 'generator_handover') {
                              setShowGeneratorHandover(true);
                            }
                          }}
                        >
                          <FileSignature className="w-3 h-3 ml-1" />
                          توقيع الإقرار
                        </Button>
                      )}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>

      {/* Print Preview Dialog */}
      <Dialog open={showPrintPreview} onOpenChange={setShowPrintPreview}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto" dir="rtl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5 text-primary" />
              معاينة سلسلة المستندات
            </DialogTitle>
          </DialogHeader>
          <div className="flex items-center gap-2 pb-3 border-b no-print">
            <Button
              variant="outline"
              size="sm"
              className="gap-1"
              onClick={() => printContent(printRef.current)}
            >
              <Printer className="w-4 h-4" />
              طباعة
            </Button>
            <Button
              variant="default"
              size="sm"
              className="gap-1"
              disabled={isExporting}
              onClick={() => exportToPDF(printRef.current)}
            >
              <Download className="w-4 h-4" />
              {isExporting ? 'جارٍ التصدير...' : 'حفظ PDF'}
            </Button>
          </div>
          <PrintableContent />
        </DialogContent>
      </Dialog>

      {/* Rejection Dialog */}
      <AlertDialog open={!!rejectingDeclaration} onOpenChange={(open) => { if (!open) { setRejectingDeclaration(null); setRejectionReason(''); } }}>
        <AlertDialogContent dir="rtl">
          <AlertDialogHeader>
            <AlertDialogTitle className="flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-red-500" />
              إلغاء الإقرار
            </AlertDialogTitle>
            <AlertDialogDescription>
              سيتم إلغاء هذا الإقرار وتسجيل أسباب الرفض. هل أنت متأكد؟
            </AlertDialogDescription>
          </AlertDialogHeader>
          <div className="py-2">
            <Textarea
              placeholder="اذكر أسباب الإلغاء / الرفض..."
              value={rejectionReason}
              onChange={(e) => setRejectionReason(e.target.value)}
              className="min-h-[80px] text-right"
              dir="rtl"
            />
          </div>
          <AlertDialogFooter className="flex-row-reverse gap-2">
            <AlertDialogCancel>تراجع</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleReject}
              disabled={!rejectionReason.trim() || rejecting}
              className="bg-red-600 hover:bg-red-700 text-white"
            >
              {rejecting ? 'جارٍ الإلغاء...' : 'تأكيد الإلغاء'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Generator Handover Dialog */}
      <GeneratorHandoverDialog
        open={showGeneratorHandover}
        onOpenChange={setShowGeneratorHandover}
        shipment={{
          id: shipment.id,
          shipment_number: shipment.shipment_number,
          waste_type: shipment.waste_type,
          quantity: shipment.quantity,
          unit: shipment.unit,
          transporter_name: shipment.transporter?.name,
          recycler_name: shipment.recycler?.name,
          disposal_name: shipment.manual_disposal_name,
        }}
        onConfirmed={() => {
          refetchDeclarations();
          onRefresh?.();
        }}
      />

      {/* Declaration View Dialog */}
      {showDeclarationView && (
        <DeliveryDeclarationViewDialog
          open={!!showDeclarationView}
          onOpenChange={(open) => { if (!open) setShowDeclarationView(null); }}
          declaration={showDeclarationView}
        />
      )}
    </>
  );
};

export default ShipmentDocumentsTimeline;
