import { useState, useCallback } from 'react';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { autoCreateGeneratorDeclaration, autoCreateRecyclerDeclaration } from '@/utils/autoDeclarationCreator';
import { autoCreateReceipt } from '@/utils/autoReceiptCreator';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import {
  FileSignature,
  FileCheck,
  Receipt,
  Truck,
  Building2,
  Recycle,
  CheckCircle2,
  Clock,
  FileText,
  XCircle,
  Bot,
  AlertTriangle,
  RefreshCw,
} from 'lucide-react';
import { format } from 'date-fns';
import { ar } from 'date-fns/locale';
import { toast } from 'sonner';
import GeneratorHandoverDialog from './GeneratorHandoverDialog';
import DeliveryDeclarationViewDialog from './DeliveryDeclarationViewDialog';
import { rejectDeclaration } from '@/utils/autoDeclarationCreator';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';

interface ShipmentDocumentsTimelineProps {
  shipment: {
    id: string;
    shipment_number: string;
    waste_type: string;
    quantity: number;
    unit?: string;
    status: string;
    generator_id?: string;
    transporter_id?: string;
    recycler_id?: string;
    generator?: { name: string } | null;
    transporter?: { name: string } | null;
    recycler?: { name: string } | null;
    manual_disposal_name?: string;
  };
  onRefresh?: () => void;
}

interface DocumentStep {
  key: string;
  label: string;
  icon: React.ReactNode;
  colorClass: string;
  description: string;
  status: 'completed' | 'pending' | 'rejected';
  signedBy?: string;
  signedAt?: string;
  actionAvailable?: boolean;
  canReject?: boolean;
  data?: any;
  autoGenerated?: boolean;
  rejectionReason?: string;
}

const ShipmentDocumentsTimeline = ({ shipment, onRefresh }: ShipmentDocumentsTimelineProps) => {
  const { profile, organization } = useAuth();
  const [showGeneratorHandover, setShowGeneratorHandover] = useState(false);
  const [showDeclarationView, setShowDeclarationView] = useState<any>(null);
  const [rejectingDeclaration, setRejectingDeclaration] = useState<any>(null);
  const [rejectionReason, setRejectionReason] = useState('');
  const [rejecting, setRejecting] = useState(false);
  const [generatingDocs, setGeneratingDocs] = useState(false);

  // Fetch all declarations for this shipment
  const { data: declarations = [], refetch: refetchDeclarations } = useQuery({
    queryKey: ['shipment-documents', shipment.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('delivery_declarations')
        .select('*')
        .eq('shipment_id', shipment.id)
        .order('created_at', { ascending: true });

      if (error) {
        console.error('Error fetching declarations:', error);
        return [];
      }
      return data || [];
    },
    staleTime: 1000 * 60 * 2,
  });

  // Fetch receipts for this shipment
  const { data: receipts = [] } = useQuery({
    queryKey: ['shipment-receipts', shipment.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('shipment_receipts')
        .select('id, receipt_number, status, created_at, created_by')
        .eq('shipment_id', shipment.id)
        .order('created_at', { ascending: true });

      if (error) {
        console.error('Error fetching receipts:', error);
        return [] as any[];
      }
      return (data || []) as any[];
    },
    staleTime: 1000 * 60 * 2,
  });

  const generatorDeclaration = declarations.find((d: any) => d.declaration_type === 'generator_handover' && (d as any).status !== 'rejected');
  const rejectedGeneratorDecl = declarations.find((d: any) => d.declaration_type === 'generator_handover' && (d as any).status === 'rejected');
  const transporterDeclaration = declarations.find((d: any) => (d.declaration_type === 'transporter_delivery' || !d.declaration_type) && (d as any).status !== 'rejected');
  const recyclerDeclaration = declarations.find((d: any) => d.declaration_type === 'recycler_receipt' && (d as any).status !== 'rejected');
  const rejectedRecyclerDecl = declarations.find((d: any) => d.declaration_type === 'recycler_receipt' && (d as any).status === 'rejected');
  const latestReceipt = receipts[receipts.length - 1] as any;

  const isGenerator = organization?.id === shipment.generator_id;
  const isRecycler = organization?.id === shipment.recycler_id;

  const handleReject = async () => {
    if (!rejectingDeclaration || !rejectionReason.trim()) return;
    setRejecting(true);
    try {
      await rejectDeclaration(rejectingDeclaration.id, organization?.id || '', rejectionReason.trim());
      toast.success('تم إلغاء الإقرار بنجاح');
      refetchDeclarations();
      onRefresh?.();
      setRejectingDeclaration(null);
      setRejectionReason('');
    } catch {
      toast.error('فشل في إلغاء الإقرار');
    } finally {
      setRejecting(false);
    }
  };

  // Auto-generate all missing documents for this shipment
  const handleGenerateMissingDocs = useCallback(async () => {
    if (!profile?.id) {
      toast.error('يجب تسجيل الدخول أولاً');
      return;
    }
    setGeneratingDocs(true);
    let created = 0;
    try {
      const status = shipment.status;
      
      // Generator declaration - should exist for approved/registered/in_transit/delivered/confirmed
      if (['approved', 'registered', 'in_transit', 'delivered', 'confirmed'].includes(status) && shipment.generator_id) {
        try {
          await autoCreateGeneratorDeclaration(shipment.id, shipment.generator_id, profile.id);
          created++;
        } catch (e) { console.error('Generator declaration:', e); }
      }

      // Recycler declaration - should exist for delivered/confirmed
      if (['delivered', 'confirmed'].includes(status) && shipment.recycler_id) {
        try {
          await autoCreateRecyclerDeclaration(shipment.id, shipment.recycler_id, profile.id);
          created++;
        } catch (e) { console.error('Recycler declaration:', e); }
      }

      // Receipt - should exist for in_transit/delivered/confirmed
      if (['in_transit', 'delivered', 'confirmed'].includes(status) && shipment.transporter_id) {
        try {
          await autoCreateReceipt(shipment.id, shipment.transporter_id, profile.id);
          created++;
        } catch (e) { console.error('Receipt:', e); }
      }

      if (created > 0) {
        toast.success(`تم إنشاء ${created} مستند(ات) مفقودة بنجاح`);
      } else {
        toast.info('جميع المستندات المتاحة موجودة بالفعل');
      }
      
      refetchDeclarations();
      onRefresh?.();
    } catch (error) {
      console.error('Error generating missing docs:', error);
      toast.error('حدث خطأ أثناء إنشاء المستندات');
    } finally {
      setGeneratingDocs(false);
    }
  }, [shipment, profile?.id, refetchDeclarations, onRefresh]);

  // Build the document steps
  const steps: DocumentStep[] = [
    {
      key: 'generator_handover',
      label: 'إقرار تسليم المولّد',
      icon: <Building2 className="w-4 h-4" />,
      colorClass: 'blue',
      description: rejectedGeneratorDecl
        ? `مرفوض: ${(rejectedGeneratorDecl as any).rejection_reason || 'بدون سبب'}`
        : 'المولّد يُقر بتسليم المخلفات للناقل — يتم تلقائياً عند بدء النقل',
      status: generatorDeclaration ? 'completed' : rejectedGeneratorDecl ? 'rejected' : 'pending',
      signedBy: generatorDeclaration?.driver_name || generatorDeclaration?.generator_name,
      signedAt: generatorDeclaration?.declared_at,
      actionAvailable: isGenerator && !generatorDeclaration,
      canReject: isGenerator && !!generatorDeclaration && (generatorDeclaration as any).status === 'active',
      data: generatorDeclaration || rejectedGeneratorDecl,
      autoGenerated: (generatorDeclaration as any)?.auto_generated,
      rejectionReason: (rejectedGeneratorDecl as any)?.rejection_reason,
    },
    {
      key: 'transporter_delivery',
      label: 'إقرار تسليم الناقل',
      icon: <Truck className="w-4 h-4" />,
      colorClass: 'purple',
      description: 'الناقل/السائق يُقر بتسليم الشحنة للمدوّر',
      status: transporterDeclaration ? 'completed' : 'pending',
      signedBy: transporterDeclaration?.driver_name || transporterDeclaration?.transporter_name,
      signedAt: transporterDeclaration?.declared_at,
      data: transporterDeclaration,
    },
    {
      key: 'recycler_receipt',
      label: 'إقرار استلام المدوّر',
      icon: <Recycle className="w-4 h-4" />,
      colorClass: 'emerald',
      description: rejectedRecyclerDecl
        ? `مرفوض: ${(rejectedRecyclerDecl as any).rejection_reason || 'بدون سبب'}`
        : 'المدوّر يُقر باستلام المخلفات — يتم تلقائياً عند التسليم',
      status: recyclerDeclaration ? 'completed' : rejectedRecyclerDecl ? 'rejected' : 'pending',
      signedBy: recyclerDeclaration?.recycler_name,
      signedAt: recyclerDeclaration?.declared_at,
      canReject: isRecycler && !!recyclerDeclaration && (recyclerDeclaration as any).status === 'active',
      data: recyclerDeclaration || rejectedRecyclerDecl,
      autoGenerated: (recyclerDeclaration as any)?.auto_generated,
      rejectionReason: (rejectedRecyclerDecl as any)?.rejection_reason,
    },
    {
      key: 'receipt',
      label: 'شهادة الاستلام',
      icon: <Receipt className="w-4 h-4" />,
      colorClass: 'green',
      description: 'شهادة استلام من المدوّر/جهة التخلص',
      status: latestReceipt ? 'completed' : 'pending',
      signedBy: latestReceipt?.issued_by_name,
      signedAt: latestReceipt?.created_at,
      data: latestReceipt,
    },
  ];

  const completedCount = steps.filter(s => s.status === 'completed').length;
  const totalSteps = steps.length;

  const getStatusIcon = (status: string) => {
    if (status === 'completed') return <CheckCircle2 className="w-4 h-4 text-green-600 dark:text-green-400" />;
    if (status === 'rejected') return <XCircle className="w-4 h-4 text-red-500" />;
    return <Clock className="w-4 h-4 text-muted-foreground" />;
  };

  const getStepBorderClass = (status: string) => {
    if (status === 'completed') return 'bg-green-100 border-green-400 dark:bg-green-900/30 dark:border-green-600';
    if (status === 'rejected') return 'bg-red-100 border-red-400 dark:bg-red-900/30 dark:border-red-600';
    return 'bg-muted/50 border-muted-foreground/20';
  };

  const getContentBorderClass = (status: string) => {
    if (status === 'completed') return 'border-green-200 bg-green-50/50 dark:border-green-800 dark:bg-green-950/20';
    if (status === 'rejected') return 'border-red-200 bg-red-50/50 dark:border-red-800 dark:bg-red-950/20';
    return 'border-muted bg-muted/10';
  };

  return (
    <>
      <Card>
        <CardHeader className="text-right pb-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Badge variant="outline" className="text-xs">
                {completedCount}/{totalSteps} مكتمل
              </Badge>
              {completedCount < totalSteps && (
                <Button
                  variant="outline"
                  size="sm"
                  className="h-7 text-xs gap-1"
                  onClick={handleGenerateMissingDocs}
                  disabled={generatingDocs}
                >
                  <RefreshCw className={`w-3 h-3 ${generatingDocs ? 'animate-spin' : ''}`} />
                  {generatingDocs ? 'جارٍ الإنشاء...' : 'إنشاء المفقودة'}
                </Button>
              )}
            </div>
            <CardTitle className="flex items-center gap-2 text-lg">
              <FileText className="w-5 h-5 text-primary" />
              سلسلة المستندات
            </CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          <div className="space-y-0">
            {steps.map((step, index) => {
              const isCompleted = step.status === 'completed';
              const isRejected = step.status === 'rejected';
              return (
                <div key={step.key} className="flex gap-3" dir="rtl">
                  {/* Timeline Line */}
                  <div className="flex flex-col items-center">
                    <div className={`w-8 h-8 rounded-full flex items-center justify-center border-2 ${getStepBorderClass(step.status)}`}>
                      {getStatusIcon(step.status)}
                    </div>
                    {index < steps.length - 1 && (
                      <div className={`w-0.5 h-full min-h-[32px] ${
                        isCompleted ? 'bg-green-300 dark:bg-green-700' : isRejected ? 'bg-red-300 dark:bg-red-700' : 'bg-muted'
                      }`} />
                    )}
                  </div>

                  {/* Content */}
                  <div className="flex-1 pb-4">
                    <div className={`p-3 rounded-lg border ${getContentBorderClass(step.status)}`}>
                      <div className="flex items-center justify-between gap-2 mb-1">
                        <div className="flex items-center gap-2">
                          {step.icon}
                          <span className="font-semibold text-sm">{step.label}</span>
                          {step.autoGenerated && (
                            <Badge variant="outline" className="text-[9px] px-1.5 py-0 gap-0.5">
                              <Bot className="w-3 h-3" />
                              تلقائي
                            </Badge>
                          )}
                        </div>
                        {isCompleted && (
                          <Badge className="bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200 text-[10px]">
                            مكتمل ✓
                          </Badge>
                        )}
                        {isRejected && (
                          <Badge className="bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200 text-[10px]">
                            <XCircle className="w-3 h-3 ml-0.5" />
                            مرفوض
                          </Badge>
                        )}
                      </div>

                      <p className="text-xs text-muted-foreground mb-2">{step.description}</p>

                      {isRejected && step.rejectionReason && (
                        <div className="bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-800 rounded p-2 mb-2 text-xs text-red-700 dark:text-red-300 flex items-start gap-1.5">
                          <AlertTriangle className="w-3.5 h-3.5 mt-0.5 shrink-0" />
                          <div>
                            <strong>سبب الرفض:</strong> {step.rejectionReason}
                          </div>
                        </div>
                      )}

                      {isCompleted && (
                        <div className="flex items-center justify-between text-[11px]">
                          <div className="text-muted-foreground">
                            {step.signedBy && <>بواسطة: <strong>{step.signedBy}</strong></>}
                            {step.signedAt && (
                              <> — {format(new Date(step.signedAt), 'dd/MM/yyyy HH:mm', { locale: ar })}</>
                            )}
                          </div>
                          <div className="flex items-center gap-1">
                            {step.data && step.key !== 'receipt' && (
                              <Button
                                variant="ghost"
                                size="sm"
                                className="h-6 text-[10px] px-2"
                                onClick={() => setShowDeclarationView(step.data)}
                              >
                                <FileSignature className="w-3 h-3 ml-1" />
                                عرض
                              </Button>
                            )}
                            {step.canReject && (
                              <Button
                                variant="ghost"
                                size="sm"
                                className="h-6 text-[10px] px-2 text-red-600 hover:text-red-700 hover:bg-red-50"
                                onClick={() => setRejectingDeclaration(step.data)}
                              >
                                <XCircle className="w-3 h-3 ml-1" />
                                إلغاء الإقرار
                              </Button>
                            )}
                          </div>
                        </div>
                      )}

                      {!isCompleted && !isRejected && step.actionAvailable && (
                        <Button
                          variant="eco"
                          size="sm"
                          className="mt-2 w-full h-8 text-xs"
                          onClick={() => {
                            if (step.key === 'generator_handover') {
                              setShowGeneratorHandover(true);
                            }
                          }}
                        >
                          <FileSignature className="w-3 h-3 ml-1" />
                          توقيع الإقرار
                        </Button>
                      )}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>

      {/* Rejection Dialog */}
      <AlertDialog open={!!rejectingDeclaration} onOpenChange={(open) => { if (!open) { setRejectingDeclaration(null); setRejectionReason(''); } }}>
        <AlertDialogContent dir="rtl">
          <AlertDialogHeader>
            <AlertDialogTitle className="flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-red-500" />
              إلغاء الإقرار
            </AlertDialogTitle>
            <AlertDialogDescription>
              سيتم إلغاء هذا الإقرار وتسجيل أسباب الرفض. هل أنت متأكد؟
            </AlertDialogDescription>
          </AlertDialogHeader>
          <div className="py-2">
            <Textarea
              placeholder="اذكر أسباب الإلغاء / الرفض..."
              value={rejectionReason}
              onChange={(e) => setRejectionReason(e.target.value)}
              className="min-h-[80px] text-right"
              dir="rtl"
            />
          </div>
          <AlertDialogFooter className="flex-row-reverse gap-2">
            <AlertDialogCancel>تراجع</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleReject}
              disabled={!rejectionReason.trim() || rejecting}
              className="bg-red-600 hover:bg-red-700 text-white"
            >
              {rejecting ? 'جارٍ الإلغاء...' : 'تأكيد الإلغاء'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Generator Handover Dialog */}
      <GeneratorHandoverDialog
        open={showGeneratorHandover}
        onOpenChange={setShowGeneratorHandover}
        shipment={{
          id: shipment.id,
          shipment_number: shipment.shipment_number,
          waste_type: shipment.waste_type,
          quantity: shipment.quantity,
          unit: shipment.unit,
          transporter_name: shipment.transporter?.name,
          recycler_name: shipment.recycler?.name,
          disposal_name: shipment.manual_disposal_name,
        }}
        onConfirmed={() => {
          refetchDeclarations();
          onRefresh?.();
        }}
      />

      {/* Declaration View Dialog */}
      {showDeclarationView && (
        <DeliveryDeclarationViewDialog
          open={!!showDeclarationView}
          onOpenChange={(open) => { if (!open) setShowDeclarationView(null); }}
          declaration={showDeclarationView}
        />
      )}
    </>
  );
};

export default ShipmentDocumentsTimeline;
