import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';

interface ShipmentData {
  id: string;
  shipment_number: string;
  generator_id: string | null;
  generator_name?: string;
  waste_type: string;
  waste_description?: string;
  quantity: number;
  unit: string;
  pickup_date?: string;
  unit_price?: number;
}

export const useAutoInvoice = () => {
  const { organization } = useAuth();

  const createInvoiceForShipment = async (shipment: ShipmentData) => {
    if (!organization?.id) {
      console.log('No organization found for auto invoice');
      return null;
    }

    try {
      // Get partner organization info
      let partnerName = shipment.generator_name || '';
      let partnerOrgId = shipment.generator_id;

      if (partnerOrgId) {
        const { data: partnerOrg } = await supabase
          .from('organizations')
          .select('name')
          .eq('id', partnerOrgId)
          .single();
        
        if (partnerOrg) {
          partnerName = partnerOrg.name;
        }
      }

      // Calculate price - use unit_price if provided, otherwise use default rate
      const unitPrice = shipment.unit_price || getDefaultPriceForWasteType(shipment.waste_type);
      const totalPrice = shipment.quantity * unitPrice;

      // Create invoice
      const { data: invoice, error: invoiceError } = await supabase
        .from('invoices')
        .insert({
          invoice_number: '', // Will be generated by trigger
          organization_id: organization.id,
          partner_organization_id: partnerOrgId,
          partner_name: partnerName,
          invoice_type: 'sales',
          invoice_category: 'shipment',
          status: 'draft',
          issue_date: new Date().toISOString().split('T')[0],
          due_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 30 days
          subtotal: totalPrice,
          tax_rate: 0,
          tax_amount: 0,
          discount_amount: 0,
          total_amount: totalPrice,
          paid_amount: 0,
          remaining_amount: totalPrice,
          currency: 'EGP',
          notes: `فاتورة تلقائية للشحنة رقم ${shipment.shipment_number}`,
        })
        .select()
        .single();

      if (invoiceError) throw invoiceError;

      // Create invoice item
      const { error: itemError } = await supabase
        .from('invoice_items')
        .insert({
          invoice_id: invoice.id,
          shipment_id: shipment.id,
          description: `${shipment.waste_type} - ${shipment.waste_description || 'شحنة نفايات'}`,
          quantity: shipment.quantity,
          unit: shipment.unit,
          unit_price: unitPrice,
          total_price: totalPrice,
          waste_type: shipment.waste_type,
          waste_quantity: shipment.quantity,
        });

      if (itemError) throw itemError;

      toast.success('تم إنشاء فاتورة تلقائية للشحنة', {
        description: `رقم الفاتورة: ${invoice.invoice_number || 'جاري التوليد'}`,
      });

      return invoice;
    } catch (error: any) {
      console.error('Error creating auto invoice:', error);
      // Don't show error to user - invoice is optional
      return null;
    }
  };

  return { createInvoiceForShipment };
};

// Default pricing based on waste type
function getDefaultPriceForWasteType(wasteType: string): number {
  const prices: Record<string, number> = {
    'بلاستيك': 2.5,
    'ورق': 1.5,
    'معادن': 5.0,
    'زجاج': 1.0,
    'خشب': 0.8,
    'نفايات صناعية': 3.0,
    'نفايات طبية': 10.0,
    'نفايات إلكترونية': 8.0,
    'نفايات خطرة': 15.0,
    'نفايات عضوية': 0.5,
    'مخلفات بناء': 0.3,
  };
  
  // Return price per kg, default to 1.0 if not found
  return prices[wasteType] || 1.0;
}
