import { useState, useEffect } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';

export type TicketStatus = 'open' | 'in_progress' | 'waiting_response' | 'resolved' | 'closed';
export type TicketPriority = 'low' | 'medium' | 'high' | 'urgent';
export type TicketCategory = 'bug' | 'feature_request' | 'technical_issue' | 'billing' | 'general' | 'complaint' | 'suggestion';

export interface SupportTicket {
  id: string;
  ticket_number: string;
  organization_id: string;
  created_by: string;
  assigned_to: string | null;
  partner_organization_id: string | null;
  related_shipment_id: string | null;
  title: string;
  description: string;
  category: TicketCategory;
  priority: TicketPriority;
  status: TicketStatus;
  resolution_notes: string | null;
  resolved_at: string | null;
  resolved_by: string | null;
  satisfaction_rating: number | null;
  satisfaction_feedback: string | null;
  created_at: string;
  updated_at: string;
  first_response_at: string | null;
  last_activity_at: string | null;
  organization?: { name: string; organization_type: string };
  partner_organization?: { name: string };
  creator?: { full_name: string };
  assignee?: { full_name: string };
}

export interface TicketMessage {
  id: string;
  ticket_id: string;
  sender_id: string;
  sender_organization_id: string | null;
  message: string;
  is_internal_note: boolean;
  is_from_admin: boolean;
  attachment_url: string | null;
  attachment_name: string | null;
  created_at: string;
  read_at: string | null;
  sender?: { full_name: string };
  sender_organization?: { name: string };
}

export interface CreateTicketData {
  title: string;
  description: string;
  category: TicketCategory;
  priority: TicketPriority;
  partner_organization_id?: string;
  related_shipment_id?: string;
}

export const useSupportTickets = () => {
  const { organization, profile, roles } = useAuth();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const isAdmin = roles.includes('admin');

  // Fetch tickets
  const { data: tickets = [], isLoading, refetch } = useQuery({
    queryKey: ['support-tickets', organization?.id, isAdmin],
    queryFn: async () => {
      let query = supabase
        .from('support_tickets')
        .select(`
          *,
          organization:organizations!support_tickets_organization_id_fkey(name, organization_type),
          partner_organization:organizations!support_tickets_partner_organization_id_fkey(name),
          creator:profiles!support_tickets_created_by_fkey(full_name),
          assignee:profiles!support_tickets_assigned_to_fkey(full_name)
        `)
        .order('created_at', { ascending: false });

      const { data, error } = await query;
      if (error) throw error;
      return data as SupportTicket[];
    },
    enabled: !!organization?.id || isAdmin,
  });

  // Create ticket
  const createTicket = useMutation({
    mutationFn: async (ticketData: CreateTicketData) => {
      // ticket_number is auto-generated by database trigger
      const insertData = {
        title: ticketData.title,
        description: ticketData.description,
        category: ticketData.category,
        priority: ticketData.priority,
        partner_organization_id: ticketData.partner_organization_id || null,
        related_shipment_id: ticketData.related_shipment_id || null,
        organization_id: organization?.id,
        created_by: profile?.id,
      };
      
      const { data, error } = await supabase
        .from('support_tickets')
        .insert(insertData as any)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['support-tickets'] });
      toast({
        title: 'تم إنشاء التذكرة',
        description: 'تم إرسال تذكرة الدعم بنجاح',
      });
    },
    onError: (error) => {
      toast({
        title: 'خطأ',
        description: 'فشل في إنشاء التذكرة',
        variant: 'destructive',
      });
    },
  });

  // Update ticket (admin)
  const updateTicket = useMutation({
    mutationFn: async ({ id, updates }: { id: string; updates: Partial<SupportTicket> }) => {
      const { data, error } = await supabase
        .from('support_tickets')
        .update({
          ...updates,
          updated_at: new Date().toISOString(),
          last_activity_at: new Date().toISOString(),
        })
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['support-tickets'] });
      toast({
        title: 'تم التحديث',
        description: 'تم تحديث التذكرة بنجاح',
      });
    },
  });

  // Close ticket with resolution
  const resolveTicket = useMutation({
    mutationFn: async ({ id, resolution_notes }: { id: string; resolution_notes: string }) => {
      const { data, error } = await supabase
        .from('support_tickets')
        .update({
          status: 'resolved',
          resolution_notes,
          resolved_at: new Date().toISOString(),
          resolved_by: profile?.id,
          last_activity_at: new Date().toISOString(),
        })
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['support-tickets'] });
      toast({
        title: 'تم حل التذكرة',
        description: 'تم إغلاق التذكرة بنجاح',
      });
    },
  });

  // Rate ticket satisfaction
  const rateTicket = useMutation({
    mutationFn: async ({ id, rating, feedback }: { id: string; rating: number; feedback?: string }) => {
      const { data, error } = await supabase
        .from('support_tickets')
        .update({
          satisfaction_rating: rating,
          satisfaction_feedback: feedback,
        })
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['support-tickets'] });
      toast({
        title: 'شكراً لتقييمك',
        description: 'تم حفظ تقييمك بنجاح',
      });
    },
  });

  return {
    tickets,
    isLoading,
    refetch,
    createTicket,
    updateTicket,
    resolveTicket,
    rateTicket,
    isAdmin,
  };
};

export const useTicketMessages = (ticketId: string) => {
  const { profile, organization, roles } = useAuth();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const isAdmin = roles.includes('admin');

  // Fetch messages
  const { data: messages = [], isLoading, refetch } = useQuery({
    queryKey: ['ticket-messages', ticketId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('ticket_messages')
        .select(`
          *,
          sender:profiles!ticket_messages_sender_id_fkey(full_name),
          sender_organization:organizations!ticket_messages_sender_organization_id_fkey(name)
        `)
        .eq('ticket_id', ticketId)
        .order('created_at', { ascending: true });

      if (error) throw error;
      return data as TicketMessage[];
    },
    enabled: !!ticketId,
  });

  // Subscribe to realtime messages
  useEffect(() => {
    if (!ticketId) return;

    const channel = supabase
      .channel(`ticket-messages-${ticketId}`)
      .on(
        'postgres_changes',
        {
          event: 'INSERT',
          schema: 'public',
          table: 'ticket_messages',
          filter: `ticket_id=eq.${ticketId}`,
        },
        () => {
          refetch();
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [ticketId, refetch]);

  // Send message
  const sendMessage = useMutation({
    mutationFn: async ({ message, isInternalNote = false }: { message: string; isInternalNote?: boolean }) => {
      const { data, error } = await supabase
        .from('ticket_messages')
        .insert({
          ticket_id: ticketId,
          sender_id: profile?.id,
          sender_organization_id: organization?.id,
          message,
          is_internal_note: isInternalNote,
          is_from_admin: isAdmin,
        })
        .select()
        .single();

      if (error) throw error;

      // Update ticket last activity
      await supabase
        .from('support_tickets')
        .update({
          last_activity_at: new Date().toISOString(),
          first_response_at: isAdmin ? new Date().toISOString() : undefined,
        })
        .eq('id', ticketId)
        .is('first_response_at', null);

      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ticket-messages', ticketId] });
      queryClient.invalidateQueries({ queryKey: ['support-tickets'] });
    },
    onError: () => {
      toast({
        title: 'خطأ',
        description: 'فشل في إرسال الرسالة',
        variant: 'destructive',
      });
    },
  });

  return {
    messages,
    isLoading,
    sendMessage,
    refetch,
    isAdmin,
  };
};

// Stats hook for admin dashboard
export const useSupportStats = () => {
  const { roles } = useAuth();
  const isAdmin = roles.includes('admin');

  const { data: stats } = useQuery({
    queryKey: ['support-stats'],
    queryFn: async () => {
      const { data: tickets, error } = await supabase
        .from('support_tickets')
        .select('status, priority, created_at, resolved_at, satisfaction_rating');

      if (error) throw error;

      const total = tickets.length;
      const open = tickets.filter(t => t.status === 'open').length;
      const inProgress = tickets.filter(t => t.status === 'in_progress').length;
      const resolved = tickets.filter(t => t.status === 'resolved' || t.status === 'closed').length;
      const urgent = tickets.filter(t => t.priority === 'urgent' && t.status !== 'resolved' && t.status !== 'closed').length;
      
      const avgRating = tickets
        .filter(t => t.satisfaction_rating)
        .reduce((acc, t) => acc + (t.satisfaction_rating || 0), 0) / 
        (tickets.filter(t => t.satisfaction_rating).length || 1);

      return {
        total,
        open,
        inProgress,
        resolved,
        urgent,
        avgRating: avgRating.toFixed(1),
      };
    },
    enabled: isAdmin,
  });

  return stats;
};
