import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { 
  Plus, 
  Trash2, 
  FileText, 
  Calendar, 
  Building2,
  Package,
  Loader2,
  Save,
} from 'lucide-react';
import { format } from 'date-fns';
import { ar } from 'date-fns/locale';

const wasteTypes = [
  { value: 'plastic', label: 'بلاستيك' },
  { value: 'paper', label: 'ورق وكرتون' },
  { value: 'metal', label: 'معادن' },
  { value: 'glass', label: 'زجاج' },
  { value: 'organic', label: 'عضوية' },
  { value: 'electronic', label: 'إلكترونية' },
  { value: 'chemical', label: 'كيميائية' },
  { value: 'construction', label: 'مخلفات بناء' },
  { value: 'medical', label: 'طبية' },
  { value: 'textile', label: 'منسوجات' },
  { value: 'other', label: 'أخرى' },
];

const formSchema = z.object({
  title: z.string().min(1, 'عنوان الخطاب مطلوب'),
  partner_organization_id: z.string().optional(),
  issue_date: z.string().min(1, 'تاريخ الإصدار مطلوب'),
  start_date: z.string().min(1, 'تاريخ البداية مطلوب'),
  end_date: z.string().optional(),
  description: z.string().optional(),
  notes: z.string().optional(),
});

interface PriceItem {
  id: string;
  waste_type: string;
  waste_description: string;
  unit_price: number;
  unit: string;
}

interface AwardLetterFormProps {
  onSuccess?: () => void;
  existingLetter?: any;
}

export default function AwardLetterForm({ onSuccess, existingLetter }: AwardLetterFormProps) {
  const { organization } = useAuth();
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [priceItems, setPriceItems] = useState<PriceItem[]>(
    existingLetter?.items || []
  );
  const [newItem, setNewItem] = useState<Partial<PriceItem>>({
    waste_type: '',
    waste_description: '',
    unit_price: 0,
    unit: 'kg',
  });

  const { register, handleSubmit, formState: { errors }, setValue, watch } = useForm({
    resolver: zodResolver(formSchema),
    defaultValues: existingLetter || {
      title: '',
      partner_organization_id: '',
      issue_date: format(new Date(), 'yyyy-MM-dd'),
      start_date: format(new Date(), 'yyyy-MM-dd'),
      end_date: '',
      description: '',
      notes: '',
    },
  });

  const addPriceItem = () => {
    if (!newItem.waste_type || !newItem.unit_price) {
      toast({
        title: 'خطأ',
        description: 'يجب تحديد نوع المخلف والسعر',
        variant: 'destructive',
      });
      return;
    }

    setPriceItems([
      ...priceItems,
      {
        id: crypto.randomUUID(),
        waste_type: newItem.waste_type!,
        waste_description: newItem.waste_description || '',
        unit_price: newItem.unit_price!,
        unit: newItem.unit || 'kg',
      },
    ]);

    setNewItem({
      waste_type: '',
      waste_description: '',
      unit_price: 0,
      unit: 'kg',
    });
  };

  const removePriceItem = (id: string) => {
    setPriceItems(priceItems.filter(item => item.id !== id));
  };

  const onSubmit = async (data: any) => {
    if (!organization?.id) return;

    if (priceItems.length === 0) {
      toast({
        title: 'خطأ',
        description: 'يجب إضافة بند سعر واحد على الأقل',
        variant: 'destructive',
      });
      return;
    }

    setLoading(true);
    try {
      // Insert award letter
      const { data: letter, error: letterError } = await supabase
        .from('award_letters')
        .insert({
          organization_id: organization.id,
          partner_organization_id: data.partner_organization_id || null,
          title: data.title,
          issue_date: data.issue_date,
          start_date: data.start_date,
          end_date: data.end_date || null,
          description: data.description || null,
          notes: data.notes || null,
          status: 'active',
          letter_number: '', // Will be auto-generated by trigger
        } as any)
        .select()
        .single();

      if (letterError) throw letterError;

      // Insert price items
      const itemsToInsert = priceItems.map(item => ({
        award_letter_id: letter.id,
        waste_type: item.waste_type,
        waste_description: item.waste_description,
        unit_price: item.unit_price,
        unit: item.unit,
      }));

      const { error: itemsError } = await supabase
        .from('award_letter_items')
        .insert(itemsToInsert);

      if (itemsError) throw itemsError;

      toast({
        title: 'تم بنجاح',
        description: 'تم إنشاء خطاب الترسية بنجاح',
      });

      onSuccess?.();
    } catch (error: any) {
      console.error('Error creating award letter:', error);
      toast({
        title: 'خطأ',
        description: error.message || 'حدث خطأ أثناء الحفظ',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
      {/* Basic Info */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" />
            بيانات خطاب الترسية
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="title">عنوان الخطاب *</Label>
              <Input
                id="title"
                placeholder="مثال: ترسية نستله - فبراير 2026"
                {...register('title')}
              />
              {errors.title && (
                <p className="text-sm text-destructive">{errors.title.message as string}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="issue_date">تاريخ الإصدار *</Label>
              <Input
                id="issue_date"
                type="date"
                {...register('issue_date')}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="start_date">تاريخ بداية السريان *</Label>
              <Input
                id="start_date"
                type="date"
                {...register('start_date')}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="end_date">تاريخ انتهاء السريان</Label>
              <Input
                id="end_date"
                type="date"
                {...register('end_date')}
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="description">وصف الخطاب</Label>
            <Textarea
              id="description"
              placeholder="وصف تفصيلي لخطاب الترسية..."
              {...register('description')}
            />
          </div>
        </CardContent>
      </Card>

      {/* Price Items */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Package className="h-5 w-5 text-primary" />
            بنود الأسعار
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Add new item form */}
          <div className="p-4 border rounded-lg bg-muted/30 space-y-4">
            <p className="text-sm font-medium">إضافة بند سعر جديد</p>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="space-y-2">
                <Label>نوع المخلف</Label>
                <Select
                  value={newItem.waste_type}
                  onValueChange={(value) => setNewItem({ ...newItem, waste_type: value })}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="اختر النوع" />
                  </SelectTrigger>
                  <SelectContent>
                    {wasteTypes.map(type => (
                      <SelectItem key={type.value} value={type.value}>
                        {type.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label>وصف إضافي</Label>
                <Input
                  placeholder="مثال: كراتين نظيفة"
                  value={newItem.waste_description}
                  onChange={(e) => setNewItem({ ...newItem, waste_description: e.target.value })}
                />
              </div>

              <div className="space-y-2">
                <Label>السعر (ج.م)</Label>
                <Input
                  type="number"
                  placeholder="0.00"
                  value={newItem.unit_price || ''}
                  onChange={(e) => setNewItem({ ...newItem, unit_price: parseFloat(e.target.value) || 0 })}
                />
              </div>

              <div className="space-y-2">
                <Label>الوحدة</Label>
                <div className="flex gap-2">
                  <Select
                    value={newItem.unit}
                    onValueChange={(value) => setNewItem({ ...newItem, unit: value })}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="kg">كيلوجرام</SelectItem>
                      <SelectItem value="ton">طن</SelectItem>
                      <SelectItem value="unit">وحدة</SelectItem>
                      <SelectItem value="m3">متر مكعب</SelectItem>
                    </SelectContent>
                  </Select>
                  <Button type="button" onClick={addPriceItem} size="icon">
                    <Plus className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            </div>
          </div>

          <Separator />

          {/* Items list */}
          {priceItems.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              <Package className="h-12 w-12 mx-auto mb-4 opacity-50" />
              <p>لم يتم إضافة أي بنود أسعار بعد</p>
            </div>
          ) : (
            <div className="space-y-2">
              {priceItems.map((item, index) => (
                <div
                  key={item.id}
                  className="flex items-center justify-between p-3 border rounded-lg hover:bg-muted/50"
                >
                  <div className="flex items-center gap-4">
                    <Badge variant="secondary">{index + 1}</Badge>
                    <div>
                      <p className="font-medium">
                        {wasteTypes.find(t => t.value === item.waste_type)?.label || item.waste_type}
                        {item.waste_description && (
                          <span className="text-muted-foreground"> - {item.waste_description}</span>
                        )}
                      </p>
                      <p className="text-sm text-muted-foreground">
                        {item.unit_price.toLocaleString('ar-EG')} ج.م / {item.unit === 'kg' ? 'كجم' : item.unit === 'ton' ? 'طن' : item.unit}
                      </p>
                    </div>
                  </div>
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    onClick={() => removePriceItem(item.id)}
                    className="text-destructive hover:text-destructive"
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Submit */}
      <div className="flex justify-end gap-4">
        <Button type="submit" disabled={loading} className="gap-2">
          {loading ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <Save className="h-4 w-4" />
          )}
          حفظ خطاب الترسية
        </Button>
      </div>
    </form>
  );
}
