import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { Progress } from '@/components/ui/progress';
import {
  Factory, Plus, Loader2, CheckCircle2, ArrowDown, ArrowUp,
  Package, Scale, Zap, DollarSign, TrendingUp, BarChart3
} from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';

const WASTE_TYPES = [
  'بلاستيك PET', 'بلاستيك HDPE', 'بلاستيك PVC', 'بلاستيك LDPE',
  'ورق', 'كرتون', 'حديد', 'ألومنيوم', 'نحاس', 'زجاج',
  'خشب', 'إطارات', 'زيوت مستعملة', 'أخرى',
];

const OUTPUT_TYPES = [
  'حبيبات بلاستيكية', 'رقائق بلاستيكية', 'لب ورق', 'خردة معدنية مفرزة',
  'زجاج مكسر نظيف', 'كمبوست', 'وقود بديل RDF', 'زيوت معاد تكريرها',
  'مسحوق مطاط', 'أخرى',
];

const ProductionBatchTracker = () => {
  const { organization, user } = useAuth();
  const queryClient = useQueryClient();
  const [showDialog, setShowDialog] = useState(false);

  const [form, setForm] = useState({
    input_waste_type: '',
    input_quantity: '',
    input_unit: 'طن',
    output_product_type: '',
    output_quantity: '',
    output_unit: 'طن',
    waste_residue_quantity: '',
    production_line: '',
    labor_cost: '',
    energy_cost: '',
    materials_cost: '',
    quality_grade: '',
    notes: '',
  });

  const { data: batches, isLoading } = useQuery({
    queryKey: ['production-batches', organization?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('production_batches')
        .select('*')
        .eq('organization_id', organization!.id)
        .order('created_at', { ascending: false })
        .limit(50);
      if (error) throw error;
      return data || [];
    },
    enabled: !!organization?.id,
  });

  const createMutation = useMutation({
    mutationFn: async () => {
      const { error } = await supabase.from('production_batches').insert({
        organization_id: organization!.id,
        batch_number: '', // auto-generated by trigger
        input_waste_type: form.input_waste_type,
        input_quantity: parseFloat(form.input_quantity) || 0,
        input_unit: form.input_unit,
        output_product_type: form.output_product_type || null,
        output_quantity: parseFloat(form.output_quantity) || 0,
        output_unit: form.output_unit,
        waste_residue_quantity: parseFloat(form.waste_residue_quantity) || 0,
        production_line: form.production_line || null,
        labor_cost: parseFloat(form.labor_cost) || 0,
        energy_cost: parseFloat(form.energy_cost) || 0,
        materials_cost: parseFloat(form.materials_cost) || 0,
        quality_grade: form.quality_grade || null,
        notes: form.notes || null,
        status: form.output_quantity ? 'completed' : 'in_progress',
        completed_at: form.output_quantity ? new Date().toISOString() : null,
        created_by: user?.id,
      });
      if (error) throw error;
    },
    onSuccess: () => {
      toast.success('تم تسجيل الدُفعة بنجاح');
      queryClient.invalidateQueries({ queryKey: ['production-batches'] });
      setShowDialog(false);
      resetForm();
    },
    onError: () => toast.error('حدث خطأ في تسجيل الدُفعة'),
  });

  const completeBatch = useMutation({
    mutationFn: async ({ id, output_quantity }: { id: string; output_quantity: number }) => {
      const { error } = await supabase.from('production_batches')
        .update({ status: 'completed', output_quantity, completed_at: new Date().toISOString() })
        .eq('id', id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['production-batches'] });
      toast.success('تم إكمال الدُفعة');
    },
  });

  const resetForm = () => setForm({
    input_waste_type: '', input_quantity: '', input_unit: 'طن',
    output_product_type: '', output_quantity: '', output_unit: 'طن',
    waste_residue_quantity: '', production_line: '',
    labor_cost: '', energy_cost: '', materials_cost: '',
    quality_grade: '', notes: '',
  });

  // Stats
  const completedBatches = batches?.filter(b => b.status === 'completed') || [];
  const avgExtraction = completedBatches.length > 0
    ? (completedBatches.reduce((sum, b) => sum + (b.extraction_rate || 0), 0) / completedBatches.length).toFixed(1)
    : '0';
  const totalInput = batches?.reduce((sum, b) => sum + (b.input_quantity || 0), 0) || 0;
  const totalOutput = batches?.reduce((sum, b) => sum + (b.output_quantity || 0), 0) || 0;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-bold flex items-center gap-2">
            <Factory className="w-5 h-5 text-primary" />
            تتبع الإنتاج (مدخلات ← مخرجات)
          </h3>
          <p className="text-sm text-muted-foreground">تتبع تحويل المخلفات إلى منتجات مع حساب الكفاءة</p>
        </div>
        <Button onClick={() => setShowDialog(true)} className="gap-2">
          <Plus className="w-4 h-4" /> دُفعة جديدة
        </Button>
      </div>

      {/* Summary Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <Card><CardContent className="pt-4 text-center">
          <ArrowDown className="w-5 h-5 mx-auto text-amber-500 mb-1" />
          <p className="text-2xl font-bold">{totalInput.toLocaleString()}</p>
          <p className="text-xs text-muted-foreground">إجمالي المدخلات (طن)</p>
        </CardContent></Card>
        <Card><CardContent className="pt-4 text-center">
          <ArrowUp className="w-5 h-5 mx-auto text-emerald-500 mb-1" />
          <p className="text-2xl font-bold">{totalOutput.toLocaleString()}</p>
          <p className="text-xs text-muted-foreground">إجمالي المخرجات (طن)</p>
        </CardContent></Card>
        <Card><CardContent className="pt-4 text-center">
          <TrendingUp className="w-5 h-5 mx-auto text-primary mb-1" />
          <p className="text-2xl font-bold">{avgExtraction}%</p>
          <p className="text-xs text-muted-foreground">متوسط نسبة الاستخلاص</p>
        </CardContent></Card>
        <Card><CardContent className="pt-4 text-center">
          <BarChart3 className="w-5 h-5 mx-auto text-blue-500 mb-1" />
          <p className="text-2xl font-bold">{batches?.length || 0}</p>
          <p className="text-xs text-muted-foreground">إجمالي الدُفعات</p>
        </CardContent></Card>
      </div>

      {/* Batches List */}
      {isLoading ? (
        <div className="flex justify-center py-8"><Loader2 className="w-6 h-6 animate-spin" /></div>
      ) : !batches?.length ? (
        <Card className="border-dashed">
          <CardContent className="py-12 text-center">
            <Factory className="w-12 h-12 mx-auto text-muted-foreground/40 mb-3" />
            <p className="text-muted-foreground">لا توجد دُفعات إنتاج مسجلة</p>
            <Button variant="outline" className="mt-3 gap-2" onClick={() => setShowDialog(true)}>
              <Plus className="w-4 h-4" /> تسجيل أول دُفعة
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-3">
          {batches.map((b: any) => (
            <Card key={b.id}>
              <CardContent className="pt-4">
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <p className="font-medium text-sm flex items-center gap-2">
                      <Package className="w-4 h-4 text-primary" />
                      {b.batch_number}
                      {b.production_line && <Badge variant="outline" className="text-[10px]">{b.production_line}</Badge>}
                    </p>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      {new Date(b.created_at).toLocaleDateString('ar-EG')}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    {b.quality_grade && (
                      <Badge variant="outline" className={`text-xs ${
                        b.quality_grade === 'A' ? 'border-emerald-500 text-emerald-600' :
                        b.quality_grade === 'B' ? 'border-amber-500 text-amber-600' :
                        'border-red-500 text-red-600'
                      }`}>
                        درجة {b.quality_grade}
                      </Badge>
                    )}
                    <Badge variant={b.status === 'completed' ? 'default' : 'secondary'}>
                      {b.status === 'completed' ? 'مكتمل' : b.status === 'in_progress' ? 'قيد التشغيل' : 'ملغى'}
                    </Badge>
                  </div>
                </div>

                <div className="grid grid-cols-3 gap-4 text-center py-2 bg-muted/30 rounded-lg mb-2">
                  <div>
                    <p className="text-xs text-muted-foreground flex items-center justify-center gap-1"><ArrowDown className="w-3 h-3" /> مدخلات</p>
                    <p className="font-bold text-sm">{b.input_quantity} {b.input_unit}</p>
                    <p className="text-[10px] text-muted-foreground">{b.input_waste_type}</p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">نسبة الاستخلاص</p>
                    <p className="font-bold text-sm text-primary">{b.extraction_rate || 0}%</p>
                    <Progress value={b.extraction_rate || 0} className="h-1.5 mt-1" />
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground flex items-center justify-center gap-1"><ArrowUp className="w-3 h-3" /> مخرجات</p>
                    <p className="font-bold text-sm">{b.output_quantity} {b.output_unit}</p>
                    <p className="text-[10px] text-muted-foreground">{b.output_product_type || '-'}</p>
                  </div>
                </div>

                {(b.total_cost > 0) && (
                  <div className="flex items-center gap-3 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1"><DollarSign className="w-3 h-3" /> التكلفة: {b.total_cost?.toLocaleString()} ج.م</span>
                    {b.cost_per_ton > 0 && (
                      <span>• تكلفة الطن: {b.cost_per_ton?.toLocaleString()} ج.م</span>
                    )}
                  </div>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Create Dialog */}
      <Dialog open={showDialog} onOpenChange={setShowDialog}>
        <DialogContent className="max-w-md max-h-[90vh] overflow-y-auto" dir="rtl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Factory className="w-5 h-5 text-primary" />
              تسجيل دُفعة إنتاج جديدة
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            {/* Inputs */}
            <div className="p-3 rounded-lg border border-amber-500/30 bg-amber-500/5 space-y-3">
              <p className="text-xs font-bold flex items-center gap-1 text-amber-700 dark:text-amber-400">
                <ArrowDown className="w-3.5 h-3.5" /> المدخلات (المواد الخام)
              </p>
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <Label className="text-xs">نوع المخلف *</Label>
                  <Select value={form.input_waste_type} onValueChange={(v) => setForm(f => ({ ...f, input_waste_type: v }))}>
                    <SelectTrigger className="text-sm"><SelectValue placeholder="اختر" /></SelectTrigger>
                    <SelectContent>{WASTE_TYPES.map(t => <SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent>
                  </Select>
                </div>
                <div className="space-y-1">
                  <Label className="text-xs">الكمية *</Label>
                  <Input type="number" value={form.input_quantity} onChange={(e) => setForm(f => ({ ...f, input_quantity: e.target.value }))} placeholder="0" className="text-sm" dir="ltr" />
                </div>
              </div>
            </div>

            {/* Outputs */}
            <div className="p-3 rounded-lg border border-emerald-500/30 bg-emerald-500/5 space-y-3">
              <p className="text-xs font-bold flex items-center gap-1 text-emerald-700 dark:text-emerald-400">
                <ArrowUp className="w-3.5 h-3.5" /> المخرجات (المنتج النهائي)
              </p>
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <Label className="text-xs">نوع المنتج</Label>
                  <Select value={form.output_product_type} onValueChange={(v) => setForm(f => ({ ...f, output_product_type: v }))}>
                    <SelectTrigger className="text-sm"><SelectValue placeholder="اختر" /></SelectTrigger>
                    <SelectContent>{OUTPUT_TYPES.map(t => <SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent>
                  </Select>
                </div>
                <div className="space-y-1">
                  <Label className="text-xs">الكمية</Label>
                  <Input type="number" value={form.output_quantity} onChange={(e) => setForm(f => ({ ...f, output_quantity: e.target.value }))} placeholder="0" className="text-sm" dir="ltr" />
                </div>
              </div>
              <div className="space-y-1">
                <Label className="text-xs">كمية الهالك / المخلفات المتبقية</Label>
                <Input type="number" value={form.waste_residue_quantity} onChange={(e) => setForm(f => ({ ...f, waste_residue_quantity: e.target.value }))} placeholder="0" className="text-sm" dir="ltr" />
              </div>
            </div>

            {/* Costs */}
            <div className="p-3 rounded-lg border space-y-3">
              <p className="text-xs font-bold flex items-center gap-1"><DollarSign className="w-3.5 h-3.5" /> التكاليف (ج.م)</p>
              <div className="grid grid-cols-3 gap-2">
                <div className="space-y-1">
                  <Label className="text-[10px]">عمالة</Label>
                  <Input type="number" value={form.labor_cost} onChange={(e) => setForm(f => ({ ...f, labor_cost: e.target.value }))} placeholder="0" className="text-sm h-8" dir="ltr" />
                </div>
                <div className="space-y-1">
                  <Label className="text-[10px]">طاقة</Label>
                  <Input type="number" value={form.energy_cost} onChange={(e) => setForm(f => ({ ...f, energy_cost: e.target.value }))} placeholder="0" className="text-sm h-8" dir="ltr" />
                </div>
                <div className="space-y-1">
                  <Label className="text-[10px]">مواد</Label>
                  <Input type="number" value={form.materials_cost} onChange={(e) => setForm(f => ({ ...f, materials_cost: e.target.value }))} placeholder="0" className="text-sm h-8" dir="ltr" />
                </div>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1">
                <Label className="text-xs">خط الإنتاج</Label>
                <Input value={form.production_line} onChange={(e) => setForm(f => ({ ...f, production_line: e.target.value }))} placeholder="مثال: خط 1" className="text-sm" />
              </div>
              <div className="space-y-1">
                <Label className="text-xs">درجة الجودة</Label>
                <Select value={form.quality_grade} onValueChange={(v) => setForm(f => ({ ...f, quality_grade: v }))}>
                  <SelectTrigger className="text-sm"><SelectValue placeholder="اختر" /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="A">A - ممتاز</SelectItem>
                    <SelectItem value="B">B - جيد</SelectItem>
                    <SelectItem value="C">C - مقبول</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="space-y-1">
              <Label className="text-xs">ملاحظات</Label>
              <Textarea value={form.notes} onChange={(e) => setForm(f => ({ ...f, notes: e.target.value }))} rows={2} className="text-sm" />
            </div>
          </div>
          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setShowDialog(false)}>إلغاء</Button>
            <Button
              onClick={() => createMutation.mutate()}
              disabled={!form.input_waste_type || !form.input_quantity || createMutation.isPending}
              className="gap-2"
            >
              {createMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Plus className="w-4 h-4" />}
              تسجيل الدُفعة
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default ProductionBatchTracker;
